schema.archiveSha256=f88029322c98d33a4eb3f2cac929f1dff7975604b5497b41e7466f87732ea732
schema.manifest=framework/materials/cloudformation-schema.sha256
schema.region=ap-northeast-1
schema.resourceTypeCount=149
schema.source=AWS CloudFormation resource provider schemas
schema.sourceUrl=https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip
