schema.archiveSha256=f8192b68240f0f3bbe7727c301d131995ef2828f32273cbfb4a95b6dd09c0e0c
schema.manifest=framework/materials/cloudformation-schema.sha256
schema.region=ap-northeast-1
schema.resourceTypeCount=154
schema.source=AWS CloudFormation resource provider schemas
schema.sourceUrl=https://schema.cloudformation.ap-northeast-1.amazonaws.com/CloudformationSchema.zip
