alb.ALB01.loadBalancerName=alb-dev-web01
alb.ALB01.scheme=internet-facing
alb.ALB01.type=application
alb.ALB01.ipAddressType=ipv4
alb.ALB01.subnets=PUBLICAZ1,PUBLICAZ2
alb.ALB01.securityGroup=ALBSG01
alb.ALB01.accessLogsEnabled=false
alb.ALB01.template=infra/cloudformation/templates/app.yaml
alb.TG01.targetGroupName=tgp-dev-web01
alb.TG01.targetType=instance
alb.TG01.protocol=HTTP
alb.TG01.port=80
alb.TG01.healthCheckProtocol=HTTP
alb.TG01.healthCheckPath=/
alb.TG01.healthCheckMatcher=200-399
alb.TG01.deregistrationDelaySeconds=60
alb.TG01.targets=EC2AZ1,EC2AZ2
alb.TG01.template=infra/cloudformation/templates/app.yaml
alb.HTTP80.protocol=HTTP
alb.HTTP80.port=80
alb.HTTP80.defaultAction=forward to TG01
alb.HTTP80.template=infra/cloudformation/templates/app.yaml