alb.ALB01.loadBalancerName=alb-dev-web01
alb.ALB01.scheme=internet-facing
alb.ALB01.type=application
alb.ALB01.ipAddressType=ipv4
alb.ALB01.subnets=PUBAZ1,PUBAZ2
alb.ALB01.securityGroup=ALBSG01
alb.ALB01.template=infra/cloudformation/templates/web-service.yaml
alb.TGP01.targetGroupName=tgp-dev-web01
alb.TGP01.targetType=instance
alb.TGP01.protocol=HTTP
alb.TGP01.port=80
alb.TGP01.healthCheckPath=/
alb.TGP01.matcher=200
alb.TGP01.targets=WEB01,WEB02
alb.TGP01.template=infra/cloudformation/templates/web-service.yaml
alb.HTTP80.protocol=HTTP
alb.HTTP80.port=80
alb.HTTP80.defaultAction=forward to TGP01
alb.HTTP80.template=infra/cloudformation/templates/web-service.yaml