ec2.WEBNGINXEC2ROLE01.roleName=webNginxEc2Role
ec2.WEBNGINXEC2ROLE01.managedPolicy=arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
ec2.WEBNGINXEC2ROLE01.purpose=EC2 bootstrap and session management
ec2.WEBNGINXEC2ROLE01.template=infra/cloudformation/templates/app.yaml
ec2.WEBNGINXEC2PROFILE01.instanceProfileName=webNginxEc2Profile
ec2.WEBNGINXEC2PROFILE01.role=WEBNGINXEC2ROLE01
ec2.WEBNGINXEC2PROFILE01.template=infra/cloudformation/templates/app.yaml
ec2.EC2AZ1.nameTag=dev-web-a01
ec2.EC2AZ1.availabilityZone=ap-northeast-1a
ec2.EC2AZ1.subnet=PRIVATEAPPAZ1
ec2.EC2AZ1.instanceType=t3.small
ec2.EC2AZ1.architecture=x86_64
ec2.EC2AZ1.amiSsmParameter=/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
ec2.EC2AZ1.associatePublicIpAddress=false
ec2.EC2AZ1.securityGroup=EC2SG01
ec2.EC2AZ1.instanceProfile=WEBNGINXEC2PROFILE01
ec2.EC2AZ1.rootVolumeType=gp3
ec2.EC2AZ1.rootVolumeSizeGiB=8
ec2.EC2AZ1.metadataHttpTokens=required
ec2.EC2AZ1.template=infra/cloudformation/templates/app.yaml
ec2.EC2AZ2.nameTag=dev-web-c01
ec2.EC2AZ2.availabilityZone=ap-northeast-1c
ec2.EC2AZ2.subnet=PRIVATEAPPAZ2
ec2.EC2AZ2.instanceType=t3.small
ec2.EC2AZ2.architecture=x86_64
ec2.EC2AZ2.amiSsmParameter=/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
ec2.EC2AZ2.associatePublicIpAddress=false
ec2.EC2AZ2.securityGroup=EC2SG01
ec2.EC2AZ2.instanceProfile=WEBNGINXEC2PROFILE01
ec2.EC2AZ2.rootVolumeType=gp3
ec2.EC2AZ2.rootVolumeSizeGiB=8
ec2.EC2AZ2.metadataHttpTokens=required
ec2.EC2AZ2.template=infra/cloudformation/templates/app.yaml
ec2.NGINXBOOTSTRAP01.packageManager=dnf
ec2.NGINXBOOTSTRAP01.installPackage=nginx
ec2.NGINXBOOTSTRAP01.systemdEnable=true
ec2.NGINXBOOTSTRAP01.indexPageContent=systemName/env/hostname/instance-id/availability-zone
ec2.NGINXBOOTSTRAP01.idempotentApproach=rpm query and overwrite index.html
ec2.NGINXBOOTSTRAP01.template=infra/cloudformation/templates/app.yaml