securityGroup.ALBSG01.groupName=dev-alb-web01-sg
securityGroup.ALBSG01.attachedTo=ALB01
securityGroup.ALBSG01.ingress=tcp/80 from 0.0.0.0/0
securityGroup.ALBSG01.egress=all to 0.0.0.0/0
securityGroup.ALBSG01.template=infra/cloudformation/templates/web-service.yaml
securityGroup.EC2SG01.groupName=dev-ec2-web01-sg
securityGroup.EC2SG01.attachedTo=WEB01,WEB02
securityGroup.EC2SG01.ingress=tcp/80 from ALBSG01
securityGroup.EC2SG01.egress=all to 0.0.0.0/0
securityGroup.EC2SG01.directInternetIngress=denied
securityGroup.EC2SG01.template=infra/cloudformation/templates/web-service.yaml