securityGroup.ALBSG01.groupName=dev-alb-web01-sg
securityGroup.ALBSG01.attachedTo=ALB01
securityGroup.ALBSG01.ingress=tcp/80 from 0.0.0.0/0
securityGroup.ALBSG01.egress=tcp/80 to EC2SG01
securityGroup.ALBSG01.template=infra/cloudformation/templates/security.yaml
securityGroup.EC2SG01.groupName=dev-ec2-app01-sg
securityGroup.EC2SG01.attachedTo=EC2AZ1,EC2AZ2
securityGroup.EC2SG01.ingress=tcp/80 from ALBSG01
securityGroup.EC2SG01.egress80=tcp/80 to 0.0.0.0/0
securityGroup.EC2SG01.egress443=tcp/443 to 0.0.0.0/0
securityGroup.EC2SG01.ingress22=none
securityGroup.EC2SG01.template=infra/cloudformation/templates/security.yaml