subnet.PUBLICAZ1.nameTag=sbnt-web-nginx-dev-public-public-a-01
subnet.PUBLICAZ1.availabilityZone=ap-northeast-1a
subnet.PUBLICAZ1.cidrBlock=10.0.0.0/24
subnet.PUBLICAZ1.subnetType=public
subnet.PUBLICAZ1.routeType=public
subnet.PUBLICAZ1.mapPublicIpOnLaunch=true
subnet.PUBLICAZ1.template=infra/cloudformation/templates/network.yaml
subnet.PUBLICAZ2.nameTag=sbnt-web-nginx-dev-public-public-c-02
subnet.PUBLICAZ2.availabilityZone=ap-northeast-1c
subnet.PUBLICAZ2.cidrBlock=10.0.1.0/24
subnet.PUBLICAZ2.subnetType=public
subnet.PUBLICAZ2.routeType=public
subnet.PUBLICAZ2.mapPublicIpOnLaunch=true
subnet.PUBLICAZ2.template=infra/cloudformation/templates/network.yaml
subnet.PRIVATEAPPAZ1.nameTag=sbnt-web-nginx-dev-app-private-a-01
subnet.PRIVATEAPPAZ1.availabilityZone=ap-northeast-1a
subnet.PRIVATEAPPAZ1.cidrBlock=10.0.10.0/24
subnet.PRIVATEAPPAZ1.subnetType=app
subnet.PRIVATEAPPAZ1.routeType=private
subnet.PRIVATEAPPAZ1.mapPublicIpOnLaunch=false
subnet.PRIVATEAPPAZ1.template=infra/cloudformation/templates/network.yaml
subnet.PRIVATEAPPAZ2.nameTag=sbnt-web-nginx-dev-app-private-c-02
subnet.PRIVATEAPPAZ2.availabilityZone=ap-northeast-1c
subnet.PRIVATEAPPAZ2.cidrBlock=10.0.11.0/24
subnet.PRIVATEAPPAZ2.subnetType=app
subnet.PRIVATEAPPAZ2.routeType=private
subnet.PRIVATEAPPAZ2.mapPublicIpOnLaunch=false
subnet.PRIVATEAPPAZ2.template=infra/cloudformation/templates/network.yaml
subnet.PUBLICRT01.nameTag=rtb-web-nginx-dev-public-public-01
subnet.PUBLICRT01.associatedSubnets=PUBLICAZ1,PUBLICAZ2
subnet.PUBLICRT01.defaultRoute=0.0.0.0/0 -> WEBNGINXIGW
subnet.PUBLICRT01.template=infra/cloudformation/templates/network.yaml
subnet.PRIVATEAPPARTA01.nameTag=rtb-web-nginx-dev-app-private-a-01
subnet.PRIVATEAPPARTA01.associatedSubnets=PRIVATEAPPAZ1
subnet.PRIVATEAPPARTA01.defaultRoute=0.0.0.0/0 -> NATA01
subnet.PRIVATEAPPARTA01.template=infra/cloudformation/templates/network.yaml
subnet.PRIVATEAPPCRT02.nameTag=rtb-web-nginx-dev-app-private-c-02
subnet.PRIVATEAPPCRT02.associatedSubnets=PRIVATEAPPAZ2
subnet.PRIVATEAPPCRT02.defaultRoute=0.0.0.0/0 -> NATC01
subnet.PRIVATEAPPCRT02.template=infra/cloudformation/templates/network.yaml