subnet.PUBAZ1.nameTag=sbnt-web-dev-web-public-a-01
subnet.PUBAZ1.availabilityZone=ap-northeast-1a
subnet.PUBAZ1.cidrBlock=10.10.0.0/24
subnet.PUBAZ1.subnetType=web
subnet.PUBAZ1.routeType=public
subnet.PUBAZ1.mapPublicIpOnLaunch=true
subnet.PUBAZ1.template=infra/cloudformation/templates/network-base.yaml
subnet.PUBAZ2.nameTag=sbnt-web-dev-web-public-c-02
subnet.PUBAZ2.availabilityZone=ap-northeast-1c
subnet.PUBAZ2.cidrBlock=10.10.1.0/24
subnet.PUBAZ2.subnetType=web
subnet.PUBAZ2.routeType=public
subnet.PUBAZ2.mapPublicIpOnLaunch=true
subnet.PUBAZ2.template=infra/cloudformation/templates/network-base.yaml
subnet.PRVAZ1.nameTag=sbnt-web-dev-app-private-a-01
subnet.PRVAZ1.availabilityZone=ap-northeast-1a
subnet.PRVAZ1.cidrBlock=10.10.10.0/24
subnet.PRVAZ1.subnetType=app
subnet.PRVAZ1.routeType=private
subnet.PRVAZ1.mapPublicIpOnLaunch=false
subnet.PRVAZ1.template=infra/cloudformation/templates/network-base.yaml
subnet.PRVAZ2.nameTag=sbnt-web-dev-app-private-c-02
subnet.PRVAZ2.availabilityZone=ap-northeast-1c
subnet.PRVAZ2.cidrBlock=10.10.11.0/24
subnet.PRVAZ2.subnetType=app
subnet.PRVAZ2.routeType=private
subnet.PRVAZ2.mapPublicIpOnLaunch=false
subnet.PRVAZ2.template=infra/cloudformation/templates/network-base.yaml
subnet.PUBLICRT01.nameTag=rtb-web-dev-web-public-01
subnet.PUBLICRT01.associatedSubnets=PUBAZ1,PUBAZ2
subnet.PUBLICRT01.defaultRoute=0.0.0.0/0 -> Internet Gateway
subnet.PUBLICRT01.template=infra/cloudformation/templates/network-base.yaml
subnet.PRIVRTAZ1.nameTag=rtb-web-dev-app-private-a-01
subnet.PRIVRTAZ1.associatedSubnets=PRVAZ1
subnet.PRIVRTAZ1.defaultRoute=0.0.0.0/0 -> NATAZ1
subnet.PRIVRTAZ1.template=infra/cloudformation/templates/network-base.yaml
subnet.PRIVRTAZ2.nameTag=rtb-web-dev-app-private-c-02
subnet.PRIVRTAZ2.associatedSubnets=PRVAZ2
subnet.PRIVRTAZ2.defaultRoute=0.0.0.0/0 -> NATAZ2
subnet.PRIVRTAZ2.template=infra/cloudformation/templates/network-base.yaml