vpc.WEBNGINXVPC.nameTag=vpc-web-nginx-dev
vpc.WEBNGINXVPC.cidrBlock=10.0.0.0/16
vpc.WEBNGINXVPC.enableDnsSupport=true
vpc.WEBNGINXVPC.enableDnsHostnames=true
vpc.WEBNGINXVPC.ipAddressFamily=ipv4
vpc.WEBNGINXVPC.template=infra/cloudformation/templates/network.yaml
vpc.WEBNGINXIGW.nameTag=igw-web-nginx-dev
vpc.WEBNGINXIGW.attachedVpc=WEBNGINXVPC
vpc.WEBNGINXIGW.template=infra/cloudformation/templates/network.yaml
vpc.NATA01EIP.nameTag=eip-web-nginx-dev-nat-a-01
vpc.NATA01EIP.domain=vpc
vpc.NATA01EIP.purpose=nat-a
vpc.NATA01EIP.allocationStrategy=create in stack
vpc.NATA01EIP.template=infra/cloudformation/templates/network.yaml
vpc.NATC02EIP.nameTag=eip-web-nginx-dev-nat-c-02
vpc.NATC02EIP.domain=vpc
vpc.NATC02EIP.purpose=nat-c
vpc.NATC02EIP.allocationStrategy=create in stack
vpc.NATC02EIP.template=infra/cloudformation/templates/network.yaml
vpc.NATA01.nameTag=natgw-web-nginx-dev-a
vpc.NATA01.subnet=PUBLICAZ1
vpc.NATA01.elasticIp=NATA01EIP
vpc.NATA01.connectivityType=public
vpc.NATA01.template=infra/cloudformation/templates/network.yaml
vpc.NATC01.nameTag=natgw-web-nginx-dev-c
vpc.NATC01.subnet=PUBLICAZ2
vpc.NATC01.elasticIp=NATC02EIP
vpc.NATC01.connectivityType=public
vpc.NATC01.template=infra/cloudformation/templates/network.yaml