vpc.WEBCORE.nameTag=vpc-web-dev
vpc.WEBCORE.cidrBlock=10.10.0.0/16
vpc.WEBCORE.enableDnsSupport=true
vpc.WEBCORE.enableDnsHostnames=true
vpc.WEBCORE.template=infra/cloudformation/templates/network-base.yaml
vpc.WEBCORE.exportPrefix=dev-web
vpc.WEBIGW01.nameTag=igw-web-dev
vpc.WEBIGW01.attachedVpc=WEBCORE
vpc.WEBIGW01.template=infra/cloudformation/templates/network-base.yaml
vpc.NATAZ1EIP.nameTag=eip-web-dev-egress-01
vpc.NATAZ1EIP.domain=vpc
vpc.NATAZ1EIP.purpose=egress
vpc.NATAZ1EIP.allocationSource=parameterized
vpc.NATAZ1EIP.existingAllocationId=TBD
vpc.NATAZ1EIP.template=infra/cloudformation/templates/network-base.yaml
vpc.NATAZ2EIP.nameTag=eip-web-dev-egress-02
vpc.NATAZ2EIP.domain=vpc
vpc.NATAZ2EIP.purpose=egress
vpc.NATAZ2EIP.allocationSource=parameterized
vpc.NATAZ2EIP.existingAllocationId=TBD
vpc.NATAZ2EIP.template=infra/cloudformation/templates/network-base.yaml
vpc.NATAZ1.nameTag=natgw-web-dev-a
vpc.NATAZ1.subnet=PUBAZ1
vpc.NATAZ1.elasticIp=NATAZ1EIP
vpc.NATAZ1.connectivityType=public
vpc.NATAZ1.template=infra/cloudformation/templates/network-base.yaml
vpc.NATAZ2.nameTag=natgw-web-dev-c
vpc.NATAZ2.subnet=PUBAZ2
vpc.NATAZ2.elasticIp=NATAZ2EIP
vpc.NATAZ2.connectivityType=public
vpc.NATAZ2.template=infra/cloudformation/templates/network-base.yaml