[pytest]
python_files = model_design.checks.py
python_functions = check_*
pythonpath = .
addopts = --import-mode=importlib -p no:cacheprovider
tmp_path_retention_count = 0
tmp_path_retention_policy = none
