#!/usr/bin/env python3
"""Generate deterministic service models from detailed-design Markdown."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


SERVICE_ID = re.compile(r"^- Design service ID: `([^`]+)`$")
OWNED_TYPES = re.compile(r"^- Owned catalog resource types: (`[^`]+`(?:, `[^`]+`)*)$")
RESOURCE = re.compile(r"^## ([A-Za-z0-9]+\.[A-Za-z0-9]+): ([A-Za-z0-9][A-Za-z0-9_-]*)$")
ANCHOR = re.compile(r'^<a\s+id="([^"]+)"\s*></a>$')
TABLE_HEADER = "| No. | Property | Value | Source / Comment |"
TABLE_ALIGNMENT = "| ---: | --- | --- | --- |"
JSON_LINK = re.compile(r"^\[[^\]]+\]\(([^)#]+\.json)\)$")
RESOURCE_LINK = re.compile(r"^\[([^\]]+)\]\(([^)]*?)#([^)]+)\)$")


def json_sha256(path: Path) -> str:
    content = json.loads(path.read_text(encoding="utf-8"))
    canonical = json.dumps(
        content, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def identifier_outputs(root: Path) -> dict[str, set[str]]:
    outputs: dict[str, set[str]] = {}
    for path in sorted((root / "framework" / "materials" / "aws").glob("*.properties")):
        resource_type = path.stem.replace("_", ".", 1)
        outputs[resource_type] = {
            line.partition("=")[0]
            for line in path.read_text(encoding="utf-8").splitlines()
            if line.endswith("=IDENTIFIER_OUTPUT")
        }
    return outputs


def linked_resource(path: Path, value: str) -> tuple[str, str] | None:
    match = RESOURCE_LINK.fullmatch(value)
    if not match:
        return None
    _, target_text, fragment = match.groups()
    target = path if not target_text else path.parent / target_text
    if not target.is_file():
        return None
    pending_anchor = ""
    for line in target.read_text(encoding="utf-8").splitlines():
        if anchor := ANCHOR.fullmatch(line):
            pending_anchor = anchor.group(1)
        elif resource := RESOURCE.fullmatch(line):
            if pending_anchor == fragment:
                return resource.groups()
            pending_anchor = ""
    return None


def logical_link(value: str, logical_id: str) -> str:
    match = RESOURCE_LINK.fullmatch(value)
    if not match:
        return value
    return f"[{logical_id}]({match.group(2)}#{match.group(3)})"


def one_match(pattern: re.Pattern[str], lines: list[str], label: str, path: Path) -> re.Match[str]:
    matches = [match for line in lines if (match := pattern.fullmatch(line))]
    if len(matches) != 1:
        raise ValueError(f"{label} must appear exactly once: {path}")
    return matches[0]


def model_for(path: Path, root: Path | None = None) -> str:
    catalog_outputs = identifier_outputs(root or Path(__file__).resolve().parents[2])
    lines = path.read_text(encoding="utf-8").splitlines()
    service_id = one_match(SERVICE_ID, lines, "Design service ID", path).group(1)
    owned = ",".join(
        re.findall(
            r"`([^`]+)`",
            one_match(OWNED_TYPES, lines, "Owned catalog resource types", path).group(1),
        )
    )
    output = [
        "# Generated by framework/scripts/sync-model.py; do not edit.",
        f"desired.service.{service_id}.serviceId={service_id}",
        f"desired.service.{service_id}.ownedCatalogResourceTypes={owned}",
    ]
    pending_anchor = ""
    current_type = ""
    current_logical_id = ""
    current_anchor = ""
    resource_number = 0
    note_number = 0
    index = 0
    while index < len(lines):
        line = lines[index]
        if match := ANCHOR.fullmatch(line):
            pending_anchor = match.group(1)
            index += 1
            continue
        if match := RESOURCE.fullmatch(line):
            resource_number += 1
            current_type, current_logical_id = match.groups()
            current_anchor = pending_anchor
            key = f"{resource_number:03d}"
            output.extend(
                (
                    f"desired.resource.{key}.resourceType={current_type}",
                    f"desired.resource.{key}.logicalId={current_logical_id}",
                    f"desired.resource.{key}.anchor={pending_anchor}",
                )
            )
            pending_anchor = ""
            index += 1
            continue
        if line == TABLE_HEADER:
            if not current_type:
                raise ValueError(f"resource table has no resource heading: {path}")
            if index + 1 >= len(lines) or lines[index + 1] != TABLE_ALIGNMENT:
                raise ValueError(f"invalid resource table alignment: {path}")
            index += 2
            row_number = 0
            while index < len(lines) and lines[index].startswith("|"):
                cells = [cell.strip() for cell in lines[index].strip("|").split("|")]
                if len(cells) != 4:
                    raise ValueError(f"resource table row must have four cells: {path}")
                row_number += 1
                key = f"{resource_number:03d}-{row_number:03d}"
                linked = linked_resource(path, cells[2])
                is_identifier_output = cells[1] in catalog_outputs.get(current_type, set())
                is_identifier_reference = bool(
                    linked and catalog_outputs.get(linked[0])
                )
                desired_value = cells[2]
                if is_identifier_output:
                    desired_value = f"[{current_logical_id}](#{current_anchor})"
                elif is_identifier_reference and linked:
                    desired_value = logical_link(cells[2], linked[1])
                output.extend(
                    (
                        f"desired.row.{key}.property={cells[1]}",
                        f"desired.row.{key}.value={desired_value}",
                        f"desired.row.{key}.comment={cells[3]}",
                    )
                )
                if is_identifier_output or is_identifier_reference:
                    observed_value = RESOURCE_LINK.fullmatch(cells[2]).group(1) if is_identifier_reference else cells[2]
                    output.extend(
                        (
                            f"observed.row.{key}.property={cells[1]}",
                            f"observed.row.{key}.value={observed_value}",
                            f"observed.row.{key}.comment={cells[3]}",
                        )
                    )
                if match := JSON_LINK.fullmatch(cells[2]):
                    artifact = path.parent / match.group(1)
                    if not artifact.is_file():
                        raise ValueError(f"linked JSON artifact is missing: {artifact}")
                    digest = json_sha256(artifact)
                    output.append(f"desired.row.{key}.artifactSha256={digest}")
                index += 1
            continue
        if line and not (
            line.startswith("#")
            or line.startswith("- Design service ID:")
            or line.startswith("- Owned catalog resource types:")
            or line.startswith("```")
        ):
            note_number += 1
            output.append(f"desired.note.{note_number:03d}.text={line}")
        index += 1
    return "\n".join(output) + "\n"


def selected(
    path: Path,
    base: Path,
    environment: str | None,
    target_directory: str | None,
) -> bool:
    relative = path.relative_to(base)
    return (
        len(relative.parts) == 3
        and (environment is None or relative.parts[0] == environment)
        and (target_directory is None or relative.parts[1] == target_directory)
    )


def sync(
    root: Path,
    write: bool,
    environment: str | None = None,
    target_directory: str | None = None,
) -> int:
    docs = root / "docs" / "designs"
    models = root / "model"
    markdown_paths = [
        path
        for path in sorted(docs.rglob("*.md"))
        if selected(path, docs, environment, target_directory)
    ]
    expected = {
        (models / path.relative_to(docs)).with_suffix(".properties"): model_for(path, root)
        for path in markdown_paths
    }
    existing = {
        path
        for path in models.rglob("*.properties")
        if selected(path, models, environment, target_directory)
    }
    failures: list[str] = []
    for path, content in expected.items():
        if write and (not path.is_file() or path.read_text(encoding="utf-8") != content):
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            failures.append(f"generated service model is stale or missing: {path.relative_to(root)}")
    for path in sorted(existing - expected.keys()):
        failures.append(f"orphan generated service model: {path.relative_to(root)}")
    if failures:
        print("Service model sync: FAIL")
        for failure in failures:
            print(f"- {failure}")
        return 1
    print(f"Service model sync: PASS ({len(expected)} files)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repository-root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--environment")
    parser.add_argument("--aws-account-id")
    parser.add_argument("--alias")
    args = parser.parse_args()
    selectors = bool(args.aws_account_id) + bool(args.alias)
    if (args.environment and selectors != 1) or (not args.environment and selectors):
        parser.error(
            "--environment must be used with exactly one of --aws-account-id or --alias"
        )
    try:
        return sync(
            args.repository_root.resolve(),
            args.write,
            args.environment,
            args.alias or args.aws_account_id,
        )
    except ValueError as error:
        print(f"Service model sync: FAIL\n- {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
