#!/usr/bin/env python3
"""Generate deterministic LLM design mirrors from detailed-design Markdown."""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path


SERVICE_ID = re.compile(r"^- Design service ID: `([^`]+)`$")
OWNED_TYPES = re.compile(r"^- Owned catalog resource types: (`[^`]+`(?:, `[^`]+`)*)$")
RESOURCE = re.compile(r"^## ([A-Za-z0-9]+\.[A-Za-z0-9]+): ([A-Za-z0-9][A-Za-z0-9_-]*)$")
ANCHOR = re.compile(r'^<a\s+id="([^"]+)"\s*></a>$')
TABLE_HEADER = "| No. | Property | Value | Source / Comment |"
TABLE_ALIGNMENT = "| ---: | --- | --- | --- |"
JSON_LINK = re.compile(r"^\[[^\]]+\]\(([^)#]+\.json)\)$")


def normalized(value: str) -> str:
    return re.sub(r"[^a-z0-9]", "", value.lower())


def resource_label(resource_type: str) -> str:
    name = resource_type.split(".", 1)[1]
    return " ".join(re.findall(r"[A-Z]+(?=[A-Z][a-z]|[0-9]|$)|[A-Z]?[a-z]+|[0-9]+", name))


def is_generated_identifier(resource_type: str, property_name: str) -> bool:
    return normalized(property_name) == normalized(f"{resource_label(resource_type)} ID")


def one_match(pattern: re.Pattern[str], lines: list[str], label: str, path: Path) -> re.Match[str]:
    matches = [match for line in lines if (match := pattern.fullmatch(line))]
    if len(matches) != 1:
        raise ValueError(f"{label} must appear exactly once: {path}")
    return matches[0]


def mirror_for(path: Path) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    service_id = one_match(SERVICE_ID, lines, "Design service ID", path).group(1)
    owned = one_match(OWNED_TYPES, lines, "Owned catalog resource types", path).group(1).replace("`", "")
    output = [
        "# Generated by framework/scripts/sync-design-mirror.py; do not edit.",
        f"designService.{service_id}.serviceId={service_id}",
        f"designService.{service_id}.ownedCatalogResourceTypes={owned}",
    ]
    pending_anchor = ""
    current_type = ""
    resource_number = 0
    note_number = 0
    index = 0
    while index < len(lines):
        line = lines[index]
        if match := ANCHOR.fullmatch(line):
            pending_anchor = match.group(1)
            index += 1
            continue
        if match := RESOURCE.fullmatch(line):
            resource_number += 1
            current_type, logical_id = match.groups()
            key = f"{resource_number:03d}"
            output.extend(
                (
                    f"designResource.{key}.resourceType={current_type}",
                    f"designResource.{key}.logicalId={logical_id}",
                    f"designResource.{key}.anchor={pending_anchor}",
                )
            )
            pending_anchor = ""
            index += 1
            continue
        if line == TABLE_HEADER:
            if not current_type:
                raise ValueError(f"resource table has no resource heading: {path}")
            if index + 1 >= len(lines) or lines[index + 1] != TABLE_ALIGNMENT:
                raise ValueError(f"invalid resource table alignment: {path}")
            index += 2
            row_number = 0
            while index < len(lines) and lines[index].startswith("|"):
                cells = [cell.strip() for cell in lines[index].strip("|").split("|")]
                if len(cells) != 4:
                    raise ValueError(f"resource table row must have four cells: {path}")
                if not is_generated_identifier(current_type, cells[1]):
                    row_number += 1
                    key = f"{resource_number:03d}-{row_number:03d}"
                    output.extend(
                        (
                            f"designRow.{key}.property={cells[1]}",
                            f"designRow.{key}.value={cells[2]}",
                            f"designRow.{key}.comment={cells[3]}",
                        )
                    )
                    if match := JSON_LINK.fullmatch(cells[2]):
                        artifact = path.parent / match.group(1)
                        if not artifact.is_file():
                            raise ValueError(f"linked JSON artifact is missing: {artifact}")
                        digest = hashlib.sha256(artifact.read_bytes()).hexdigest()
                        output.append(f"designRow.{key}.artifactSha256={digest}")
                index += 1
            continue
        if line and not (
            line.startswith("#")
            or line.startswith("- Design service ID:")
            or line.startswith("- Owned catalog resource types:")
            or line.startswith("```")
        ):
            note_number += 1
            output.append(f"designNote.{note_number:03d}.text={line}")
        index += 1
    return "\n".join(output) + "\n"


def selected(path: Path, base: Path, environment: str | None, account: str | None) -> bool:
    relative = path.relative_to(base)
    return (
        len(relative.parts) == 3
        and (environment is None or relative.parts[0] == environment)
        and (account is None or relative.parts[1] == account)
    )


def sync(root: Path, write: bool, environment: str | None = None, account: str | None = None) -> int:
    docs = root / "docs" / "designs"
    mirrors = root / "llm" / "designs"
    markdown_paths = [path for path in sorted(docs.rglob("*.md")) if selected(path, docs, environment, account)]
    expected = {
        (mirrors / path.relative_to(docs)).with_suffix(".properties"): mirror_for(path)
        for path in markdown_paths
    }
    existing = {
        path for path in mirrors.rglob("*.properties") if selected(path, mirrors, environment, account)
    }
    failures: list[str] = []
    for path, content in expected.items():
        if write and (not path.is_file() or path.read_text(encoding="utf-8") != content):
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            failures.append(f"generated design mirror is stale or missing: {path.relative_to(root)}")
    for path in sorted(existing - expected.keys()):
        failures.append(f"orphan generated design mirror: {path.relative_to(root)}")
    if failures:
        print("Design mirror sync: FAIL")
        for failure in failures:
            print(f"- {failure}")
        return 1
    print(f"Design mirror sync: PASS ({len(expected)} files)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repository-root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--environment")
    parser.add_argument("--aws-account-id")
    args = parser.parse_args()
    if bool(args.environment) != bool(args.aws_account_id):
        parser.error("--environment and --aws-account-id must be used together")
    try:
        return sync(args.repository_root.resolve(), args.write, args.environment, args.aws_account_id)
    except ValueError as error:
        print(f"Design mirror sync: FAIL\n- {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
