#!/usr/bin/env python3
"""Generate detailed-design Markdown from authoritative service properties."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import importlib.util
import shutil
import tempfile
from pathlib import Path

from design_catalog import design_material_files
from design_layout import CODEBUILD_FORMAL_VARIABLE, HIDDEN_PROPERTIES, RESOURCE, STACK_DESIGN, GROUPED, expanded_design, resource_logical_ids, resource_display_name, stack_design
from policy_tables import without_policy_tables, rendered_design, resources_in, unique_object, invalid_constant
from model_design import properties, entries, markdown_for, resource_rows


SERVICE_ID = re.compile(r"^- Design service ID: `([^`]+)`$")
OWNED_TYPES = re.compile(r"^- Owned catalog resource types: (`[^`]+`(?:, `[^`]+`)*)$")
ANCHOR = re.compile(r'^<a\s+id="([^"]+)"\s*></a>$')
TABLE_HEADER = "| No. | Property | Value | Source / Comment |"
TABLE_ALIGNMENT = "| ---: | --- | --- | --- |"
JSON_LINK = re.compile(r"^\[[^\]]+\]\(([^)#]+\.json)\)$")
RESOURCE_LINK = re.compile(r"^\[([^\]]+)\]\(([^)]*?)#([^)]+)\)$")


def json_sha256(path: Path) -> str:
    content = json.loads(path.read_text(encoding="utf-8"))
    canonical = json.dumps(
        content, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def identifier_outputs(root: Path) -> dict[str, set[str]]:
    outputs: dict[str, set[str]] = {}
    for path in design_material_files(root):
        resource_type = path.stem.replace("_", ".", 1)
        outputs[resource_type] = {
            line.partition("=")[0]
            for line in path.read_text(encoding="utf-8").splitlines()
            if line.endswith("=IDENTIFIER_OUTPUT") and line.partition("=")[0] not in HIDDEN_PROPERTIES
        }
    return outputs


def linked_resource(path: Path, value: str) -> tuple[str, str] | None:
    match = RESOURCE_LINK.fullmatch(value)
    if not match:
        return None
    _, target_text, fragment = match.groups()
    target = path if not target_text else path.parent / target_text
    if not target.is_file():
        return None
    pending_anchor = ""
    source = target.read_text(encoding="utf-8").splitlines()
    identities = resource_logical_ids(source)
    lines, _ = expanded_design(source)
    for line in lines:
        if anchor := ANCHOR.fullmatch(line):
            pending_anchor = anchor.group(1)
        elif resource := RESOURCE.fullmatch(line):
            if pending_anchor == fragment:
                return resource.group(1), identities.get(resource.groups(), resource.group(2))
            pending_anchor = ""
    return None


def logical_link(value: str, logical_id: str) -> str:
    match = RESOURCE_LINK.fullmatch(value)
    if not match:
        return value
    return f"[{logical_id}]({match.group(2)}#{match.group(3)})"


def one_match(pattern: re.Pattern[str], lines: list[str], label: str, path: Path) -> re.Match[str]:
    matches = [match for line in lines if (match := pattern.fullmatch(line))]
    if len(matches) != 1:
        raise ValueError(f"{label} must appear exactly once: {path}")
    return matches[0]


def model_for(path: Path, root: Path | None = None) -> str:
    """Read-only projection for verification and explicit migration; never save it by default."""
    if path.name == STACK_DESIGN:
        stacks = stack_design(path)
        output = ["# Generated by framework/scripts/sync-model.py; do not edit."]
        for number, stack in enumerate(stacks, 1):
            key = f"desired.stack.{number:03d}"
            output.extend((
                f'{key}.name={stack["name"]}',
                f'{key}.template={stack["template"]}',
                f'{key}.parameters={stack["parameters"]}',
            ))
        return "\n".join(output) + "\n"
    catalog_outputs = identifier_outputs(root or Path(__file__).resolve().parents[2])
    lines = path.read_text(encoding="utf-8").splitlines()
    identities = resource_logical_ids(lines)
    lines, children = expanded_design(without_policy_tables(lines))
    service_id = one_match(SERVICE_ID, lines, "Design service ID", path).group(1)
    owned = ",".join(
        re.findall(
            r"`([^`]+)`",
            one_match(OWNED_TYPES, lines, "Owned catalog resource types", path).group(1),
        )
    )
    output = [
        "# Generated by framework/scripts/sync-model.py; do not edit.",
        f"desired.service.{service_id}.serviceId={service_id}",
        f"desired.service.{service_id}.ownedCatalogResourceTypes={owned}",
    ]
    pending_anchor = ""
    current_type = ""
    current_logical_id = ""
    current_anchor = ""
    resource_number = 0
    note_number = 0
    index = 0
    while index < len(lines):
        line = lines[index]
        if match := ANCHOR.fullmatch(line):
            pending_anchor = match.group(1)
            index += 1
            continue
        if match := RESOURCE.fullmatch(line):
            resource_number += 1
            current_type, current_logical_id = match.groups()
            current_logical_id = identities.get(match.groups(), current_logical_id)
            current_anchor = pending_anchor
            key = f"{resource_number:03d}"
            output.extend(
                (
                    f"desired.resource.{key}.resourceType={current_type}",
                    f"desired.resource.{key}.logicalId={current_logical_id}",
                    f"desired.resource.{key}.anchor={pending_anchor}",
                )
            )
            if child := children.get(current_anchor):
                output.extend((
                    f'desired.resource.{key}.parentProperty={child["parentProperty"]}',
                    f'desired.resource.{key}.parentReference=[{child["parentLogicalId"]}](#{child["parentAnchor"]})',
                ))
            pending_anchor = ""
            index += 1
            continue
        if line == TABLE_HEADER:
            if not current_type:
                raise ValueError(f"resource table has no resource heading: {path}")
            if index + 1 >= len(lines) or lines[index + 1] != TABLE_ALIGNMENT:
                raise ValueError(f"invalid resource table alignment: {path}")
            index += 2
            row_number = 0
            while index < len(lines) and lines[index].startswith("|"):
                cells = [cell.strip() for cell in lines[index].strip("|").split("|")]
                if len(cells) != 4:
                    raise ValueError(f"resource table row must have four cells: {path}")
                row_number += 1
                key = f"{resource_number:03d}-{row_number:03d}"
                linked = linked_resource(path, cells[2])
                is_identifier_output = cells[1] in catalog_outputs.get(current_type, set())
                is_identifier_reference = bool(
                    linked and catalog_outputs.get(linked[0])
                    and cells[1] != CODEBUILD_FORMAL_VARIABLE + "Value"
                )
                desired_value = cells[2]
                if is_identifier_output:
                    desired_value = f"[{current_logical_id}](#{current_anchor})"
                elif is_identifier_reference and linked:
                    desired_value = logical_link(cells[2], linked[1])
                output.extend(
                    (
                        f"desired.row.{key}.property={cells[1]}",
                        f"desired.row.{key}.value={desired_value}",
                        f"desired.row.{key}.comment={cells[3]}",
                    )
                )
                if is_identifier_output or is_identifier_reference:
                    observed_value = RESOURCE_LINK.fullmatch(cells[2]).group(1) if is_identifier_reference else cells[2]
                    output.extend(
                        (
                            f"observed.row.{key}.property={cells[1]}",
                            f"observed.row.{key}.value={observed_value}",
                            f"observed.row.{key}.comment={cells[3]}",
                        )
                    )
                if match := JSON_LINK.fullmatch(cells[2]):
                    artifact = path.parent / match.group(1)
                    if not artifact.is_file():
                        raise ValueError(f"linked JSON artifact is missing: {artifact}")
                    digest = json_sha256(artifact)
                    output.append(f"desired.row.{key}.artifactSha256={digest}")
                index += 1
            continue
        if line.startswith("|"):
            while index < len(lines) and lines[index].startswith("|"):
                index += 1
            continue
        if line and not (
            line.startswith("#")
            or line.startswith("- Design service ID:")
            or line.startswith("- Owned catalog resource types:")
            or line.startswith("```")
        ):
            note_number += 1
            output.append(f"desired.note.{note_number:03d}.text={line}")
        index += 1
    return "\n".join(output) + "\n"


def imported_model(path: Path, root: Path) -> str:
    """Preserve display inputs when explicitly migrating an existing design."""
    model = model_for(path, root)
    source = path.read_text(encoding="utf-8").splitlines()
    output = []
    if path.name == STACK_DESIGN:
        for number, stack in enumerate(stack_design(path), 1):
            output.append(f'display.stack.{number:03d}.comment={stack["comment"]}')
    else:
        output.append("display.service.title=" + next(line for line in source if line.startswith("# ")))
        values = properties(model)
        overview = {}
        for line in source:
            if line.startswith("|"):
                cells = [cell.strip() for cell in line.strip("|").split("|")]
                if len(cells) == 3 and (match := RESOURCE_LINK.fullmatch(cells[1])):
                    overview[match.group(3)] = cells[2]
        headings = {anchor: name for anchor, kind, name in (
            (resource.anchor, resource.resource_type, resource.logical_id)
            for resource in resources_in(without_policy_tables(source))
        )}
        for identity, resource in entries(values, "desired.resource."):
            rows = resource_rows(values, identity, resource["resourceType"], root)
            if resource_display_name(resource["resourceType"], rows) is None and GROUPED.get(resource["resourceType"], {}).get("display") != "rule-table":
                label = headings.get(resource["anchor"])
                if label is None:
                    raise ValueError(f"confirmed display label required for grouped resource: {resource['logicalId']}")
                output.append(f"display.resource.{identity}.label={label}")
            if resource["resourceType"] not in GROUPED:
                if resource["anchor"] not in overview:
                    raise ValueError(f"resource overview comment is missing: {resource['anchor']}")
                output.append(f"display.resource.{identity}.comment={overview[resource['anchor']]}")
        for identity, row in entries(values, "desired.row."):
            if match := JSON_LINK.fullmatch(row["value"]):
                document = json.loads((path.parent / match.group(1)).read_text(encoding="utf-8"), object_pairs_hook=unique_object, parse_constant=invalid_constant)
                output.append(f"desired.row.{identity}.document=" + json.dumps(document, ensure_ascii=False, separators=(",", ":")))
    return model.replace("# Generated by framework/scripts/sync-model.py; do not edit.", "# Authoritative design values; Markdown is generated by framework/scripts/sync-model.py.") + "\n".join(output) + "\n"


def selected(
    path: Path,
    base: Path,
    environment: str | None,
    target_directory: str | None,
) -> bool:
    relative = path.relative_to(base)
    return (
        len(relative.parts) == 3
        and (environment is None or relative.parts[0] == environment)
        and (target_directory is None or relative.parts[1] == target_directory)
    )


def sync(
    root: Path,
    write: bool,
    environment: str | None = None,
    target_directory: str | None = None,
    import_markdown: bool = False,
) -> int:
    root = root.resolve()
    docs = root / "docs" / "designs"
    models = root / "model"
    markdown_paths = [
        path
        for path in sorted(docs.rglob("*.md"))
        if selected(path, docs, environment, target_directory)
    ]
    model_paths = sorted(
        path
        for path in models.rglob("*.properties")
        if selected(path, models, environment, target_directory)
    )
    if import_markdown:
        if not write:
            raise ValueError("--import-markdown requires --write and an explicitly authorized migration task")
        contract = root / "tasks/active.md"
        if not contract.is_file() or "- Task type: `migration`" not in contract.read_text(encoding="utf-8"):
            raise ValueError("Markdown import is allowed only in an explicit migration task")
        expected_models = {(models / path.relative_to(docs)).with_suffix(".properties"): imported_model(path, root) for path in markdown_paths}
        if any(path.is_file() for path in expected_models):
            raise ValueError("Markdown import must not overwrite an existing authoritative model")
        save_files(expected_models)
        print(f"Service model import: PASS ({len(expected_models)} files); verify and generate Markdown next")
        return 0
    destinations = {(docs / path.relative_to(models)).with_suffix(".md"): properties(path.read_text(encoding="utf-8")) for path in model_paths}
    if missing := set(markdown_paths) - destinations.keys():
        raise ValueError("authoritative model missing; explicit migration required: " + ", ".join(str(path.relative_to(root)) for path in sorted(missing)))
    if not destinations:
        print("Design Markdown sync: PASS (0 files)")
        return 0
    with tempfile.TemporaryDirectory() as directory:
        stage = Path(directory).resolve()
        shutil.copytree(root / "framework", stage / "framework")
        targets = {path.parent.relative_to(docs) for path in destinations}
        for target in targets:
            for base in (docs, models):
                if (base / target).is_dir():
                    shutil.copytree(base / target, stage / base.relative_to(root) / target)
        if (root / "project.json").is_file():
            shutil.copyfile(root / "project.json", stage / "project.json")
        artifacts = {}
        for path, values in destinations.items():
            staged = stage / path.relative_to(root)
            for identity, row in entries(values, "desired.row."):
                match = JSON_LINK.fullmatch(row.get("value", ""))
                if not match:
                    if "document" in row:
                        raise ValueError(f"JSON document requires an artifact link: {identity}")
                    continue
                if "document" not in row:
                    raise ValueError(f"authoritative JSON document missing: {path.name}: {identity}")
                document = json.loads(row["document"], object_pairs_hook=unique_object, parse_constant=invalid_constant)
                if not isinstance(document, dict):
                    raise ValueError(f"JSON document must be an object: {identity}")
                artifact = (staged.parent / match.group(1)).resolve()
                if artifact.parent != staged.with_suffix("").resolve():
                    raise ValueError(f"JSON artifact must belong to owning service: {identity}")
                content = json.dumps(document, ensure_ascii=False, indent=2) + "\n"
                if artifact in artifacts and artifacts[artifact] != content:
                    raise ValueError(f"conflicting authoritative JSON documents: {artifact.name}")
                artifacts[artifact] = content
        for artifact, content in artifacts.items():
            artifact.parent.mkdir(parents=True, exist_ok=True)
            artifact.write_text(content, encoding="utf-8")
        # Render all base views first, so cross-service links see the same new state.
        staged_paths = []
        for path, values in destinations.items():
            staged = stage / path.relative_to(root)
            staged.parent.mkdir(parents=True, exist_ok=True)
            staged.write_text(markdown_for(staged, values, stage), encoding="utf-8")
            staged_paths.append(staged)
        for path in staged_paths:
            if path.name != STACK_DESIGN:
                path.write_text(rendered_design(path), encoding="utf-8")
        validate_views(stage, root, staged_paths, destinations)
        expected = {root / path.relative_to(stage): path.read_text(encoding="utf-8") for path in [*artifacts, *staged_paths]}
    if write:
        save_files(expected)
    failures = [f"generated Markdown is stale or missing: {path.relative_to(root)}" for path, content in expected.items()
                if not path.is_file() or path.read_text(encoding="utf-8") != content]
    if failures:
        raise ValueError("\n- ".join(failures))
    print(f"Design Markdown sync: PASS ({len(expected)} files)")
    return 0


def validate_views(stage: Path, root: Path, paths: list[Path], sources: dict[Path, dict[str, str]]) -> None:
    """Use the existing parsers/schema validator before touching any saved view."""
    for path in paths:
        actual = properties(model_for(path, root))
        source = sources[root / path.relative_to(stage)]
        formal = {key: value for key, value in source.items() if not key.startswith("display.") and not key.endswith((".document", ".artifactSha256"))}
        actual = {key: value for key, value in actual.items() if not key.endswith(".artifactSha256")}
        if actual != formal:
            differences = sorted(key for key in actual.keys() | formal.keys() if actual.get(key) != formal.get(key))
            raise ValueError(f"model/display projection mismatch: {path.name}: {', '.join(differences)}")
    if not paths:
        return
    spec = importlib.util.spec_from_file_location("blueprint_view_validator", Path(__file__).with_name("validate-blueprint.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    validator = module.Validator(stage)
    validator.schema_catalog = module.DesignSchemaCatalog(root)
    validator.check_project_topology()
    for path in paths:
        validator.check_target_file(path, stage / "docs/designs")
        validator.check_target_file((stage / "model" / path.relative_to(stage / "docs/designs")).with_suffix(".properties"), stage / "model")
    validator.check_stack_designs()
    services = [path for path in paths if path.name != STACK_DESIGN]
    metadata, types, owners, outputs = validator.check_design_service_ownership(services)
    validator.check_resource_names(metadata)
    validator.check_design_tables(metadata, types, owners, outputs)
    validator.check_design_overviews()
    validator.check_design_links(outputs)
    validator.check_design_artifacts()
    validator.check_observed_values()
    if validator.errors:
        raise ValueError("\n- ".join(validator.errors))


def save_files(expected: dict[Path, str]) -> None:
    """Rollback the batch if a filesystem write fails after successful generation."""
    originals = {path: path.read_bytes() if path.is_file() else None for path in expected}
    written = []
    try:
        for path, content in expected.items():
            if originals[path] == content.encode("utf-8"):
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            written.append(path)
            path.write_text(content, encoding="utf-8")
    except OSError as error:
        rollback_errors = []
        for path in reversed(written):
            try:
                if originals[path] is None:
                    path.unlink(missing_ok=True)
                elif path.read_bytes() != originals[path]:
                    path.write_bytes(originals[path])
            except OSError as rollback_error:
                rollback_errors.append(f"{path}: {rollback_error}")
        if rollback_errors:
            raise OSError(f"{error}; generated-file rollback failed: {'; '.join(rollback_errors)}") from error
        raise


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repository-root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--import-markdown", action="store_true", help="Explicit one-time migration; requires a migration task and absent models")
    parser.add_argument("--environment")
    parser.add_argument("--aws-account-id")
    parser.add_argument("--alias")
    args = parser.parse_args()
    selectors = bool(args.aws_account_id) + bool(args.alias)
    if (args.environment and selectors != 1) or (not args.environment and selectors):
        parser.error(
            "--environment must be used with exactly one of --aws-account-id or --alias"
        )
    try:
        return sync(
            args.repository_root.resolve(),
            args.write,
            args.environment,
            args.alias or args.aws_account_id,
            args.import_markdown,
        )
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f"Design Markdown sync: FAIL\n- {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
