ApiGatewayV2.IntegrationResponse.ApiId=
ApiGatewayV2.IntegrationResponse.ContentHandlingStrategy=
ApiGatewayV2.IntegrationResponse.IntegrationId=
ApiGatewayV2.IntegrationResponse.IntegrationResponseKey=
ApiGatewayV2.IntegrationResponse.ResponseParameters=
ApiGatewayV2.IntegrationResponse.ResponseTemplates=
ApiGatewayV2.IntegrationResponse.TemplateSelectionExpression=
