ApiGateway.Deployment.DeploymentCanarySettings.PercentTraffic=
ApiGateway.Deployment.DeploymentCanarySettings.StageVariableOverrides=
ApiGateway.Deployment.DeploymentCanarySettings.UseStageCache=
ApiGateway.Deployment.Description=
ApiGateway.Deployment.RestApiId=
ApiGateway.Deployment.StageDescription.AccessLogSetting.DestinationArn=
ApiGateway.Deployment.StageDescription.AccessLogSetting.Format=
ApiGateway.Deployment.StageDescription.CacheClusterEnabled=
ApiGateway.Deployment.StageDescription.CacheClusterSize=
ApiGateway.Deployment.StageDescription.CacheDataEncrypted=
ApiGateway.Deployment.StageDescription.CacheTtlInSeconds=
ApiGateway.Deployment.StageDescription.CachingEnabled=
ApiGateway.Deployment.StageDescription.CanarySetting.PercentTraffic=
ApiGateway.Deployment.StageDescription.CanarySetting.StageVariableOverrides=
ApiGateway.Deployment.StageDescription.CanarySetting.UseStageCache=
ApiGateway.Deployment.StageDescription.ClientCertificateId=
ApiGateway.Deployment.StageDescription.DataTraceEnabled=
ApiGateway.Deployment.StageDescription.Description=
ApiGateway.Deployment.StageDescription.DocumentationVersion=
ApiGateway.Deployment.StageDescription.LoggingLevel=
ApiGateway.Deployment.StageDescription.MethodSettings[].CacheDataEncrypted=
ApiGateway.Deployment.StageDescription.MethodSettings[].CacheTtlInSeconds=
ApiGateway.Deployment.StageDescription.MethodSettings[].CachingEnabled=
ApiGateway.Deployment.StageDescription.MethodSettings[].DataTraceEnabled=
ApiGateway.Deployment.StageDescription.MethodSettings[].HttpMethod=
ApiGateway.Deployment.StageDescription.MethodSettings[].LoggingLevel=
ApiGateway.Deployment.StageDescription.MethodSettings[].MetricsEnabled=
ApiGateway.Deployment.StageDescription.MethodSettings[].ResourcePath=
ApiGateway.Deployment.StageDescription.MethodSettings[].ThrottlingBurstLimit=
ApiGateway.Deployment.StageDescription.MethodSettings[].ThrottlingRateLimit=
ApiGateway.Deployment.StageDescription.MetricsEnabled=
ApiGateway.Deployment.StageDescription.Tags[].Key=
ApiGateway.Deployment.StageDescription.Tags[].Value=
ApiGateway.Deployment.StageDescription.ThrottlingBurstLimit=
ApiGateway.Deployment.StageDescription.ThrottlingRateLimit=
ApiGateway.Deployment.StageDescription.TracingEnabled=
ApiGateway.Deployment.StageDescription.Variables=
ApiGateway.Deployment.StageName=
