CloudTrail.Trail.AdvancedEventSelectors[].FieldSelectors[].EndsWith=
CloudTrail.Trail.AdvancedEventSelectors[].FieldSelectors[].Equals=
CloudTrail.Trail.AdvancedEventSelectors[].FieldSelectors[].Field=
CloudTrail.Trail.AdvancedEventSelectors[].FieldSelectors[].NotEndsWith=
CloudTrail.Trail.AdvancedEventSelectors[].FieldSelectors[].NotEquals=
CloudTrail.Trail.AdvancedEventSelectors[].FieldSelectors[].NotStartsWith=
CloudTrail.Trail.AdvancedEventSelectors[].FieldSelectors[].StartsWith=
CloudTrail.Trail.AdvancedEventSelectors[].Name=
CloudTrail.Trail.CloudWatchLogsLogGroupArn=
CloudTrail.Trail.CloudWatchLogsRoleArn=
CloudTrail.Trail.EnableLogFileValidation=
CloudTrail.Trail.EventSelectors[].DataResources[].Type=
CloudTrail.Trail.EventSelectors[].DataResources[].Values=
CloudTrail.Trail.EventSelectors[].ExcludeManagementEventSources=
CloudTrail.Trail.EventSelectors[].IncludeManagementEvents=
CloudTrail.Trail.EventSelectors[].ReadWriteType=
CloudTrail.Trail.IncludeGlobalServiceEvents=
CloudTrail.Trail.InsightSelectors[].EventCategories=
CloudTrail.Trail.InsightSelectors[].InsightType=
CloudTrail.Trail.IsLogging=
CloudTrail.Trail.IsMultiRegionTrail=
CloudTrail.Trail.IsOrganizationTrail=
CloudTrail.Trail.KMSKeyId=
CloudTrail.Trail.S3BucketName=
CloudTrail.Trail.S3KeyPrefix=
CloudTrail.Trail.SnsTopicName=
CloudTrail.Trail.Tags[].Key=
CloudTrail.Trail.Tags[].Value=
CloudTrail.Trail.TrailName=
