CloudFront.Function.AutoPublish=
CloudFront.Function.FunctionCode=
CloudFront.Function.FunctionConfig.Comment=
CloudFront.Function.FunctionConfig.KeyValueStoreAssociations[].KeyValueStoreARN=
CloudFront.Function.FunctionConfig.Runtime=
CloudFront.Function.Name=
CloudFront.Function.Tags[].Key=
CloudFront.Function.Tags[].Value=
