CodeBuild.Project.Artifacts.ArtifactIdentifier=
CodeBuild.Project.Artifacts.EncryptionDisabled=
CodeBuild.Project.Artifacts.Location=
CodeBuild.Project.Artifacts.Name=
CodeBuild.Project.Artifacts.NamespaceType=
CodeBuild.Project.Artifacts.OverrideArtifactName=
CodeBuild.Project.Artifacts.Packaging=
CodeBuild.Project.Artifacts.Path=
CodeBuild.Project.Artifacts.Type=
CodeBuild.Project.AutoRetryLimit=
CodeBuild.Project.Cache.Location=
CodeBuild.Project.Cache.Modes=
CodeBuild.Project.Cache.Type=
CodeBuild.Project.ConcurrentBuildLimit=
CodeBuild.Project.Description=
CodeBuild.Project.EncryptionKey=
CodeBuild.Project.Environment.Certificate=
CodeBuild.Project.Environment.ComputeType=
CodeBuild.Project.Environment.EnvironmentVariables[].Name=
CodeBuild.Project.Environment.EnvironmentVariables[].Type=
CodeBuild.Project.Environment.EnvironmentVariables[].Value=
CodeBuild.Project.Environment.Image=
CodeBuild.Project.Environment.ImagePullCredentialsType=
CodeBuild.Project.Environment.PrivilegedMode=
CodeBuild.Project.Environment.RegistryCredential.Credential=
CodeBuild.Project.Environment.RegistryCredential.CredentialProvider=
CodeBuild.Project.Environment.Type=
CodeBuild.Project.LogsConfig.CloudWatchLogs.GroupName=
CodeBuild.Project.LogsConfig.CloudWatchLogs.Status=
CodeBuild.Project.LogsConfig.CloudWatchLogs.StreamName=
CodeBuild.Project.LogsConfig.S3Logs.EncryptionDisabled=
CodeBuild.Project.LogsConfig.S3Logs.Location=
CodeBuild.Project.LogsConfig.S3Logs.Status=
CodeBuild.Project.Name=
CodeBuild.Project.QueuedTimeoutInMinutes=
CodeBuild.Project.ServiceRole=
CodeBuild.Project.Source.Auth.Resource=
CodeBuild.Project.Source.Auth.Type=
CodeBuild.Project.Source.BuildSpec=
CodeBuild.Project.Source.GitCloneDepth=
CodeBuild.Project.Source.GitSubmodulesConfig.FetchSubmodules=
CodeBuild.Project.Source.InsecureSsl=
CodeBuild.Project.Source.Location=
CodeBuild.Project.Source.ReportBuildStatus=
CodeBuild.Project.Source.Type=
CodeBuild.Project.SourceVersion=
CodeBuild.Project.Tags[].Key=
CodeBuild.Project.Tags[].Value=
CodeBuild.Project.TimeoutInMinutes=
CodeBuild.Project.Triggers.BuildType=
CodeBuild.Project.Triggers.Webhook=
CodeBuild.Project.Visibility=
CodeBuild.Project.VpcConfig.SecurityGroupIds=
CodeBuild.Project.VpcConfig.Subnets=
CodeBuild.Project.VpcConfig.VpcId=
