CodePipeline.Pipeline.ArtifactStore.EncryptionKey.Id=
CodePipeline.Pipeline.ArtifactStore.EncryptionKey.Type=
CodePipeline.Pipeline.ArtifactStore.Location=
CodePipeline.Pipeline.ArtifactStore.Type=
CodePipeline.Pipeline.ArtifactStores[].ArtifactStore.EncryptionKey.Id=
CodePipeline.Pipeline.ArtifactStores[].ArtifactStore.EncryptionKey.Type=
CodePipeline.Pipeline.ArtifactStores[].ArtifactStore.Location=
CodePipeline.Pipeline.ArtifactStores[].ArtifactStore.Type=
CodePipeline.Pipeline.ArtifactStores[].Region=
CodePipeline.Pipeline.ExecutionMode=
CodePipeline.Pipeline.Name=
CodePipeline.Pipeline.PipelineType=
CodePipeline.Pipeline.RestartExecutionOnUpdate=
CodePipeline.Pipeline.RoleArn=
CodePipeline.Pipeline.Stages[].Actions[].ActionTypeId.Category=
CodePipeline.Pipeline.Stages[].Actions[].ActionTypeId.Owner=
CodePipeline.Pipeline.Stages[].Actions[].ActionTypeId.Provider=
CodePipeline.Pipeline.Stages[].Actions[].ActionTypeId.Version=
CodePipeline.Pipeline.Stages[].Actions[].Commands=
CodePipeline.Pipeline.Stages[].Actions[].Configuration=
CodePipeline.Pipeline.Stages[].Actions[].InputArtifacts[].Name=
CodePipeline.Pipeline.Stages[].Actions[].Name=
CodePipeline.Pipeline.Stages[].Actions[].Namespace=
CodePipeline.Pipeline.Stages[].Actions[].OutputArtifacts[].Files=
CodePipeline.Pipeline.Stages[].Actions[].OutputArtifacts[].Name=
CodePipeline.Pipeline.Stages[].Actions[].OutputVariables=
CodePipeline.Pipeline.Stages[].Actions[].Region=
CodePipeline.Pipeline.Stages[].Actions[].RoleArn=
CodePipeline.Pipeline.Stages[].Actions[].RunOrder=
CodePipeline.Pipeline.Stages[].Actions[].TimeoutInMinutes=
CodePipeline.Pipeline.Stages[].Name=
CodePipeline.Pipeline.Tags[].Key=
CodePipeline.Pipeline.Tags[].Value=
CodePipeline.Pipeline.Triggers[].GitConfiguration.PullRequest[].Branches.Excludes=
CodePipeline.Pipeline.Triggers[].GitConfiguration.PullRequest[].Branches.Includes=
CodePipeline.Pipeline.Triggers[].GitConfiguration.PullRequest[].Events=
CodePipeline.Pipeline.Triggers[].GitConfiguration.PullRequest[].FilePaths.Excludes=
CodePipeline.Pipeline.Triggers[].GitConfiguration.PullRequest[].FilePaths.Includes=
CodePipeline.Pipeline.Triggers[].GitConfiguration.Push[].Branches.Excludes=
CodePipeline.Pipeline.Triggers[].GitConfiguration.Push[].Branches.Includes=
CodePipeline.Pipeline.Triggers[].GitConfiguration.Push[].FilePaths.Excludes=
CodePipeline.Pipeline.Triggers[].GitConfiguration.Push[].FilePaths.Includes=
CodePipeline.Pipeline.Triggers[].GitConfiguration.Push[].Tags.Excludes=
CodePipeline.Pipeline.Triggers[].GitConfiguration.Push[].Tags.Includes=
CodePipeline.Pipeline.Triggers[].GitConfiguration.SourceActionName=
CodePipeline.Pipeline.Triggers[].ProviderType=
CodePipeline.Pipeline.Variables[].DefaultValue=
CodePipeline.Pipeline.Variables[].Description=
CodePipeline.Pipeline.Variables[].Name=
