CodeCommit.Repository.Code.BranchName=
CodeCommit.Repository.Code.S3.Bucket=
CodeCommit.Repository.Code.S3.Key=
CodeCommit.Repository.Code.S3.ObjectVersion=
CodeCommit.Repository.KmsKeyId=
CodeCommit.Repository.RepositoryDescription=
CodeCommit.Repository.RepositoryName=
CodeCommit.Repository.Tags[].Key=
CodeCommit.Repository.Tags[].Value=
CodeCommit.Repository.Triggers[].Branches=
CodeCommit.Repository.Triggers[].CustomData=
CodeCommit.Repository.Triggers[].DestinationArn=
CodeCommit.Repository.Triggers[].Events=
CodeCommit.Repository.Triggers[].Name=
