Config.ConfigurationRecorder.Name=
Config.ConfigurationRecorder.RecordingGroup.AllSupported=
Config.ConfigurationRecorder.RecordingGroup.ExclusionByResourceTypes.ResourceTypes=
Config.ConfigurationRecorder.RecordingGroup.IncludeGlobalResourceTypes=
Config.ConfigurationRecorder.RecordingGroup.RecordingStrategy.UseOnly=
Config.ConfigurationRecorder.RecordingGroup.ResourceTypes=
Config.ConfigurationRecorder.RecordingMode.RecordingFrequency=
Config.ConfigurationRecorder.RecordingMode.RecordingModeOverrides[].Description=
Config.ConfigurationRecorder.RecordingMode.RecordingModeOverrides[].RecordingFrequency=
Config.ConfigurationRecorder.RecordingMode.RecordingModeOverrides[].ResourceTypes=
Config.ConfigurationRecorder.RoleARN=
