EC2.TransitGatewayVpcAttachment.Options.ApplianceModeSupport=
EC2.TransitGatewayVpcAttachment.Options.DnsSupport=
EC2.TransitGatewayVpcAttachment.Options.SecurityGroupReferencingSupport=
EC2.TransitGatewayVpcAttachment.SubnetIds=
EC2.TransitGatewayVpcAttachment.Tags[].Key=
EC2.TransitGatewayVpcAttachment.Tags[].Value=
EC2.TransitGatewayVpcAttachment.TransitGatewayId=
EC2.TransitGatewayVpcAttachment.VpcId=
