EC2.TransitGateway.AmazonSideAsn=
EC2.TransitGateway.AutoAcceptSharedAttachments=
EC2.TransitGateway.DefaultRouteTableAssociation=
EC2.TransitGateway.DefaultRouteTablePropagation=
EC2.TransitGateway.Description=
EC2.TransitGateway.DnsSupport=
EC2.TransitGateway.EncryptionSupport=
EC2.TransitGateway.SecurityGroupReferencingSupport=
EC2.TransitGateway.Tags[].Key=
EC2.TransitGateway.Tags[].Value=
EC2.TransitGateway.TransitGatewayCidrBlocks=
EC2.TransitGateway.VpnEcmpSupport=
