EC2.SecurityGroup.GroupDescription=
EC2.SecurityGroup.GroupName=
EC2.SecurityGroup.SecurityGroupEgress[].CidrIp=
EC2.SecurityGroup.SecurityGroupEgress[].CidrIpv6=
EC2.SecurityGroup.SecurityGroupEgress[].Description=
EC2.SecurityGroup.SecurityGroupEgress[].DestinationPrefixListId=
EC2.SecurityGroup.SecurityGroupEgress[].DestinationSecurityGroupId=
EC2.SecurityGroup.SecurityGroupEgress[].FromPort=
EC2.SecurityGroup.SecurityGroupEgress[].IpProtocol=
EC2.SecurityGroup.SecurityGroupEgress[].ToPort=
EC2.SecurityGroup.SecurityGroupIngress[].CidrIp=
EC2.SecurityGroup.SecurityGroupIngress[].CidrIpv6=
EC2.SecurityGroup.SecurityGroupIngress[].Description=
EC2.SecurityGroup.SecurityGroupIngress[].FromPort=
EC2.SecurityGroup.SecurityGroupIngress[].IpProtocol=
EC2.SecurityGroup.SecurityGroupIngress[].SourcePrefixListId=
EC2.SecurityGroup.SecurityGroupIngress[].SourceSecurityGroupId=
EC2.SecurityGroup.SecurityGroupIngress[].SourceSecurityGroupOwnerId=
EC2.SecurityGroup.SecurityGroupIngress[].ToPort=
EC2.SecurityGroup.Tags[].Key=
EC2.SecurityGroup.Tags[].Value=
EC2.SecurityGroup.VpcId=
