ElasticLoadBalancingV2.LoadBalancer.EnableCapacityReservationProvisionStabilize=
ElasticLoadBalancingV2.LoadBalancer.EnablePrefixForIpv6SourceNat=
ElasticLoadBalancingV2.LoadBalancer.EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic=
ElasticLoadBalancingV2.LoadBalancer.IpAddressType=
ElasticLoadBalancingV2.LoadBalancer.Ipv4IpamPoolId=
ElasticLoadBalancingV2.LoadBalancer.LoadBalancerAttributes[].Key=
ElasticLoadBalancingV2.LoadBalancer.LoadBalancerAttributes[].Value=
ElasticLoadBalancingV2.LoadBalancer.MinimumLoadBalancerCapacity.CapacityUnits=
ElasticLoadBalancingV2.LoadBalancer.Name=
ElasticLoadBalancingV2.LoadBalancer.Scheme=
ElasticLoadBalancingV2.LoadBalancer.SecurityGroups[]=
ElasticLoadBalancingV2.LoadBalancer.SubnetMappings[].AllocationId=
ElasticLoadBalancingV2.LoadBalancer.SubnetMappings[].IPv6Address=
ElasticLoadBalancingV2.LoadBalancer.SubnetMappings[].PrivateIPv4Address=
ElasticLoadBalancingV2.LoadBalancer.SubnetMappings[].SourceNatIpv6Prefix=
ElasticLoadBalancingV2.LoadBalancer.SubnetMappings[].SubnetId=
ElasticLoadBalancingV2.LoadBalancer.Subnets[]=
ElasticLoadBalancingV2.LoadBalancer.Tags[].Key=
ElasticLoadBalancingV2.LoadBalancer.Tags[].Value=
ElasticLoadBalancingV2.LoadBalancer.Type=
