Events.Rule.Description=
Events.Rule.EventBusName=
Events.Rule.EventPattern=
Events.Rule.Name=
Events.Rule.RoleArn=
Events.Rule.ScheduleExpression=
Events.Rule.State=
Events.Rule.Tags[].Key=
Events.Rule.Tags[].Value=
Events.Rule.Targets[].Arn=
Events.Rule.Targets[].DeadLetterConfig.Arn=
Events.Rule.Targets[].HttpParameters.HeaderParameters=
Events.Rule.Targets[].HttpParameters.PathParameterValues=
Events.Rule.Targets[].HttpParameters.QueryStringParameters=
Events.Rule.Targets[].Id=
Events.Rule.Targets[].Input=
Events.Rule.Targets[].InputPath=
Events.Rule.Targets[].InputTransformer.InputPathsMap=
Events.Rule.Targets[].InputTransformer.InputTemplate=
Events.Rule.Targets[].RetryPolicy.MaximumEventAgeInSeconds=
Events.Rule.Targets[].RetryPolicy.MaximumRetryAttempts=
Events.Rule.Targets[].RoleArn=
