Events.EventBus.DeadLetterConfig.Arn=
Events.EventBus.Description=
Events.EventBus.EventSourceName=
Events.EventBus.KmsKeyIdentifier=
Events.EventBus.LogConfig.IncludeDetail=
Events.EventBus.LogConfig.Level=
Events.EventBus.Name=
Events.EventBus.Policy=
Events.EventBus.Tags[].Key=
Events.EventBus.Tags[].Value=
