Glue.Crawler.Classifiers=
Glue.Crawler.Configuration=
Glue.Crawler.CrawlerSecurityConfiguration=
Glue.Crawler.DatabaseName=
Glue.Crawler.Description=
Glue.Crawler.LakeFormationConfiguration.AccountId=
Glue.Crawler.LakeFormationConfiguration.UseLakeFormationCredentials=
Glue.Crawler.Name=
Glue.Crawler.RecrawlPolicy.RecrawlBehavior=
Glue.Crawler.Role=
Glue.Crawler.Schedule.ScheduleExpression=
Glue.Crawler.SchemaChangePolicy.DeleteBehavior=
Glue.Crawler.SchemaChangePolicy.UpdateBehavior=
Glue.Crawler.TablePrefix=
Glue.Crawler.Tags=
Glue.Crawler.Targets.JdbcTargets[].ConnectionName=
Glue.Crawler.Targets.JdbcTargets[].Exclusions=
Glue.Crawler.Targets.JdbcTargets[].Path=
Glue.Crawler.Targets.S3Targets[].ConnectionName=
Glue.Crawler.Targets.S3Targets[].DlqEventQueueArn=
Glue.Crawler.Targets.S3Targets[].EventQueueArn=
Glue.Crawler.Targets.S3Targets[].Exclusions=
Glue.Crawler.Targets.S3Targets[].Path=
Glue.Crawler.Targets.S3Targets[].SampleSize=
