Glue.SecurityConfiguration.EncryptionConfiguration.CloudWatchEncryption.CloudWatchEncryptionMode=
Glue.SecurityConfiguration.EncryptionConfiguration.CloudWatchEncryption.KmsKeyArn=
Glue.SecurityConfiguration.EncryptionConfiguration.JobBookmarksEncryption.JobBookmarksEncryptionMode=
Glue.SecurityConfiguration.EncryptionConfiguration.JobBookmarksEncryption.KmsKeyArn=
Glue.SecurityConfiguration.EncryptionConfiguration.S3Encryptions[].KmsKeyArn=
Glue.SecurityConfiguration.EncryptionConfiguration.S3Encryptions[].S3EncryptionMode=
Glue.SecurityConfiguration.Name=
