GuardDuty.Detector.DataSources.Kubernetes.AuditLogs.Enable=
GuardDuty.Detector.DataSources.MalwareProtection.ScanEc2InstanceWithFindings.EbsVolumes=
GuardDuty.Detector.DataSources.S3Logs.Enable=
GuardDuty.Detector.Enable=
GuardDuty.Detector.Features[].AdditionalConfiguration[].Name=
GuardDuty.Detector.Features[].AdditionalConfiguration[].Status=
GuardDuty.Detector.Features[].Name=
GuardDuty.Detector.Features[].Status=
GuardDuty.Detector.FindingPublishingFrequency=
GuardDuty.Detector.Tags[].Key=
GuardDuty.Detector.Tags[].Value=
