IAM.Role.AssumeRolePolicyDocument=
IAM.Role.Description=
IAM.Role.ManagedPolicyArns=
IAM.Role.MaxSessionDuration=
IAM.Role.Path=
IAM.Role.PermissionsBoundary=
IAM.Role.Policies[].PolicyDocument=
IAM.Role.Policies[].PolicyName=
IAM.Role.RoleName=
IAM.Role.Tags[].Key=
IAM.Role.Tags[].Value=
