KinesisFirehose.DeliveryStream.DeliveryStreamEncryptionConfigurationInput.KeyARN=
KinesisFirehose.DeliveryStream.DeliveryStreamEncryptionConfigurationInput.KeyType=
KinesisFirehose.DeliveryStream.DeliveryStreamName=
KinesisFirehose.DeliveryStream.DeliveryStreamType=
KinesisFirehose.DeliveryStream.S3DestinationConfiguration.BucketARN=
KinesisFirehose.DeliveryStream.S3DestinationConfiguration.BufferingHints.IntervalInSeconds=
KinesisFirehose.DeliveryStream.S3DestinationConfiguration.BufferingHints.SizeInMBs=
KinesisFirehose.DeliveryStream.S3DestinationConfiguration.CloudWatchLoggingOptions.Enabled=
KinesisFirehose.DeliveryStream.S3DestinationConfiguration.CloudWatchLoggingOptions.LogGroupName=
KinesisFirehose.DeliveryStream.S3DestinationConfiguration.CloudWatchLoggingOptions.LogStreamName=
KinesisFirehose.DeliveryStream.S3DestinationConfiguration.CompressionFormat=
KinesisFirehose.DeliveryStream.S3DestinationConfiguration.EncryptionConfiguration.KMSEncryptionConfig.AWSKMSKeyARN=
KinesisFirehose.DeliveryStream.S3DestinationConfiguration.EncryptionConfiguration.NoEncryptionConfig=
KinesisFirehose.DeliveryStream.S3DestinationConfiguration.ErrorOutputPrefix=
KinesisFirehose.DeliveryStream.S3DestinationConfiguration.Prefix=
KinesisFirehose.DeliveryStream.S3DestinationConfiguration.RoleARN=
KinesisFirehose.DeliveryStream.Tags[].Key=
KinesisFirehose.DeliveryStream.Tags[].Value=
