Lambda.Function.Architectures=
Lambda.Function.Code.ImageUri=
Lambda.Function.Code.S3Bucket=
Lambda.Function.Code.S3Key=
Lambda.Function.Code.S3ObjectVersion=
Lambda.Function.Code.SourceKMSKeyArn=
Lambda.Function.CodeSigningConfigArn=
Lambda.Function.DeadLetterConfig.TargetArn=
Lambda.Function.Description=
Lambda.Function.Environment.Variables=
Lambda.Function.EphemeralStorage.Size=
Lambda.Function.FileSystemConfigs[].Arn=
Lambda.Function.FileSystemConfigs[].LocalMountPath=
Lambda.Function.FunctionName=
Lambda.Function.Handler=
Lambda.Function.ImageConfig.Command=
Lambda.Function.ImageConfig.EntryPoint=
Lambda.Function.ImageConfig.WorkingDirectory=
Lambda.Function.KmsKeyArn=
Lambda.Function.Layers=
Lambda.Function.LoggingConfig.ApplicationLogLevel=
Lambda.Function.LoggingConfig.LogFormat=
Lambda.Function.LoggingConfig.LogGroup=
Lambda.Function.LoggingConfig.SystemLogLevel=
Lambda.Function.MemorySize=
Lambda.Function.PackageType=
Lambda.Function.RecursiveLoop=
Lambda.Function.ReservedConcurrentExecutions=
Lambda.Function.Role=
Lambda.Function.Runtime=
Lambda.Function.RuntimeManagementConfig.RuntimeVersionArn=
Lambda.Function.RuntimeManagementConfig.UpdateRuntimeOn=
Lambda.Function.Tags[].Key=
Lambda.Function.Tags[].Value=
Lambda.Function.Timeout=
Lambda.Function.TracingConfig.Mode=
Lambda.Function.VpcConfig.Ipv6AllowedForDualStack=
Lambda.Function.VpcConfig.SecurityGroupIds=
Lambda.Function.VpcConfig.SubnetIds=
