Lambda.EventInvokeConfig.DestinationConfig.OnFailure.Destination=
Lambda.EventInvokeConfig.DestinationConfig.OnSuccess.Destination=
Lambda.EventInvokeConfig.FunctionName=
Lambda.EventInvokeConfig.MaximumEventAgeInSeconds=
Lambda.EventInvokeConfig.MaximumRetryAttempts=
Lambda.EventInvokeConfig.Qualifier=
