Logs.LogGroup.DataProtectionPolicy=
Logs.LogGroup.DeletionProtectionEnabled=
Logs.LogGroup.KmsKeyId=
Logs.LogGroup.LogGroupClass=
Logs.LogGroup.LogGroupName=
Logs.LogGroup.ResourcePolicyDocument=
Logs.LogGroup.RetentionInDays=
Logs.LogGroup.Tags[].Key=
Logs.LogGroup.Tags[].Value=
