QuickSight.VPCConnection.AwsAccountId=
QuickSight.VPCConnection.DnsResolvers=
QuickSight.VPCConnection.Name=
QuickSight.VPCConnection.RoleArn=
QuickSight.VPCConnection.SecurityGroupIds=
QuickSight.VPCConnection.SubnetIds=
QuickSight.VPCConnection.Tags[].Key=
QuickSight.VPCConnection.Tags[].Value=
QuickSight.VPCConnection.VPCConnectionId=
