QuickSight.DataSet.AwsAccountId=
QuickSight.DataSet.DataSetId=
QuickSight.DataSet.DataSetRefreshProperties.FailureConfiguration.EmailAlert.AlertStatus=
QuickSight.DataSet.DataSetRefreshProperties.RefreshConfiguration.IncrementalRefresh.LookbackWindow.ColumnName=
QuickSight.DataSet.DataSetRefreshProperties.RefreshConfiguration.IncrementalRefresh.LookbackWindow.Size=
QuickSight.DataSet.DataSetRefreshProperties.RefreshConfiguration.IncrementalRefresh.LookbackWindow.SizeUnit=
QuickSight.DataSet.DataSetUsageConfiguration.DisableUseAsDirectQuerySource=
QuickSight.DataSet.DataSetUsageConfiguration.DisableUseAsImportedSource=
QuickSight.DataSet.FieldFolders=
QuickSight.DataSet.FolderArns=
QuickSight.DataSet.ImportMode=
QuickSight.DataSet.IngestionWaitPolicy.IngestionWaitTimeInHours=
QuickSight.DataSet.IngestionWaitPolicy.WaitForSpiceIngestion=
QuickSight.DataSet.Name=
QuickSight.DataSet.PerformanceConfiguration.UniqueKeys[].ColumnNames=
QuickSight.DataSet.Permissions[].Actions=
QuickSight.DataSet.Permissions[].Principal=
QuickSight.DataSet.PhysicalTableMap=
QuickSight.DataSet.Tags[].Key=
QuickSight.DataSet.Tags[].Value=
QuickSight.DataSet.UseAs=
