QuickSight.DataSource.AwsAccountId=
QuickSight.DataSource.Credentials.SecretArn=
QuickSight.DataSource.DataSourceId=
QuickSight.DataSource.DataSourceParameters.AthenaParameters.IdentityCenterConfiguration.EnableIdentityPropagation=
QuickSight.DataSource.DataSourceParameters.AthenaParameters.RoleArn=
QuickSight.DataSource.DataSourceParameters.AthenaParameters.WorkGroup=
QuickSight.DataSource.DataSourceParameters.S3Parameters.ManifestFileLocation.Bucket=
QuickSight.DataSource.DataSourceParameters.S3Parameters.ManifestFileLocation.Key=
QuickSight.DataSource.DataSourceParameters.S3Parameters.RoleArn=
QuickSight.DataSource.DataSourceParameters.SnowflakeParameters.AuthenticationType=
QuickSight.DataSource.DataSourceParameters.SnowflakeParameters.Database=
QuickSight.DataSource.DataSourceParameters.SnowflakeParameters.DatabaseAccessControlRole=
QuickSight.DataSource.DataSourceParameters.SnowflakeParameters.Host=
QuickSight.DataSource.DataSourceParameters.SnowflakeParameters.OAuthParameters.IdentityProviderResourceUri=
QuickSight.DataSource.DataSourceParameters.SnowflakeParameters.OAuthParameters.IdentityProviderVpcConnectionProperties.VpcConnectionArn=
QuickSight.DataSource.DataSourceParameters.SnowflakeParameters.OAuthParameters.OAuthScope=
QuickSight.DataSource.DataSourceParameters.SnowflakeParameters.OAuthParameters.TokenProviderUrl=
QuickSight.DataSource.DataSourceParameters.SnowflakeParameters.Warehouse=
QuickSight.DataSource.Name=
QuickSight.DataSource.Permissions[].Actions=
QuickSight.DataSource.Permissions[].Principal=
QuickSight.DataSource.Permissions[].Resource=
QuickSight.DataSource.SslProperties.DisableSsl=
QuickSight.DataSource.Tags[].Key=
QuickSight.DataSource.Tags[].Value=
QuickSight.DataSource.Type=
QuickSight.DataSource.VpcConnectionProperties.VpcConnectionArn=
