RDS.DBProxyEndpoint.DBProxyEndpointName=
RDS.DBProxyEndpoint.DBProxyName=
RDS.DBProxyEndpoint.EndpointNetworkType=
RDS.DBProxyEndpoint.Tags[].Key=
RDS.DBProxyEndpoint.Tags[].Value=
RDS.DBProxyEndpoint.TargetRole=
RDS.DBProxyEndpoint.VpcSecurityGroupIds[]=
RDS.DBProxyEndpoint.VpcSubnetIds[]=
