RDS.DBProxyTargetGroup.ConnectionPoolConfigurationInfo.ConnectionBorrowTimeout=
RDS.DBProxyTargetGroup.ConnectionPoolConfigurationInfo.InitQuery=
RDS.DBProxyTargetGroup.ConnectionPoolConfigurationInfo.MaxConnectionsPercent=
RDS.DBProxyTargetGroup.ConnectionPoolConfigurationInfo.MaxIdleConnectionsPercent=
RDS.DBProxyTargetGroup.ConnectionPoolConfigurationInfo.SessionPinningFilters[]=
RDS.DBProxyTargetGroup.DBClusterIdentifiers[]=
RDS.DBProxyTargetGroup.DBInstanceIdentifiers[]=
RDS.DBProxyTargetGroup.DBProxyName=
RDS.DBProxyTargetGroup.TargetGroupName=
