S3.Bucket.BucketEncryption.ServerSideEncryptionConfiguration[].BucketKeyEnabled=
S3.Bucket.BucketEncryption.ServerSideEncryptionConfiguration[].ServerSideEncryptionByDefault.KMSMasterKeyID=
S3.Bucket.BucketEncryption.ServerSideEncryptionConfiguration[].ServerSideEncryptionByDefault.SSEAlgorithm=
S3.Bucket.BucketName=
S3.Bucket.LifecycleConfiguration.Rules[].AbortIncompleteMultipartUpload.DaysAfterInitiation=
S3.Bucket.LifecycleConfiguration.Rules[].ExpirationDate=
S3.Bucket.LifecycleConfiguration.Rules[].ExpirationInDays=
S3.Bucket.LifecycleConfiguration.Rules[].ExpiredObjectDeleteMarker=
S3.Bucket.LifecycleConfiguration.Rules[].Id=
S3.Bucket.LifecycleConfiguration.Rules[].NoncurrentVersionExpiration.NewerNoncurrentVersions=
S3.Bucket.LifecycleConfiguration.Rules[].NoncurrentVersionExpiration.NoncurrentDays=
S3.Bucket.LifecycleConfiguration.Rules[].NoncurrentVersionTransitions[].NewerNoncurrentVersions=
S3.Bucket.LifecycleConfiguration.Rules[].NoncurrentVersionTransitions[].StorageClass=
S3.Bucket.LifecycleConfiguration.Rules[].NoncurrentVersionTransitions[].TransitionInDays=
S3.Bucket.LifecycleConfiguration.Rules[].ObjectSizeGreaterThan=
S3.Bucket.LifecycleConfiguration.Rules[].ObjectSizeLessThan=
S3.Bucket.LifecycleConfiguration.Rules[].Prefix=
S3.Bucket.LifecycleConfiguration.Rules[].Status=
S3.Bucket.LifecycleConfiguration.Rules[].TagFilters[].Key=
S3.Bucket.LifecycleConfiguration.Rules[].TagFilters[].Value=
S3.Bucket.LifecycleConfiguration.Rules[].Transitions[].StorageClass=
S3.Bucket.LifecycleConfiguration.Rules[].Transitions[].TransitionDate=
S3.Bucket.LifecycleConfiguration.Rules[].Transitions[].TransitionInDays=
S3.Bucket.LifecycleConfiguration.TransitionDefaultMinimumObjectSize=
S3.Bucket.LoggingConfiguration.DestinationBucketName=
S3.Bucket.LoggingConfiguration.LogFilePrefix=
S3.Bucket.LoggingConfiguration.TargetObjectKeyFormat.PartitionedPrefix.PartitionDateSource=
S3.Bucket.LoggingConfiguration.TargetObjectKeyFormat.SimplePrefix=
S3.Bucket.NotificationConfiguration.EventBridgeConfiguration.EventBridgeEnabled=
S3.Bucket.NotificationConfiguration.LambdaConfigurations[].Event=
S3.Bucket.NotificationConfiguration.LambdaConfigurations[].Filter.S3Key.Rules[].Name=
S3.Bucket.NotificationConfiguration.LambdaConfigurations[].Filter.S3Key.Rules[].Value=
S3.Bucket.NotificationConfiguration.LambdaConfigurations[].Function=
S3.Bucket.NotificationConfiguration.QueueConfigurations[].Event=
S3.Bucket.NotificationConfiguration.QueueConfigurations[].Filter.S3Key.Rules[].Name=
S3.Bucket.NotificationConfiguration.QueueConfigurations[].Filter.S3Key.Rules[].Value=
S3.Bucket.NotificationConfiguration.QueueConfigurations[].Queue=
S3.Bucket.NotificationConfiguration.TopicConfigurations[].Event=
S3.Bucket.NotificationConfiguration.TopicConfigurations[].Filter.S3Key.Rules[].Name=
S3.Bucket.NotificationConfiguration.TopicConfigurations[].Filter.S3Key.Rules[].Value=
S3.Bucket.NotificationConfiguration.TopicConfigurations[].Topic=
S3.Bucket.ObjectLockConfiguration.ObjectLockEnabled=
S3.Bucket.ObjectLockConfiguration.Rule.DefaultRetention.Days=
S3.Bucket.ObjectLockConfiguration.Rule.DefaultRetention.Mode=
S3.Bucket.ObjectLockConfiguration.Rule.DefaultRetention.Years=
S3.Bucket.ObjectLockEnabled=
S3.Bucket.OwnershipControls.Rules[].ObjectOwnership=
S3.Bucket.PublicAccessBlockConfiguration.BlockPublicAcls=
S3.Bucket.PublicAccessBlockConfiguration.BlockPublicPolicy=
S3.Bucket.PublicAccessBlockConfiguration.IgnorePublicAcls=
S3.Bucket.PublicAccessBlockConfiguration.RestrictPublicBuckets=
S3.Bucket.ReplicationConfiguration.Role=
S3.Bucket.ReplicationConfiguration.Rules[].DeleteMarkerReplication.Status=
S3.Bucket.ReplicationConfiguration.Rules[].Destination.Account=
S3.Bucket.ReplicationConfiguration.Rules[].Destination.Bucket=
S3.Bucket.ReplicationConfiguration.Rules[].Destination.EncryptionConfiguration.ReplicaKmsKeyID=
S3.Bucket.ReplicationConfiguration.Rules[].Destination.Metrics.EventThreshold.Minutes=
S3.Bucket.ReplicationConfiguration.Rules[].Destination.Metrics.Status=
S3.Bucket.ReplicationConfiguration.Rules[].Destination.ReplicationTime.Status=
S3.Bucket.ReplicationConfiguration.Rules[].Destination.ReplicationTime.Time.Minutes=
S3.Bucket.ReplicationConfiguration.Rules[].Destination.StorageClass=
S3.Bucket.ReplicationConfiguration.Rules[].Filter.And.Prefix=
S3.Bucket.ReplicationConfiguration.Rules[].Filter.And.TagFilters[].Key=
S3.Bucket.ReplicationConfiguration.Rules[].Filter.And.TagFilters[].Value=
S3.Bucket.ReplicationConfiguration.Rules[].Filter.Prefix=
S3.Bucket.ReplicationConfiguration.Rules[].Filter.TagFilter.Key=
S3.Bucket.ReplicationConfiguration.Rules[].Filter.TagFilter.Value=
S3.Bucket.ReplicationConfiguration.Rules[].Id=
S3.Bucket.ReplicationConfiguration.Rules[].Priority=
S3.Bucket.ReplicationConfiguration.Rules[].SourceSelectionCriteria.ReplicaModifications.Status=
S3.Bucket.ReplicationConfiguration.Rules[].SourceSelectionCriteria.SseKmsEncryptedObjects.Status=
S3.Bucket.ReplicationConfiguration.Rules[].Status=
S3.Bucket.Tags[].Key=
S3.Bucket.Tags[].Value=
S3.Bucket.VersioningConfiguration.Status=
