SNS.Subscription.DeliveryPolicy=
SNS.Subscription.Endpoint=
SNS.Subscription.FilterPolicy=
SNS.Subscription.FilterPolicyScope=
SNS.Subscription.Protocol=
SNS.Subscription.RawMessageDelivery=
SNS.Subscription.RedrivePolicy=
SNS.Subscription.Region=
SNS.Subscription.ReplayPolicy=
SNS.Subscription.SubscriptionRoleArn=
SNS.Subscription.TopicArn=
