SSO.PermissionSet.CustomerManagedPolicyReferences[].Name=
SSO.PermissionSet.CustomerManagedPolicyReferences[].Path=
SSO.PermissionSet.Description=
SSO.PermissionSet.InlinePolicy=
SSO.PermissionSet.InstanceArn=
SSO.PermissionSet.ManagedPolicies=
SSO.PermissionSet.Name=
SSO.PermissionSet.PermissionsBoundary.CustomerManagedPolicyReference.Name=
SSO.PermissionSet.PermissionsBoundary.CustomerManagedPolicyReference.Path=
SSO.PermissionSet.PermissionsBoundary.ManagedPolicyArn=
SSO.PermissionSet.RelayStateType=
SSO.PermissionSet.SessionDuration=
SSO.PermissionSet.Tags[].Key=
SSO.PermissionSet.Tags[].Value=
