ApiGateway.RestApi.ApiKeySourceType=
ApiGateway.RestApi.BinaryMediaTypes[]=
ApiGateway.RestApi.Body=
ApiGateway.RestApi.BodyS3Location.Bucket=
ApiGateway.RestApi.BodyS3Location.ETag=
ApiGateway.RestApi.BodyS3Location.Key=
ApiGateway.RestApi.BodyS3Location.Version=
ApiGateway.RestApi.CloneFrom=
ApiGateway.RestApi.Description=
ApiGateway.RestApi.DisableExecuteApiEndpoint=
ApiGateway.RestApi.EndpointAccessMode=
ApiGateway.RestApi.EndpointConfiguration.IpAddressType=
ApiGateway.RestApi.EndpointConfiguration.Types[]=
ApiGateway.RestApi.EndpointConfiguration.VpcEndpointIds[]=
ApiGateway.RestApi.FailOnWarnings=
ApiGateway.RestApi.MinimumCompressionSize=
ApiGateway.RestApi.Mode=
ApiGateway.RestApi.Name=
ApiGateway.RestApi.Parameters=
ApiGateway.RestApi.Policy=
ApiGateway.RestApi.RestApiId=IDENTIFIER_OUTPUT
ApiGateway.RestApi.SecurityPolicy=
ApiGateway.RestApi.Tags[].Key=
ApiGateway.RestApi.Tags[].Value=
