ApiGatewayV2.RouteResponse.ApiId=
ApiGatewayV2.RouteResponse.ModelSelectionExpression=
ApiGatewayV2.RouteResponse.ResponseModels=
ApiGatewayV2.RouteResponse.ResponseParameters=
ApiGatewayV2.RouteResponse.RouteId=
ApiGatewayV2.RouteResponse.RouteResponseId=IDENTIFIER_OUTPUT
ApiGatewayV2.RouteResponse.RouteResponseKey=
