ApiGatewayV2.Route.ApiId=
ApiGatewayV2.Route.ApiKeyRequired=
ApiGatewayV2.Route.AuthorizationScopes[]=
ApiGatewayV2.Route.AuthorizationType=
ApiGatewayV2.Route.AuthorizerId=
ApiGatewayV2.Route.ModelSelectionExpression=
ApiGatewayV2.Route.OperationName=
ApiGatewayV2.Route.RequestModels=
ApiGatewayV2.Route.RequestParameters=
ApiGatewayV2.Route.RouteKey=
ApiGatewayV2.Route.RouteResponseSelectionExpression=
ApiGatewayV2.Route.Target=
