ApiGatewayV2.Stage.AccessLogSettings.DestinationArn=
ApiGatewayV2.Stage.AccessLogSettings.Format=
ApiGatewayV2.Stage.ApiId=
ApiGatewayV2.Stage.AutoDeploy=
ApiGatewayV2.Stage.ClientCertificateId=
ApiGatewayV2.Stage.DefaultRouteSettings.DataTraceEnabled=
ApiGatewayV2.Stage.DefaultRouteSettings.DetailedMetricsEnabled=
ApiGatewayV2.Stage.DefaultRouteSettings.LoggingLevel=
ApiGatewayV2.Stage.DefaultRouteSettings.ThrottlingBurstLimit=
ApiGatewayV2.Stage.DefaultRouteSettings.ThrottlingRateLimit=
ApiGatewayV2.Stage.DeploymentId=
ApiGatewayV2.Stage.Description=
ApiGatewayV2.Stage.RouteSettings=
ApiGatewayV2.Stage.StageName=
ApiGatewayV2.Stage.StageVariables=
ApiGatewayV2.Stage.Tags=
