ApiGatewayV2.Authorizer.ApiId=
ApiGatewayV2.Authorizer.AuthorizerCredentialsArn=
ApiGatewayV2.Authorizer.AuthorizerId=IDENTIFIER_OUTPUT
ApiGatewayV2.Authorizer.AuthorizerPayloadFormatVersion=
ApiGatewayV2.Authorizer.AuthorizerResultTtlInSeconds=
ApiGatewayV2.Authorizer.AuthorizerType=
ApiGatewayV2.Authorizer.AuthorizerUri=
ApiGatewayV2.Authorizer.EnableSimpleResponses=
ApiGatewayV2.Authorizer.IdentitySource[]=
ApiGatewayV2.Authorizer.IdentityValidationExpression=
ApiGatewayV2.Authorizer.JwtConfiguration.Audience[]=
ApiGatewayV2.Authorizer.JwtConfiguration.Issuer=
ApiGatewayV2.Authorizer.Name=
