ApiGateway.VpcLink.Name=
ApiGateway.VpcLink.VpcLinkId=IDENTIFIER_OUTPUT
ApiGateway.VpcLink.Description=
ApiGateway.VpcLink.Tags[].Key=
ApiGateway.VpcLink.Tags[].Value=
ApiGateway.VpcLink.TargetArns[]=
