ApiGatewayV2.DomainName.DomainName=
ApiGatewayV2.DomainName.DomainNameConfigurations[].CertificateArn=
ApiGatewayV2.DomainName.DomainNameConfigurations[].CertificateName=
ApiGatewayV2.DomainName.DomainNameConfigurations[].EndpointType=
ApiGatewayV2.DomainName.DomainNameConfigurations[].IpAddressType=
ApiGatewayV2.DomainName.DomainNameConfigurations[].OwnershipVerificationCertificateArn=
ApiGatewayV2.DomainName.DomainNameConfigurations[].SecurityPolicy=
ApiGatewayV2.DomainName.MutualTlsAuthentication.TruststoreUri=
ApiGatewayV2.DomainName.MutualTlsAuthentication.TruststoreVersion=
ApiGatewayV2.DomainName.RoutingMode=
ApiGatewayV2.DomainName.Tags=
