ApiGateway.UsagePlan.ApiStages[].ApiId=
ApiGateway.UsagePlan.ApiStages[].Stage=
ApiGateway.UsagePlan.ApiStages[].Throttle=
ApiGateway.UsagePlan.Description=
ApiGateway.UsagePlan.Id=IDENTIFIER_OUTPUT
ApiGateway.UsagePlan.Quota.Limit=
ApiGateway.UsagePlan.Quota.Offset=
ApiGateway.UsagePlan.Quota.Period=
ApiGateway.UsagePlan.Tags[].Key=
ApiGateway.UsagePlan.Tags[].Value=
ApiGateway.UsagePlan.Throttle.BurstLimit=
ApiGateway.UsagePlan.Throttle.RateLimit=
ApiGateway.UsagePlan.UsagePlanName=
