ApiGateway.Authorizer.AuthType=
ApiGateway.Authorizer.AuthorizerCredentials=
ApiGateway.Authorizer.AuthorizerId=IDENTIFIER_OUTPUT
ApiGateway.Authorizer.AuthorizerResultTtlInSeconds=
ApiGateway.Authorizer.AuthorizerUri=
ApiGateway.Authorizer.IdentitySource=
ApiGateway.Authorizer.IdentityValidationExpression=
ApiGateway.Authorizer.Name=
ApiGateway.Authorizer.ProviderARNs[]=
ApiGateway.Authorizer.RestApiId=
ApiGateway.Authorizer.Type=
