ApiGateway.GatewayResponse.ResponseParameters=
ApiGateway.GatewayResponse.ResponseTemplates=
ApiGateway.GatewayResponse.ResponseType=
ApiGateway.GatewayResponse.RestApiId=
ApiGateway.GatewayResponse.StatusCode=
