ApiGatewayV2.Api.ApiKeySelectionExpression=
ApiGatewayV2.Api.BasePath=
ApiGatewayV2.Api.Body=
ApiGatewayV2.Api.BodyS3Location.Bucket=
ApiGatewayV2.Api.BodyS3Location.Etag=
ApiGatewayV2.Api.BodyS3Location.Key=
ApiGatewayV2.Api.BodyS3Location.Version=
ApiGatewayV2.Api.CorsConfiguration.AllowCredentials=
ApiGatewayV2.Api.CorsConfiguration.AllowHeaders[]=
ApiGatewayV2.Api.CorsConfiguration.AllowMethods[]=
ApiGatewayV2.Api.CorsConfiguration.AllowOrigins[]=
ApiGatewayV2.Api.CorsConfiguration.ExposeHeaders[]=
ApiGatewayV2.Api.CorsConfiguration.MaxAge=
ApiGatewayV2.Api.CredentialsArn=
ApiGatewayV2.Api.Description=
ApiGatewayV2.Api.DisableExecuteApiEndpoint=
ApiGatewayV2.Api.DisableSchemaValidation=
ApiGatewayV2.Api.FailOnWarnings=
ApiGatewayV2.Api.IpAddressType=
ApiGatewayV2.Api.Name=
ApiGatewayV2.Api.ProtocolType=
ApiGatewayV2.Api.RouteKey=
ApiGatewayV2.Api.RouteSelectionExpression=
ApiGatewayV2.Api.Tags=
ApiGatewayV2.Api.Target=
ApiGatewayV2.Api.Version=
