ApiGatewayV2.Integration.ApiId=
ApiGatewayV2.Integration.ConnectionId=
ApiGatewayV2.Integration.ConnectionType=
ApiGatewayV2.Integration.ContentHandlingStrategy=
ApiGatewayV2.Integration.CredentialsArn=
ApiGatewayV2.Integration.Description=
ApiGatewayV2.Integration.IntegrationId=IDENTIFIER_OUTPUT
ApiGatewayV2.Integration.IntegrationMethod=
ApiGatewayV2.Integration.IntegrationSubtype=
ApiGatewayV2.Integration.IntegrationType=
ApiGatewayV2.Integration.IntegrationUri=
ApiGatewayV2.Integration.PassthroughBehavior=
ApiGatewayV2.Integration.PayloadFormatVersion=
ApiGatewayV2.Integration.RequestParameters=
ApiGatewayV2.Integration.RequestTemplates=
ApiGatewayV2.Integration.ResponseParameters=
ApiGatewayV2.Integration.TemplateSelectionExpression=
ApiGatewayV2.Integration.TimeoutInMillis=
ApiGatewayV2.Integration.TlsConfig.ServerNameToVerify=
