ApiGateway.ApiKey.APIKeyId=IDENTIFIER_OUTPUT
ApiGateway.ApiKey.CustomerId=
ApiGateway.ApiKey.Description=
ApiGateway.ApiKey.Enabled=
ApiGateway.ApiKey.GenerateDistinctId=
ApiGateway.ApiKey.Name=
ApiGateway.ApiKey.StageKeys[].RestApiId=
ApiGateway.ApiKey.StageKeys[].StageName=
ApiGateway.ApiKey.Tags[].Key=
ApiGateway.ApiKey.Tags[].Value=
ApiGateway.ApiKey.Value=
