ApiGateway.DomainName.CertificateArn=
ApiGateway.DomainName.DomainName=
ApiGateway.DomainName.EndpointAccessMode=
ApiGateway.DomainName.EndpointConfiguration.IpAddressType=
ApiGateway.DomainName.EndpointConfiguration.Types[]=
ApiGateway.DomainName.MutualTlsAuthentication.TruststoreUri=
ApiGateway.DomainName.MutualTlsAuthentication.TruststoreVersion=
ApiGateway.DomainName.OwnershipVerificationCertificateArn=
ApiGateway.DomainName.RegionalCertificateArn=
ApiGateway.DomainName.RoutingMode=
ApiGateway.DomainName.SecurityPolicy=
ApiGateway.DomainName.Tags[].Key=
ApiGateway.DomainName.Tags[].Value=
