Athena.WorkGroup.Description=
Athena.WorkGroup.Name=
Athena.WorkGroup.State=
Athena.WorkGroup.Tags[].Key=
Athena.WorkGroup.Tags[].Value=
Athena.WorkGroup.WorkGroupConfiguration.BytesScannedCutoffPerQuery=
Athena.WorkGroup.WorkGroupConfiguration.EnforceWorkGroupConfiguration=
Athena.WorkGroup.WorkGroupConfiguration.EngineVersion.SelectedEngineVersion=
Athena.WorkGroup.WorkGroupConfiguration.PublishCloudWatchMetricsEnabled=
Athena.WorkGroup.WorkGroupConfiguration.RequesterPaysEnabled=
Athena.WorkGroup.WorkGroupConfiguration.ResultConfiguration.AclConfiguration.S3AclOption=
Athena.WorkGroup.WorkGroupConfiguration.ResultConfiguration.EncryptionConfiguration.EncryptionOption=
Athena.WorkGroup.WorkGroupConfiguration.ResultConfiguration.EncryptionConfiguration.KmsKey=
Athena.WorkGroup.WorkGroupConfiguration.ResultConfiguration.ExpectedBucketOwner=
Athena.WorkGroup.WorkGroupConfiguration.ResultConfiguration.OutputLocation=
