AutoScaling.LifecycleHook.LifecycleHookName=
AutoScaling.LifecycleHook.AutoScalingGroupName=
AutoScaling.LifecycleHook.DefaultResult=
AutoScaling.LifecycleHook.HeartbeatTimeout=
AutoScaling.LifecycleHook.LifecycleTransition=
AutoScaling.LifecycleHook.NotificationMetadata=
AutoScaling.LifecycleHook.NotificationTargetARN=
AutoScaling.LifecycleHook.RoleARN=
