AutoScaling.ScalingPolicy.AdjustmentType=
AutoScaling.ScalingPolicy.AutoScalingGroupName=
AutoScaling.ScalingPolicy.Cooldown=
AutoScaling.ScalingPolicy.EstimatedInstanceWarmup=
AutoScaling.ScalingPolicy.MetricAggregationType=
AutoScaling.ScalingPolicy.MinAdjustmentMagnitude=
AutoScaling.ScalingPolicy.PolicyType=
AutoScaling.ScalingPolicy.PredictiveScalingConfiguration=
AutoScaling.ScalingPolicy.ScalingAdjustment=
AutoScaling.ScalingPolicy.StepAdjustments=
AutoScaling.ScalingPolicy.TargetTrackingConfiguration=
