CertificateManager.Certificate.CertificateAuthorityArn=
CertificateManager.Certificate.CertificateExport=
CertificateManager.Certificate.CertificateTransparencyLoggingPreference=
CertificateManager.Certificate.DomainName=
CertificateManager.Certificate.DomainValidationOptions[].DomainName=
CertificateManager.Certificate.DomainValidationOptions[].HostedZoneId=
CertificateManager.Certificate.DomainValidationOptions[].ValidationDomain=
CertificateManager.Certificate.KeyAlgorithm=
CertificateManager.Certificate.SubjectAlternativeNames=
CertificateManager.Certificate.Tags[].Key=
CertificateManager.Certificate.Tags[].Value=
CertificateManager.Certificate.ValidationMethod=
