CloudFront.ResponseHeadersPolicy.Id=IDENTIFIER_OUTPUT
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.Comment=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.CorsConfig.AccessControlAllowCredentials=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.CorsConfig.AccessControlAllowHeaders.Items[]=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.CorsConfig.AccessControlAllowMethods.Items[]=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.CorsConfig.AccessControlAllowOrigins.Items[]=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.CorsConfig.AccessControlExposeHeaders.Items[]=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.CorsConfig.AccessControlMaxAgeSec=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.CorsConfig.OriginOverride=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items[].Header=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items[].Override=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.CustomHeadersConfig.Items[].Value=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.Name=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.RemoveHeadersConfig.Items[].Header=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.ContentSecurityPolicy=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentSecurityPolicy.Override=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ContentTypeOptions.Override=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.FrameOption=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.FrameOptions.Override=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.Override=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.ReferrerPolicy.ReferrerPolicy=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.AccessControlMaxAgeSec=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.IncludeSubdomains=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Override=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.StrictTransportSecurity.Preload=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ModeBlock=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Override=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.Protection=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.SecurityHeadersConfig.XSSProtection.ReportUri=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.Enabled=
CloudFront.ResponseHeadersPolicy.ResponseHeadersPolicyConfig.ServerTimingHeadersConfig.SamplingRate=
