CloudFront.OriginAccessControl.OriginAccessControlConfig.Description=
CloudFront.OriginAccessControl.OriginAccessControlConfig.Name=
CloudFront.OriginAccessControl.OriginAccessControlConfig.OriginAccessControlOriginType=
CloudFront.OriginAccessControl.OriginAccessControlConfig.SigningBehavior=
CloudFront.OriginAccessControl.OriginAccessControlConfig.SigningProtocol=
