CloudFront.OriginRequestPolicy.Id=IDENTIFIER_OUTPUT
CloudFront.OriginRequestPolicy.OriginRequestPolicyConfig.Comment=
CloudFront.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig.CookieBehavior=
CloudFront.OriginRequestPolicy.OriginRequestPolicyConfig.CookiesConfig.Cookies[]=
CloudFront.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig.HeaderBehavior=
CloudFront.OriginRequestPolicy.OriginRequestPolicyConfig.HeadersConfig.Headers[]=
CloudFront.OriginRequestPolicy.OriginRequestPolicyConfig.Name=
CloudFront.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig.QueryStringBehavior=
CloudFront.OriginRequestPolicy.OriginRequestPolicyConfig.QueryStringsConfig.QueryStrings[]=
