Config.ConfigRule.ConfigRuleId=IDENTIFIER_OUTPUT
Config.ConfigRule.ConfigRuleName=
Config.ConfigRule.Description=
Config.ConfigRule.Scope.TagKey=
Config.ConfigRule.Scope.ComplianceResourceTypes=
Config.ConfigRule.Scope.TagValue=
Config.ConfigRule.Scope.ComplianceResourceId=
Config.ConfigRule.MaximumExecutionFrequency=
Config.ConfigRule.Source.CustomPolicyDetails.EnableDebugLogDelivery=
Config.ConfigRule.Source.CustomPolicyDetails.PolicyText=
Config.ConfigRule.Source.CustomPolicyDetails.PolicyRuntime=
Config.ConfigRule.Source.SourceIdentifier=
Config.ConfigRule.Source.Owner=
Config.ConfigRule.Source.SourceDetails[].EventSource=
Config.ConfigRule.Source.SourceDetails[].MaximumExecutionFrequency=
Config.ConfigRule.Source.SourceDetails[].MessageType=
Config.ConfigRule.InputParameters=
Config.ConfigRule.EvaluationModes[].Mode=
