Config.DeliveryChannel.ConfigSnapshotDeliveryProperties.DeliveryFrequency=
Config.DeliveryChannel.Name=
Config.DeliveryChannel.S3BucketName=
Config.DeliveryChannel.S3KeyPrefix=
Config.DeliveryChannel.S3KmsKeyArn=
Config.DeliveryChannel.SnsTopicARN=
