DataZone.ProjectMembership.MemberIdentifier=IDENTIFIER_OUTPUT
DataZone.ProjectMembership.MemberIdentifierType=IDENTIFIER_OUTPUT
DataZone.ProjectMembership.Designation=
DataZone.ProjectMembership.DomainIdentifier=
DataZone.ProjectMembership.Member.GroupIdentifier=
DataZone.ProjectMembership.Member.UserIdentifier=
DataZone.ProjectMembership.ProjectIdentifier=
