DataZone.Connection.DomainId=IDENTIFIER_OUTPUT
DataZone.Connection.ConnectionId=IDENTIFIER_OUTPUT
DataZone.Connection.AwsLocation.AccessRole=
DataZone.Connection.AwsLocation.AwsAccountId=
DataZone.Connection.AwsLocation.AwsRegion=
DataZone.Connection.AwsLocation.IamConnectionId=
DataZone.Connection.Configurations[].Classification=
DataZone.Connection.Configurations[].Properties=
DataZone.Connection.Description=
DataZone.Connection.DomainIdentifier=
DataZone.Connection.EnableTrustedIdentityPropagation=
DataZone.Connection.EnvironmentIdentifier=
DataZone.Connection.Name=
DataZone.Connection.ProjectIdentifier=
DataZone.Connection.Props.AmazonQProperties.AuthMode=
DataZone.Connection.Props.AmazonQProperties.IsEnabled=
DataZone.Connection.Props.AmazonQProperties.ProfileArn=
DataZone.Connection.Props.AthenaProperties.WorkgroupName=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AthenaProperties=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.AuthenticationType=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.BasicAuthenticationCredentials.Password=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.BasicAuthenticationCredentials.UserName=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.CustomAuthenticationCredentials=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.KmsKeyArn=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.OAuth2Properties.AuthorizationCodeProperties.AuthorizationCode=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.OAuth2Properties.AuthorizationCodeProperties.RedirectUri=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.OAuth2Properties.OAuth2ClientApplication.AWSManagedClientApplicationReference=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.OAuth2Properties.OAuth2ClientApplication.UserManagedClientApplicationClientId=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.OAuth2Properties.OAuth2Credentials.AccessToken=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.OAuth2Properties.OAuth2Credentials.JwtToken=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.OAuth2Properties.OAuth2Credentials.RefreshToken=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.OAuth2Properties.OAuth2Credentials.UserManagedClientApplicationClientSecret=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.OAuth2Properties.OAuth2GrantType=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.OAuth2Properties.TokenUrl=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.OAuth2Properties.TokenUrlParametersMap=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.AuthenticationConfiguration.SecretArn=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.ConnectionProperties=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.ConnectionType=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.Description=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.MatchCriteria=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.Name=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.PhysicalConnectionRequirements.AvailabilityZone=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.PhysicalConnectionRequirements.SecurityGroupIdList[]=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.PhysicalConnectionRequirements.SubnetId=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.PhysicalConnectionRequirements.SubnetIdList[]=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.PythonProperties=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.SparkProperties=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.ValidateCredentials=
DataZone.Connection.Props.GlueProperties.GlueConnectionInput.ValidateForComputeEnvironments[]=
DataZone.Connection.Props.HyperPodProperties.ClusterName=
DataZone.Connection.Props.IamProperties.GlueLineageSyncEnabled=
DataZone.Connection.Props.IamProperties.RoleArn=
DataZone.Connection.Props.LakehouseProperties.GlueLineageSyncEnabled=
DataZone.Connection.Props.MlflowProperties.TrackingServerArn=
DataZone.Connection.Props.RedshiftProperties.Credentials.SecretArn=
DataZone.Connection.Props.RedshiftProperties.Credentials.UsernamePassword.Password=
DataZone.Connection.Props.RedshiftProperties.Credentials.UsernamePassword.Username=
DataZone.Connection.Props.RedshiftProperties.DatabaseName=
DataZone.Connection.Props.RedshiftProperties.Host=
DataZone.Connection.Props.RedshiftProperties.LineageSync.Enabled=
DataZone.Connection.Props.RedshiftProperties.LineageSync.Schedule.Schedule=
DataZone.Connection.Props.RedshiftProperties.Port=
DataZone.Connection.Props.RedshiftProperties.Storage.ClusterName=
DataZone.Connection.Props.RedshiftProperties.Storage.WorkgroupName=
DataZone.Connection.Props.S3Properties.RegisterS3AccessGrantLocation=
DataZone.Connection.Props.S3Properties.S3AccessGrantLocationId=
DataZone.Connection.Props.S3Properties.S3Uri=
DataZone.Connection.Props.SparkEmrProperties.ComputeArn=
DataZone.Connection.Props.SparkEmrProperties.InstanceProfileArn=
DataZone.Connection.Props.SparkEmrProperties.JavaVirtualEnv=
DataZone.Connection.Props.SparkEmrProperties.LogUri=
DataZone.Connection.Props.SparkEmrProperties.ManagedEndpointArn=
DataZone.Connection.Props.SparkEmrProperties.PythonVirtualEnv=
DataZone.Connection.Props.SparkEmrProperties.RuntimeRole=
DataZone.Connection.Props.SparkEmrProperties.TrustedCertificatesS3Uri=
DataZone.Connection.Props.SparkGlueProperties.AdditionalArgs.Connection=
DataZone.Connection.Props.SparkGlueProperties.GlueConnectionName=
DataZone.Connection.Props.SparkGlueProperties.GlueVersion=
DataZone.Connection.Props.SparkGlueProperties.IdleTimeout=
DataZone.Connection.Props.SparkGlueProperties.JavaVirtualEnv=
DataZone.Connection.Props.SparkGlueProperties.NumberOfWorkers=
DataZone.Connection.Props.SparkGlueProperties.PythonVirtualEnv=
DataZone.Connection.Props.SparkGlueProperties.WorkerType=
DataZone.Connection.Props.WorkflowsMwaaProperties.MwaaEnvironmentName=
DataZone.Connection.Props.WorkflowsServerlessProperties=
DataZone.Connection.Scope=
