DataZone.EnvironmentBlueprintConfiguration.DomainId=IDENTIFIER_OUTPUT
DataZone.EnvironmentBlueprintConfiguration.EnvironmentBlueprintId=IDENTIFIER_OUTPUT
DataZone.EnvironmentBlueprintConfiguration.DomainIdentifier=
DataZone.EnvironmentBlueprintConfiguration.EnabledRegions[]=
DataZone.EnvironmentBlueprintConfiguration.EnvironmentBlueprintIdentifier=
DataZone.EnvironmentBlueprintConfiguration.EnvironmentRolePermissionBoundary=
DataZone.EnvironmentBlueprintConfiguration.GlobalParameters=
DataZone.EnvironmentBlueprintConfiguration.ManageAccessRoleArn=
DataZone.EnvironmentBlueprintConfiguration.ProvisioningConfigurations[].LakeFormationConfiguration.LocationRegistrationExcludeS3Locations[]=
DataZone.EnvironmentBlueprintConfiguration.ProvisioningConfigurations[].LakeFormationConfiguration.LocationRegistrationRole=
DataZone.EnvironmentBlueprintConfiguration.ProvisioningRoleArn=
DataZone.EnvironmentBlueprintConfiguration.RegionalParameters[].Parameters=
DataZone.EnvironmentBlueprintConfiguration.RegionalParameters[].Region=
