DataZone.Environment.DomainId=IDENTIFIER_OUTPUT
DataZone.Environment.Id=IDENTIFIER_OUTPUT
DataZone.Environment.DeploymentOrder=
DataZone.Environment.Description=
DataZone.Environment.DomainIdentifier=
DataZone.Environment.EnvironmentAccountIdentifier=
DataZone.Environment.EnvironmentAccountRegion=
DataZone.Environment.EnvironmentBlueprintIdentifier=
DataZone.Environment.EnvironmentConfigurationId=
DataZone.Environment.EnvironmentProfileIdentifier=
DataZone.Environment.EnvironmentRoleArn=
DataZone.Environment.GlossaryTerms[]=
DataZone.Environment.Name=
DataZone.Environment.ProjectIdentifier=
DataZone.Environment.UserParameters[].Name=
DataZone.Environment.UserParameters[].Value=
