DataZone.DataSource.DomainId=IDENTIFIER_OUTPUT
DataZone.DataSource.Id=IDENTIFIER_OUTPUT
DataZone.DataSource.AssetFormsInput[].Content=
DataZone.DataSource.AssetFormsInput[].FormName=
DataZone.DataSource.AssetFormsInput[].TypeIdentifier=
DataZone.DataSource.AssetFormsInput[].TypeRevision=
DataZone.DataSource.Configuration.GlueRunConfiguration.AutoImportDataQualityResult=
DataZone.DataSource.Configuration.GlueRunConfiguration.CatalogName=
DataZone.DataSource.Configuration.GlueRunConfiguration.DataAccessRole=
DataZone.DataSource.Configuration.GlueRunConfiguration.RelationalFilterConfigurations[].DatabaseName=
DataZone.DataSource.Configuration.GlueRunConfiguration.RelationalFilterConfigurations[].FilterExpressions[].Expression=
DataZone.DataSource.Configuration.GlueRunConfiguration.RelationalFilterConfigurations[].FilterExpressions[].Type=
DataZone.DataSource.Configuration.GlueRunConfiguration.RelationalFilterConfigurations[].SchemaName=
DataZone.DataSource.ConnectionIdentifier=
DataZone.DataSource.Description=
DataZone.DataSource.DomainIdentifier=
DataZone.DataSource.EnableSetting=
DataZone.DataSource.EnvironmentIdentifier=
DataZone.DataSource.Name=
DataZone.DataSource.ProjectIdentifier=
DataZone.DataSource.PublishOnImport=
DataZone.DataSource.Recommendation.EnableBusinessNameGeneration=
DataZone.DataSource.Schedule.Schedule=
DataZone.DataSource.Schedule.Timezone=
DataZone.DataSource.Type=
