DataZone.EnvironmentProfile.DomainId=IDENTIFIER_OUTPUT
DataZone.EnvironmentProfile.Id=IDENTIFIER_OUTPUT
DataZone.EnvironmentProfile.AwsAccountId=
DataZone.EnvironmentProfile.AwsAccountRegion=
DataZone.EnvironmentProfile.Description=
DataZone.EnvironmentProfile.DomainIdentifier=
DataZone.EnvironmentProfile.EnvironmentBlueprintIdentifier=
DataZone.EnvironmentProfile.Name=
DataZone.EnvironmentProfile.ProjectIdentifier=
DataZone.EnvironmentProfile.UserParameters[].Name=
DataZone.EnvironmentProfile.UserParameters[].Value=
