DataZone.Owner.OwnerType=IDENTIFIER_OUTPUT
DataZone.Owner.OwnerIdentifier=IDENTIFIER_OUTPUT
DataZone.Owner.DomainIdentifier=
DataZone.Owner.EntityIdentifier=
DataZone.Owner.EntityType=
DataZone.Owner.Owner.Group.GroupIdentifier=
DataZone.Owner.Owner.User.UserIdentifier=
