DataZone.Project.DomainId=IDENTIFIER_OUTPUT
DataZone.Project.Id=IDENTIFIER_OUTPUT
DataZone.Project.Description=
DataZone.Project.DomainIdentifier=
DataZone.Project.DomainUnitId=
DataZone.Project.GlossaryTerms[]=
DataZone.Project.MembershipAssignments[].Designation=
DataZone.Project.MembershipAssignments[].Member.GroupIdentifier=
DataZone.Project.MembershipAssignments[].Member.UserIdentifier=
DataZone.Project.Name=
DataZone.Project.ProjectCategory=
DataZone.Project.ProjectExecutionRole=
DataZone.Project.ProjectProfileId=
DataZone.Project.ProjectProfileVersion=
DataZone.Project.ResourceTags[].Key=
DataZone.Project.ResourceTags[].Value=
DataZone.Project.UserParameters[].EnvironmentConfigurationName=
DataZone.Project.UserParameters[].EnvironmentId=
DataZone.Project.UserParameters[].EnvironmentParameters[].Name=
DataZone.Project.UserParameters[].EnvironmentParameters[].Value=
