DataZone.Domain.Id=IDENTIFIER_OUTPUT
DataZone.Domain.Description=
DataZone.Domain.DomainExecutionRole=
DataZone.Domain.DomainVersion=
DataZone.Domain.KmsKeyIdentifier=
DataZone.Domain.Name=
DataZone.Domain.ServiceRole=
DataZone.Domain.SingleSignOn.IdcInstanceArn=
DataZone.Domain.SingleSignOn.Type=
DataZone.Domain.SingleSignOn.UserAssignment=
DataZone.Domain.Tags[].Key=
DataZone.Domain.Tags[].Value=
