DataZone.ProjectProfile.Identifier=IDENTIFIER_OUTPUT
DataZone.ProjectProfile.AllowCustomProjectResourceTags=
DataZone.ProjectProfile.Description=
DataZone.ProjectProfile.DomainIdentifier=
DataZone.ProjectProfile.DomainUnitIdentifier=
DataZone.ProjectProfile.EnvironmentConfigurations[].AwsAccount.AwsAccountId=
DataZone.ProjectProfile.EnvironmentConfigurations[].AwsRegion.RegionName=
DataZone.ProjectProfile.EnvironmentConfigurations[].ConfigurationParameters.ParameterOverrides[].IsEditable=
DataZone.ProjectProfile.EnvironmentConfigurations[].ConfigurationParameters.ParameterOverrides[].Name=
DataZone.ProjectProfile.EnvironmentConfigurations[].ConfigurationParameters.ParameterOverrides[].Value=
DataZone.ProjectProfile.EnvironmentConfigurations[].ConfigurationParameters.SsmPath=
DataZone.ProjectProfile.EnvironmentConfigurations[].DeploymentMode=
DataZone.ProjectProfile.EnvironmentConfigurations[].DeploymentOrder=
DataZone.ProjectProfile.EnvironmentConfigurations[].Description=
DataZone.ProjectProfile.EnvironmentConfigurations[].EnvironmentBlueprintId=
DataZone.ProjectProfile.EnvironmentConfigurations[].Name=
DataZone.ProjectProfile.Name=
DataZone.ProjectProfile.ProjectResourceTagsDescription=
DataZone.ProjectProfile.ProjectResourceTags[].IsValueEditable=
DataZone.ProjectProfile.ProjectResourceTags[].Key=
DataZone.ProjectProfile.ProjectResourceTags[].Value=
DataZone.ProjectProfile.Status=
DataZone.ProjectProfile.UseDefaultConfigurations=
