DynamoDB.GlobalTable.AttributeDefinitions[].AttributeName=
DynamoDB.GlobalTable.AttributeDefinitions[].AttributeType=
DynamoDB.GlobalTable.BillingMode=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].IndexName=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].KeySchema[].AttributeName=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].KeySchema[].KeyType=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].Projection.NonKeyAttributes[]=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].Projection.ProjectionType=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].ReadOnDemandThroughputSettings.MaxReadRequestUnits=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].ReadProvisionedThroughputSettings.ReadCapacityUnits=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].WarmThroughput.ReadUnitsPerSecond=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].WarmThroughput.WriteUnitsPerSecond=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].WriteOnDemandThroughputSettings.MaxWriteRequestUnits=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.MaxCapacity=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.MinCapacity=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.SeedCapacity=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.DisableScaleIn=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.ScaleInCooldown=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.ScaleOutCooldown=
DynamoDB.GlobalTable.GlobalSecondaryIndexes[].WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.TargetValue=
DynamoDB.GlobalTable.GlobalTableSourceArn=
DynamoDB.GlobalTable.GlobalTableWitnesses[].Region=
DynamoDB.GlobalTable.KeySchema[].AttributeName=
DynamoDB.GlobalTable.KeySchema[].KeyType=
DynamoDB.GlobalTable.LocalSecondaryIndexes[].IndexName=
DynamoDB.GlobalTable.LocalSecondaryIndexes[].KeySchema[].AttributeName=
DynamoDB.GlobalTable.LocalSecondaryIndexes[].KeySchema[].KeyType=
DynamoDB.GlobalTable.LocalSecondaryIndexes[].Projection.NonKeyAttributes[]=
DynamoDB.GlobalTable.LocalSecondaryIndexes[].Projection.ProjectionType=
DynamoDB.GlobalTable.MultiRegionConsistency=
DynamoDB.GlobalTable.ReadOnDemandThroughputSettings.MaxReadRequestUnits=
DynamoDB.GlobalTable.ReadProvisionedThroughputSettings.ReadCapacityUnits=
DynamoDB.GlobalTable.Replicas[].ContributorInsightsSpecification.Enabled=
DynamoDB.GlobalTable.Replicas[].ContributorInsightsSpecification.Mode=
DynamoDB.GlobalTable.Replicas[].DeletionProtectionEnabled=
DynamoDB.GlobalTable.Replicas[].GlobalSecondaryIndexes[].ContributorInsightsSpecification.Enabled=
DynamoDB.GlobalTable.Replicas[].GlobalSecondaryIndexes[].ContributorInsightsSpecification.Mode=
DynamoDB.GlobalTable.Replicas[].GlobalSecondaryIndexes[].IndexName=
DynamoDB.GlobalTable.Replicas[].GlobalSecondaryIndexes[].ReadOnDemandThroughputSettings.MaxReadRequestUnits=
DynamoDB.GlobalTable.Replicas[].GlobalSecondaryIndexes[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.MaxCapacity=
DynamoDB.GlobalTable.Replicas[].GlobalSecondaryIndexes[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.MinCapacity=
DynamoDB.GlobalTable.Replicas[].GlobalSecondaryIndexes[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.SeedCapacity=
DynamoDB.GlobalTable.Replicas[].GlobalSecondaryIndexes[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.DisableScaleIn=
DynamoDB.GlobalTable.Replicas[].GlobalSecondaryIndexes[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.ScaleInCooldown=
DynamoDB.GlobalTable.Replicas[].GlobalSecondaryIndexes[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.ScaleOutCooldown=
DynamoDB.GlobalTable.Replicas[].GlobalSecondaryIndexes[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.TargetValue=
DynamoDB.GlobalTable.Replicas[].GlobalSecondaryIndexes[].ReadProvisionedThroughputSettings.ReadCapacityUnits=
DynamoDB.GlobalTable.Replicas[].GlobalTableSettingsReplicationMode=
DynamoDB.GlobalTable.Replicas[].KinesisStreamSpecification.ApproximateCreationDateTimePrecision=
DynamoDB.GlobalTable.Replicas[].KinesisStreamSpecification.StreamArn=
DynamoDB.GlobalTable.Replicas[].PointInTimeRecoverySpecification.PointInTimeRecoveryEnabled=
DynamoDB.GlobalTable.Replicas[].PointInTimeRecoverySpecification.RecoveryPeriodInDays=
DynamoDB.GlobalTable.Replicas[].ReadOnDemandThroughputSettings.MaxReadRequestUnits=
DynamoDB.GlobalTable.Replicas[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.MaxCapacity=
DynamoDB.GlobalTable.Replicas[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.MinCapacity=
DynamoDB.GlobalTable.Replicas[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.SeedCapacity=
DynamoDB.GlobalTable.Replicas[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.DisableScaleIn=
DynamoDB.GlobalTable.Replicas[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.ScaleInCooldown=
DynamoDB.GlobalTable.Replicas[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.ScaleOutCooldown=
DynamoDB.GlobalTable.Replicas[].ReadProvisionedThroughputSettings.ReadCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.TargetValue=
DynamoDB.GlobalTable.Replicas[].ReadProvisionedThroughputSettings.ReadCapacityUnits=
DynamoDB.GlobalTable.Replicas[].Region=
DynamoDB.GlobalTable.Replicas[].ReplicaStreamSpecification.ResourcePolicy.PolicyDocument=
DynamoDB.GlobalTable.Replicas[].ResourcePolicy.PolicyDocument=
DynamoDB.GlobalTable.Replicas[].SSESpecification.KMSMasterKeyId=
DynamoDB.GlobalTable.Replicas[].TableClass=
DynamoDB.GlobalTable.Replicas[].Tags[].Key=
DynamoDB.GlobalTable.Replicas[].Tags[].Value=
DynamoDB.GlobalTable.SSESpecification.SSEEnabled=
DynamoDB.GlobalTable.SSESpecification.SSEType=
DynamoDB.GlobalTable.StreamSpecification.StreamViewType=
DynamoDB.GlobalTable.TableName=
DynamoDB.GlobalTable.TimeToLiveSpecification.AttributeName=
DynamoDB.GlobalTable.TimeToLiveSpecification.Enabled=
DynamoDB.GlobalTable.WarmThroughput.ReadUnitsPerSecond=
DynamoDB.GlobalTable.WarmThroughput.WriteUnitsPerSecond=
DynamoDB.GlobalTable.WriteOnDemandThroughputSettings.MaxWriteRequestUnits=
DynamoDB.GlobalTable.WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.MaxCapacity=
DynamoDB.GlobalTable.WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.MinCapacity=
DynamoDB.GlobalTable.WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.SeedCapacity=
DynamoDB.GlobalTable.WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.DisableScaleIn=
DynamoDB.GlobalTable.WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.ScaleInCooldown=
DynamoDB.GlobalTable.WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.ScaleOutCooldown=
DynamoDB.GlobalTable.WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings.TargetTrackingScalingPolicyConfiguration.TargetValue=
