DynamoDB.Table.AttributeDefinitions[].AttributeName=
DynamoDB.Table.AttributeDefinitions[].AttributeType=
DynamoDB.Table.BillingMode=
DynamoDB.Table.ContributorInsightsSpecification.Enabled=
DynamoDB.Table.ContributorInsightsSpecification.Mode=
DynamoDB.Table.DeletionProtectionEnabled=
DynamoDB.Table.GlobalSecondaryIndexes[].ContributorInsightsSpecification.Enabled=
DynamoDB.Table.GlobalSecondaryIndexes[].ContributorInsightsSpecification.Mode=
DynamoDB.Table.GlobalSecondaryIndexes[].IndexName=
DynamoDB.Table.GlobalSecondaryIndexes[].KeySchema[].AttributeName=
DynamoDB.Table.GlobalSecondaryIndexes[].KeySchema[].KeyType=
DynamoDB.Table.GlobalSecondaryIndexes[].OnDemandThroughput.MaxReadRequestUnits=
DynamoDB.Table.GlobalSecondaryIndexes[].OnDemandThroughput.MaxWriteRequestUnits=
DynamoDB.Table.GlobalSecondaryIndexes[].Projection.NonKeyAttributes[]=
DynamoDB.Table.GlobalSecondaryIndexes[].Projection.ProjectionType=
DynamoDB.Table.GlobalSecondaryIndexes[].ProvisionedThroughput.ReadCapacityUnits=
DynamoDB.Table.GlobalSecondaryIndexes[].ProvisionedThroughput.WriteCapacityUnits=
DynamoDB.Table.GlobalSecondaryIndexes[].WarmThroughput.ReadUnitsPerSecond=
DynamoDB.Table.GlobalSecondaryIndexes[].WarmThroughput.WriteUnitsPerSecond=
DynamoDB.Table.ImportSourceSpecification.InputCompressionType=
DynamoDB.Table.ImportSourceSpecification.InputFormat=
DynamoDB.Table.ImportSourceSpecification.InputFormatOptions.Csv.Delimiter=
DynamoDB.Table.ImportSourceSpecification.InputFormatOptions.Csv.HeaderList[]=
DynamoDB.Table.ImportSourceSpecification.S3BucketSource.S3Bucket=
DynamoDB.Table.ImportSourceSpecification.S3BucketSource.S3BucketOwner=
DynamoDB.Table.ImportSourceSpecification.S3BucketSource.S3KeyPrefix=
DynamoDB.Table.KeySchema[].AttributeName=
DynamoDB.Table.KeySchema[].KeyType=
DynamoDB.Table.KinesisStreamSpecification.ApproximateCreationDateTimePrecision=
DynamoDB.Table.KinesisStreamSpecification.StreamArn=
DynamoDB.Table.LocalSecondaryIndexes[].IndexName=
DynamoDB.Table.LocalSecondaryIndexes[].KeySchema[].AttributeName=
DynamoDB.Table.LocalSecondaryIndexes[].KeySchema[].KeyType=
DynamoDB.Table.LocalSecondaryIndexes[].Projection.NonKeyAttributes[]=
DynamoDB.Table.LocalSecondaryIndexes[].Projection.ProjectionType=
DynamoDB.Table.OnDemandThroughput.MaxReadRequestUnits=
DynamoDB.Table.OnDemandThroughput.MaxWriteRequestUnits=
DynamoDB.Table.PointInTimeRecoverySpecification.PointInTimeRecoveryEnabled=
DynamoDB.Table.PointInTimeRecoverySpecification.RecoveryPeriodInDays=
DynamoDB.Table.ProvisionedThroughput.ReadCapacityUnits=
DynamoDB.Table.ProvisionedThroughput.WriteCapacityUnits=
DynamoDB.Table.ResourcePolicy=
DynamoDB.Table.SSESpecification.KMSMasterKeyId=
DynamoDB.Table.SSESpecification.SSEEnabled=
DynamoDB.Table.SSESpecification.SSEType=
DynamoDB.Table.StreamSpecification.ResourcePolicy.PolicyDocument=
DynamoDB.Table.StreamSpecification.StreamViewType=
DynamoDB.Table.TableClass=
DynamoDB.Table.TableName=
DynamoDB.Table.Tags[].Key=
DynamoDB.Table.Tags[].Value=
DynamoDB.Table.TimeToLiveSpecification.AttributeName=
DynamoDB.Table.TimeToLiveSpecification.Enabled=
DynamoDB.Table.WarmThroughput.ReadUnitsPerSecond=
DynamoDB.Table.WarmThroughput.WriteUnitsPerSecond=
