EC2.VPCEndpoint.DnsOptions.DnsRecordIpType=
EC2.VPCEndpoint.DnsOptions.PrivateDnsOnlyForInboundResolverEndpoint=
EC2.VPCEndpoint.Id=IDENTIFIER_OUTPUT
EC2.VPCEndpoint.IpAddressType=
EC2.VPCEndpoint.PolicyDocument=
EC2.VPCEndpoint.PrivateDnsEnabled=
EC2.VPCEndpoint.RouteTableIds=
EC2.VPCEndpoint.SecurityGroupIds=
EC2.VPCEndpoint.ServiceName=
EC2.VPCEndpoint.ServiceRegion=
EC2.VPCEndpoint.SubnetIds=
EC2.VPCEndpoint.Tags[].Key=
EC2.VPCEndpoint.Tags[].Value=
EC2.VPCEndpoint.VpcEndpointType=
EC2.VPCEndpoint.VpcId=
