EC2.Instance.AvailabilityZone=
EC2.Instance.BlockDeviceMappings[].DeviceName=
EC2.Instance.BlockDeviceMappings[].Ebs.DeleteOnTermination=
EC2.Instance.BlockDeviceMappings[].Ebs.Encrypted=
EC2.Instance.BlockDeviceMappings[].Ebs.Iops=
EC2.Instance.BlockDeviceMappings[].Ebs.KmsKeyId=
EC2.Instance.BlockDeviceMappings[].Ebs.SnapshotId=
EC2.Instance.BlockDeviceMappings[].Ebs.VolumeSize=
EC2.Instance.BlockDeviceMappings[].Ebs.VolumeType=
EC2.Instance.BlockDeviceMappings[].NoDevice=
EC2.Instance.BlockDeviceMappings[].VirtualName=
EC2.Instance.CpuOptions.CoreCount=
EC2.Instance.CpuOptions.ThreadsPerCore=
EC2.Instance.DisableApiTermination=
EC2.Instance.EbsOptimized=
EC2.Instance.IamInstanceProfile=
EC2.Instance.ImageId=
EC2.Instance.InstanceId=IDENTIFIER_OUTPUT
EC2.Instance.InstanceInitiatedShutdownBehavior=
EC2.Instance.InstanceType=
EC2.Instance.KeyName=
EC2.Instance.MetadataOptions.HttpEndpoint=
EC2.Instance.MetadataOptions.HttpProtocolIpv6=
EC2.Instance.MetadataOptions.HttpPutResponseHopLimit=
EC2.Instance.MetadataOptions.HttpTokens=
EC2.Instance.MetadataOptions.InstanceMetadataTags=
EC2.Instance.Monitoring=
EC2.Instance.NetworkInterfaces[].AssociatePublicIpAddress=
EC2.Instance.NetworkInterfaces[].DeleteOnTermination=
EC2.Instance.NetworkInterfaces[].Description=
EC2.Instance.NetworkInterfaces[].DeviceIndex=
EC2.Instance.NetworkInterfaces[].GroupSet=
EC2.Instance.NetworkInterfaces[].NetworkInterfaceId=
EC2.Instance.NetworkInterfaces[].PrivateIpAddress=
EC2.Instance.NetworkInterfaces[].PrivateIpAddresses[].Primary=
EC2.Instance.NetworkInterfaces[].PrivateIpAddresses[].PrivateIpAddress=
EC2.Instance.NetworkInterfaces[].SecondaryPrivateIpAddressCount=
EC2.Instance.NetworkInterfaces[].SubnetId=
EC2.Instance.PrivateDnsNameOptions.EnableResourceNameDnsAAAARecord=
EC2.Instance.PrivateDnsNameOptions.EnableResourceNameDnsARecord=
EC2.Instance.PrivateDnsNameOptions.HostnameType=
EC2.Instance.PrivateIpAddress=
EC2.Instance.PropagateTagsToVolumeOnCreation=
EC2.Instance.SecurityGroupIds=
EC2.Instance.SourceDestCheck=
EC2.Instance.SubnetId=
EC2.Instance.Tags[].Key=
EC2.Instance.Tags[].Value=
EC2.Instance.Tenancy=
EC2.Instance.UserData=
