EC2.FlowLog.DeliverCrossAccountRole=
EC2.FlowLog.DeliverLogsPermissionArn=
EC2.FlowLog.DestinationOptions.FileFormat=
EC2.FlowLog.DestinationOptions.HiveCompatiblePartitions=
EC2.FlowLog.DestinationOptions.PerHourPartition=
EC2.FlowLog.LogDestination=
EC2.FlowLog.LogDestinationType=
EC2.FlowLog.LogFormat=
EC2.FlowLog.LogGroupName=
EC2.FlowLog.MaxAggregationInterval=
EC2.FlowLog.ResourceId=
EC2.FlowLog.ResourceType=
EC2.FlowLog.TagFieldSpecifications[].ResourceType=
EC2.FlowLog.TagFieldSpecifications[].TagKeys=
EC2.FlowLog.Tags[].Key=
EC2.FlowLog.Tags[].Value=
EC2.FlowLog.TrafficType=
