EC2.LaunchTemplate.LaunchTemplateData.BlockDeviceMappings[].DeviceName=
EC2.LaunchTemplate.LaunchTemplateData.BlockDeviceMappings[].Ebs.DeleteOnTermination=
EC2.LaunchTemplate.LaunchTemplateData.BlockDeviceMappings[].Ebs.EbsCardIndex=
EC2.LaunchTemplate.LaunchTemplateData.BlockDeviceMappings[].Ebs.Encrypted=
EC2.LaunchTemplate.LaunchTemplateData.BlockDeviceMappings[].Ebs.Iops=
EC2.LaunchTemplate.LaunchTemplateData.BlockDeviceMappings[].Ebs.KmsKeyId=
EC2.LaunchTemplate.LaunchTemplateData.BlockDeviceMappings[].Ebs.SnapshotId=
EC2.LaunchTemplate.LaunchTemplateData.BlockDeviceMappings[].Ebs.Throughput=
EC2.LaunchTemplate.LaunchTemplateData.BlockDeviceMappings[].Ebs.VolumeInitializationRate=
EC2.LaunchTemplate.LaunchTemplateData.BlockDeviceMappings[].Ebs.VolumeSize=
EC2.LaunchTemplate.LaunchTemplateData.BlockDeviceMappings[].Ebs.VolumeType=
EC2.LaunchTemplate.LaunchTemplateData.BlockDeviceMappings[].NoDevice=
EC2.LaunchTemplate.LaunchTemplateData.BlockDeviceMappings[].VirtualName=
EC2.LaunchTemplate.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationPreference=
EC2.LaunchTemplate.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationId=
EC2.LaunchTemplate.LaunchTemplateData.CapacityReservationSpecification.CapacityReservationTarget.CapacityReservationResourceGroupArn=
EC2.LaunchTemplate.LaunchTemplateData.CpuOptions.AmdSevSnp=
EC2.LaunchTemplate.LaunchTemplateData.CpuOptions.CoreCount=
EC2.LaunchTemplate.LaunchTemplateData.CpuOptions.NestedVirtualization=
EC2.LaunchTemplate.LaunchTemplateData.CpuOptions.ThreadsPerCore=
EC2.LaunchTemplate.LaunchTemplateData.CreditSpecification.CpuCredits=
EC2.LaunchTemplate.LaunchTemplateData.DisableApiStop=
EC2.LaunchTemplate.LaunchTemplateData.DisableApiTermination=
EC2.LaunchTemplate.LaunchTemplateData.EbsOptimized=
EC2.LaunchTemplate.LaunchTemplateData.EnclaveOptions.Enabled=
EC2.LaunchTemplate.LaunchTemplateData.HibernationOptions.Configured=
EC2.LaunchTemplate.LaunchTemplateData.IamInstanceProfile.Arn=
EC2.LaunchTemplate.LaunchTemplateData.IamInstanceProfile.Name=
EC2.LaunchTemplate.LaunchTemplateData.ImageId=
EC2.LaunchTemplate.LaunchTemplateData.InstanceInitiatedShutdownBehavior=
EC2.LaunchTemplate.LaunchTemplateData.InstanceMarketOptions.MarketType=
EC2.LaunchTemplate.LaunchTemplateData.InstanceMarketOptions.SpotOptions.BlockDurationMinutes=
EC2.LaunchTemplate.LaunchTemplateData.InstanceMarketOptions.SpotOptions.InstanceInterruptionBehavior=
EC2.LaunchTemplate.LaunchTemplateData.InstanceMarketOptions.SpotOptions.MaxPrice=
EC2.LaunchTemplate.LaunchTemplateData.InstanceMarketOptions.SpotOptions.SpotInstanceType=
EC2.LaunchTemplate.LaunchTemplateData.InstanceMarketOptions.SpotOptions.ValidUntil=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.AcceleratorCount.Max=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.AcceleratorCount.Min=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.AcceleratorManufacturers[]=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.AcceleratorNames[]=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.AcceleratorTotalMemoryMiB.Max=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.AcceleratorTotalMemoryMiB.Min=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.AcceleratorTypes[]=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.AllowedInstanceTypes[]=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.BareMetal=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.BaselineEbsBandwidthMbps.Max=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.BaselineEbsBandwidthMbps.Min=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.BaselinePerformanceFactors.Cpu.References[].InstanceFamily=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.BurstablePerformance=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.CpuManufacturers[]=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.ExcludedInstanceTypes[]=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.InstanceGenerations[]=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.LocalStorage=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.LocalStorageTypes[]=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.MemoryGiBPerVCpu.Max=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.MemoryGiBPerVCpu.Min=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.MemoryMiB.Max=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.MemoryMiB.Min=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.NetworkBandwidthGbps.Max=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.NetworkBandwidthGbps.Min=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.NetworkInterfaceCount.Max=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.NetworkInterfaceCount.Min=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.RequireHibernateSupport=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.TotalLocalStorageGB.Max=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.TotalLocalStorageGB.Min=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.VCpuCount.Max=
EC2.LaunchTemplate.LaunchTemplateData.InstanceRequirements.VCpuCount.Min=
EC2.LaunchTemplate.LaunchTemplateData.InstanceType=
EC2.LaunchTemplate.LaunchTemplateData.KernelId=
EC2.LaunchTemplate.LaunchTemplateData.KeyName=
EC2.LaunchTemplate.LaunchTemplateData.LicenseSpecifications[].LicenseConfigurationArn=
EC2.LaunchTemplate.LaunchTemplateData.MaintenanceOptions.AutoRecovery=
EC2.LaunchTemplate.LaunchTemplateData.MetadataOptions.HttpEndpoint=
EC2.LaunchTemplate.LaunchTemplateData.MetadataOptions.HttpProtocolIpv6=
EC2.LaunchTemplate.LaunchTemplateData.MetadataOptions.HttpPutResponseHopLimit=
EC2.LaunchTemplate.LaunchTemplateData.MetadataOptions.HttpTokens=
EC2.LaunchTemplate.LaunchTemplateData.MetadataOptions.InstanceMetadataTags=
EC2.LaunchTemplate.LaunchTemplateData.Monitoring.Enabled=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].AssociateCarrierIpAddress=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].AssociatePublicIpAddress=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].ConnectionTrackingSpecification.TcpEstablishedTimeout=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].ConnectionTrackingSpecification.UdpStreamTimeout=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].ConnectionTrackingSpecification.UdpTimeout=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].DeleteOnTermination=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].Description=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].DeviceIndex=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].EnaQueueCount=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].EnaSrdSpecification.EnaSrdEnabled=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].EnaSrdSpecification.EnaSrdUdpSpecification.EnaSrdUdpEnabled=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].Groups[]=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].InterfaceType=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].Ipv4PrefixCount=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].Ipv4Prefixes[].Ipv4Prefix=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].Ipv6AddressCount=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].Ipv6Addresses[].Ipv6Address=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].Ipv6PrefixCount=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].Ipv6Prefixes[].Ipv6Prefix=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].NetworkCardIndex=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].NetworkInterfaceId=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].PrimaryIpv6=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].PrivateIpAddress=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].PrivateIpAddresses[].Primary=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].PrivateIpAddresses[].PrivateIpAddress=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].SecondaryPrivateIpAddressCount=
EC2.LaunchTemplate.LaunchTemplateData.NetworkInterfaces[].SubnetId=
EC2.LaunchTemplate.LaunchTemplateData.NetworkPerformanceOptions.BandwidthWeighting=
EC2.LaunchTemplate.LaunchTemplateData.Placement.Affinity=
EC2.LaunchTemplate.LaunchTemplateData.Placement.AvailabilityZone=
EC2.LaunchTemplate.LaunchTemplateData.Placement.GroupId=
EC2.LaunchTemplate.LaunchTemplateData.Placement.GroupName=
EC2.LaunchTemplate.LaunchTemplateData.Placement.HostId=
EC2.LaunchTemplate.LaunchTemplateData.Placement.HostResourceGroupArn=
EC2.LaunchTemplate.LaunchTemplateData.Placement.PartitionNumber=
EC2.LaunchTemplate.LaunchTemplateData.Placement.SpreadDomain=
EC2.LaunchTemplate.LaunchTemplateData.Placement.Tenancy=
EC2.LaunchTemplate.LaunchTemplateData.PrivateDnsNameOptions.EnableResourceNameDnsAAAARecord=
EC2.LaunchTemplate.LaunchTemplateData.PrivateDnsNameOptions.EnableResourceNameDnsARecord=
EC2.LaunchTemplate.LaunchTemplateData.PrivateDnsNameOptions.HostnameType=
EC2.LaunchTemplate.LaunchTemplateData.RamDiskId=
EC2.LaunchTemplate.LaunchTemplateData.SecurityGroupIds[]=
EC2.LaunchTemplate.LaunchTemplateData.SecurityGroups[]=
EC2.LaunchTemplate.LaunchTemplateData.TagSpecifications[].ResourceType=
EC2.LaunchTemplate.LaunchTemplateData.TagSpecifications[].Tags[].Key=
EC2.LaunchTemplate.LaunchTemplateData.TagSpecifications[].Tags[].Value=
EC2.LaunchTemplate.LaunchTemplateData.UserData=
EC2.LaunchTemplate.LaunchTemplateName=
EC2.LaunchTemplate.TagSpecifications[].ResourceType=
EC2.LaunchTemplate.TagSpecifications[].Tags[].Key=
EC2.LaunchTemplate.TagSpecifications[].Tags[].Value=
EC2.LaunchTemplate.VersionDescription=
