EC2.SecurityGroupEgress.CidrIp=
EC2.SecurityGroupEgress.CidrIpv6=
EC2.SecurityGroupEgress.Description=
EC2.SecurityGroupEgress.DestinationPrefixListId=
EC2.SecurityGroupEgress.DestinationSecurityGroupId=
EC2.SecurityGroupEgress.FromPort=
EC2.SecurityGroupEgress.GroupId=
EC2.SecurityGroupEgress.IpProtocol=
EC2.SecurityGroupEgress.ToPort=
