EC2.NatGateway.AllocationId=
EC2.NatGateway.ConnectivityType=
EC2.NatGateway.MaxDrainDurationSeconds=
EC2.NatGateway.NatGatewayId=IDENTIFIER_OUTPUT
EC2.NatGateway.PrivateIpAddress=
EC2.NatGateway.SecondaryAllocationIds=
EC2.NatGateway.SecondaryPrivateIpAddressCount=
EC2.NatGateway.SecondaryPrivateIpAddresses=
EC2.NatGateway.SubnetId=
EC2.NatGateway.Tags[].Key=
EC2.NatGateway.Tags[].Value=
