EC2.VPCBlockPublicAccessExclusion.ExclusionId=IDENTIFIER_OUTPUT
EC2.VPCBlockPublicAccessExclusion.InternetGatewayExclusionMode=
EC2.VPCBlockPublicAccessExclusion.VpcId=
EC2.VPCBlockPublicAccessExclusion.SubnetId=
EC2.VPCBlockPublicAccessExclusion.Tags[].Key=
EC2.VPCBlockPublicAccessExclusion.Tags[].Value=
