EC2.Subnet.AvailabilityZone=
EC2.Subnet.CidrBlock=
EC2.Subnet.MapPublicIpOnLaunch=
EC2.Subnet.PrivateDnsNameOptionsOnLaunch.EnableResourceNameDnsAAAARecord=
EC2.Subnet.PrivateDnsNameOptionsOnLaunch.EnableResourceNameDnsARecord=
EC2.Subnet.PrivateDnsNameOptionsOnLaunch.HostnameType=
EC2.Subnet.Tags[].Key=
EC2.Subnet.Tags[].Value=
EC2.Subnet.VpcId=
