ECR.Repository.EmptyOnDelete=
ECR.Repository.EncryptionConfiguration.EncryptionType=
ECR.Repository.EncryptionConfiguration.KmsKey=
ECR.Repository.ImageScanningConfiguration.ScanOnPush=
ECR.Repository.ImageTagMutability=
ECR.Repository.ImageTagMutabilityExclusionFilters[].ImageTagMutabilityExclusionFilterType=
ECR.Repository.ImageTagMutabilityExclusionFilters[].ImageTagMutabilityExclusionFilterValue=
ECR.Repository.LifecyclePolicy=
ECR.Repository.RepositoryName=
ECR.Repository.RepositoryPolicyText=
ECR.Repository.Tags[].Key=
ECR.Repository.Tags[].Value=
