ECS.Cluster.CapacityProviders[]=
ECS.Cluster.ClusterName=
ECS.Cluster.ClusterSettings[].Name=
ECS.Cluster.ClusterSettings[].Value=
ECS.Cluster.Configuration.ExecuteCommandConfiguration.KmsKeyId=
ECS.Cluster.Configuration.ExecuteCommandConfiguration.LogConfiguration.CloudWatchEncryptionEnabled=
ECS.Cluster.Configuration.ExecuteCommandConfiguration.LogConfiguration.CloudWatchLogGroupName=
ECS.Cluster.Configuration.ExecuteCommandConfiguration.LogConfiguration.S3BucketName=
ECS.Cluster.Configuration.ExecuteCommandConfiguration.LogConfiguration.S3EncryptionEnabled=
ECS.Cluster.Configuration.ExecuteCommandConfiguration.LogConfiguration.S3KeyPrefix=
ECS.Cluster.Configuration.ExecuteCommandConfiguration.Logging=
ECS.Cluster.Configuration.ManagedStorageConfiguration.FargateEphemeralStorageKmsKeyId=
ECS.Cluster.Configuration.ManagedStorageConfiguration.KmsKeyId=
ECS.Cluster.DefaultCapacityProviderStrategy[].Base=
ECS.Cluster.DefaultCapacityProviderStrategy[].CapacityProvider=
ECS.Cluster.DefaultCapacityProviderStrategy[].Weight=
ECS.Cluster.ServiceConnectDefaults.Namespace=
ECS.Cluster.Tags[].Key=
ECS.Cluster.Tags[].Value=
