ECS.CapacityProvider.AutoScalingGroupProvider.AutoScalingGroupArn=
ECS.CapacityProvider.AutoScalingGroupProvider.ManagedDraining=
ECS.CapacityProvider.AutoScalingGroupProvider.ManagedScaling.InstanceWarmupPeriod=
ECS.CapacityProvider.AutoScalingGroupProvider.ManagedScaling.MaximumScalingStepSize=
ECS.CapacityProvider.AutoScalingGroupProvider.ManagedScaling.MinimumScalingStepSize=
ECS.CapacityProvider.AutoScalingGroupProvider.ManagedScaling.Status=
ECS.CapacityProvider.AutoScalingGroupProvider.ManagedScaling.TargetCapacity=
ECS.CapacityProvider.AutoScalingGroupProvider.ManagedTerminationProtection=
ECS.CapacityProvider.ClusterName=
ECS.CapacityProvider.ManagedInstancesProvider.AutoRepairConfiguration.ActionsStatus=
ECS.CapacityProvider.ManagedInstancesProvider.InfrastructureOptimization.ScaleInAfter=
ECS.CapacityProvider.ManagedInstancesProvider.InfrastructureRoleArn=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityOptionType=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationGroupArn=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationPreference=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.Ec2InstanceProfileArn=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.FipsEnabled=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceMetadataTagsPropagation=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Max=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Min=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorManufacturers[]=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorNames[]=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Max=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Min=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTypes[]=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AllowedInstanceTypes[]=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BareMetal=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEbsBandwidthMbps.Max=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEbsBandwidthMbps.Min=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BurstablePerformance=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.CpuManufacturers[]=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.ExcludedInstanceTypes[]=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.InstanceGenerations[]=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorage=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorageTypes[]=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCpu.Max=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCpu.Min=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Max=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Min=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Max=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Min=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Max=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Min=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.RequireHibernateSupport=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Max=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Min=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCpuCount.Max=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCpuCount.Min=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration.UseLocalStorage=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.Monitoring=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.SecurityGroups[]=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.Subnets[]=
ECS.CapacityProvider.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration.StorageSizeGiB=
ECS.CapacityProvider.ManagedInstancesProvider.PropagateTags=
ECS.CapacityProvider.Name=
ECS.CapacityProvider.Tags[].Key=
ECS.CapacityProvider.Tags[].Value=
