ECS.ClusterCapacityProviderAssociations.CapacityProviders[]=
ECS.ClusterCapacityProviderAssociations.Cluster=
ECS.ClusterCapacityProviderAssociations.DefaultCapacityProviderStrategy[].Base=
ECS.ClusterCapacityProviderAssociations.DefaultCapacityProviderStrategy[].CapacityProvider=
ECS.ClusterCapacityProviderAssociations.DefaultCapacityProviderStrategy[].Weight=
