ECS.TaskDefinition.ContainerDefinitions=
ECS.TaskDefinition.Cpu=
ECS.TaskDefinition.EnableFaultInjection=
ECS.TaskDefinition.EphemeralStorage.SizeInGiB=
ECS.TaskDefinition.ExecutionRoleArn=
ECS.TaskDefinition.Family=
ECS.TaskDefinition.IpcMode=
ECS.TaskDefinition.Memory=
ECS.TaskDefinition.NetworkMode=
ECS.TaskDefinition.PidMode=
ECS.TaskDefinition.PlacementConstraints[].Expression=
ECS.TaskDefinition.PlacementConstraints[].Type=
ECS.TaskDefinition.ProxyConfiguration=
ECS.TaskDefinition.RequiresCompatibilities[]=
ECS.TaskDefinition.RuntimePlatform.CpuArchitecture=
ECS.TaskDefinition.RuntimePlatform.OperatingSystemFamily=
ECS.TaskDefinition.Tags[].Key=
ECS.TaskDefinition.Tags[].Value=
ECS.TaskDefinition.TaskRoleArn=
ECS.TaskDefinition.Volumes=
