Glue.Table.CatalogId=
Glue.Table.DatabaseName=
Glue.Table.Id=IDENTIFIER_OUTPUT
Glue.Table.TableInput.Description=
Glue.Table.TableInput.Name=
Glue.Table.TableInput.Owner=
Glue.Table.TableInput.Parameters=
Glue.Table.TableInput.PartitionKeys[].Comment=
Glue.Table.TableInput.PartitionKeys[].Name=
Glue.Table.TableInput.PartitionKeys[].Type=
Glue.Table.TableInput.Retention=
Glue.Table.TableInput.StorageDescriptor.BucketColumns=
Glue.Table.TableInput.StorageDescriptor.Columns[].Comment=
Glue.Table.TableInput.StorageDescriptor.Columns[].Name=
Glue.Table.TableInput.StorageDescriptor.Columns[].Type=
Glue.Table.TableInput.StorageDescriptor.Compressed=
Glue.Table.TableInput.StorageDescriptor.InputFormat=
Glue.Table.TableInput.StorageDescriptor.Location=
Glue.Table.TableInput.StorageDescriptor.NumberOfBuckets=
Glue.Table.TableInput.StorageDescriptor.OutputFormat=
Glue.Table.TableInput.StorageDescriptor.Parameters=
Glue.Table.TableInput.StorageDescriptor.SerdeInfo.Name=
Glue.Table.TableInput.StorageDescriptor.SerdeInfo.Parameters=
Glue.Table.TableInput.StorageDescriptor.SerdeInfo.SerializationLibrary=
Glue.Table.TableInput.StorageDescriptor.SortColumns[].Column=
Glue.Table.TableInput.StorageDescriptor.SortColumns[].SortOrder=
Glue.Table.TableInput.StorageDescriptor.StoredAsSubDirectories=
Glue.Table.TableInput.TableType=
