Glue.Job.Command.Name=
Glue.Job.Command.PythonVersion=
Glue.Job.Command.Runtime=
Glue.Job.Command.ScriptLocation=
Glue.Job.Connections.Connections=
Glue.Job.DefaultArguments=
Glue.Job.Description=
Glue.Job.ExecutionClass=
Glue.Job.ExecutionProperty.MaxConcurrentRuns=
Glue.Job.GlueVersion=
Glue.Job.JobMode=
Glue.Job.JobRunQueuingEnabled=
Glue.Job.MaintenanceWindow=
Glue.Job.MaxRetries=
Glue.Job.Name=
Glue.Job.NonOverridableArguments=
Glue.Job.NotificationProperty.NotifyDelayAfter=
Glue.Job.NumberOfWorkers=
Glue.Job.Role=
Glue.Job.SecurityConfiguration=
Glue.Job.Tags=
Glue.Job.Timeout=
Glue.Job.WorkerType=
