Glue.Catalog.CatalogId=IDENTIFIER_OUTPUT
Glue.Catalog.AllowFullTableExternalDataAccess=
Glue.Catalog.CatalogProperties.DataLakeAccessProperties.AllowFullTableExternalDataAccess=
Glue.Catalog.CatalogProperties.DataLakeAccessProperties.CatalogType=
Glue.Catalog.CatalogProperties.DataLakeAccessProperties.DataLakeAccess=
Glue.Catalog.CatalogProperties.DataLakeAccessProperties.DataTransferRole=
Glue.Catalog.CatalogProperties.DataLakeAccessProperties.KmsKey=
Glue.Catalog.CreateDatabaseDefaultPermissions=
Glue.Catalog.CreateTableDefaultPermissions=
Glue.Catalog.Description=
Glue.Catalog.FederatedCatalog.ConnectionName=
Glue.Catalog.FederatedCatalog.Identifier=
Glue.Catalog.Name=
Glue.Catalog.OverwriteChildResourcePermissionsWithDefault=
Glue.Catalog.Parameters=
Glue.Catalog.Tags[].Key=
Glue.Catalog.Tags[].Value=
Glue.Catalog.TargetRedshiftCatalog.CatalogArn=
