Glue.Database.CatalogId=
Glue.Database.DatabaseInput.Description=
Glue.Database.DatabaseInput.LocationUri=
Glue.Database.DatabaseInput.Name=
Glue.Database.DatabaseInput.Parameters=
Glue.Database.DatabaseName=
