Glue.Connection.CatalogId=
Glue.Connection.ConnectionInput.AuthenticationConfiguration.AuthenticationType=
Glue.Connection.ConnectionInput.AuthenticationConfiguration.KmsKeyArn=
Glue.Connection.ConnectionInput.AuthenticationConfiguration.SecretArn=
Glue.Connection.ConnectionInput.ConnectionProperties=
Glue.Connection.ConnectionInput.ConnectionType=
Glue.Connection.ConnectionInput.Description=
Glue.Connection.ConnectionInput.MatchCriteria=
Glue.Connection.ConnectionInput.Name=
Glue.Connection.ConnectionInput.PhysicalConnectionRequirements.AvailabilityZone=
Glue.Connection.ConnectionInput.PhysicalConnectionRequirements.SecurityGroupIdList=
Glue.Connection.ConnectionInput.PhysicalConnectionRequirements.SubnetId=
Glue.Connection.ConnectionInput.ValidateCredentials=
Glue.Connection.ConnectionInput.ValidateForComputeEnvironments=
Glue.Connection.Name=IDENTIFIER_OUTPUT
