IAM.User.UserName=
IAM.User.Groups=
IAM.User.LoginProfile.Password=
IAM.User.LoginProfile.PasswordResetRequired=
IAM.User.ManagedPolicyArns=
IAM.User.Path=
IAM.User.PermissionsBoundary=
IAM.User.Policies[].PolicyName=
IAM.User.Policies[].PolicyDocument=
IAM.User.Tags[].Key=
IAM.User.Tags[].Value=
