KMS.Key.BypassPolicyLockoutSafetyCheck=
KMS.Key.Description=
KMS.Key.EnableKeyRotation=
KMS.Key.Enabled=
KMS.Key.KeyId=IDENTIFIER_OUTPUT
KMS.Key.KeyPolicy=
KMS.Key.KeySpec=
KMS.Key.KeyUsage=
KMS.Key.MultiRegion=
KMS.Key.Origin=
KMS.Key.PendingWindowInDays=
KMS.Key.RotationPeriodInDays=
KMS.Key.Tags[].Key=
KMS.Key.Tags[].Value=
