LakeFormation.PrincipalPermissions.PrincipalIdentifier=IDENTIFIER_OUTPUT
LakeFormation.PrincipalPermissions.ResourceIdentifier=IDENTIFIER_OUTPUT
LakeFormation.PrincipalPermissions.Catalog=
LakeFormation.PrincipalPermissions.Permissions=
LakeFormation.PrincipalPermissions.PermissionsWithGrantOption=
LakeFormation.PrincipalPermissions.Principal=
LakeFormation.PrincipalPermissions.Principal.DataLakePrincipalIdentifier=
LakeFormation.PrincipalPermissions.Resource=
LakeFormation.PrincipalPermissions.Resource.Catalog=
LakeFormation.PrincipalPermissions.Resource.Database=
LakeFormation.PrincipalPermissions.Resource.Database.CatalogId=
LakeFormation.PrincipalPermissions.Resource.Database.Name=
LakeFormation.PrincipalPermissions.Resource.Table=
LakeFormation.PrincipalPermissions.Resource.Table.CatalogId=
LakeFormation.PrincipalPermissions.Resource.Table.DatabaseName=
LakeFormation.PrincipalPermissions.Resource.Table.Name=
LakeFormation.PrincipalPermissions.Resource.Table.TableWildcard=
LakeFormation.PrincipalPermissions.Resource.TableWithColumns=
LakeFormation.PrincipalPermissions.Resource.TableWithColumns.CatalogId=
LakeFormation.PrincipalPermissions.Resource.TableWithColumns.DatabaseName=
LakeFormation.PrincipalPermissions.Resource.TableWithColumns.Name=
LakeFormation.PrincipalPermissions.Resource.TableWithColumns.ColumnNames=
LakeFormation.PrincipalPermissions.Resource.TableWithColumns.ColumnWildcard=
LakeFormation.PrincipalPermissions.Resource.TableWithColumns.ColumnWildcard.ExcludedColumnNames=
