Lambda.EventSourceMapping.BatchSize=
Lambda.EventSourceMapping.BisectBatchOnFunctionError=
Lambda.EventSourceMapping.DestinationConfig.OnFailure.Destination=
Lambda.EventSourceMapping.Enabled=
Lambda.EventSourceMapping.EventSourceArn=
Lambda.EventSourceMapping.FilterCriteria.Filters[].Pattern=
Lambda.EventSourceMapping.FunctionName=
Lambda.EventSourceMapping.FunctionResponseTypes=
Lambda.EventSourceMapping.KmsKeyArn=
Lambda.EventSourceMapping.LoggingConfig.SystemLogLevel=
Lambda.EventSourceMapping.MaximumBatchingWindowInSeconds=
Lambda.EventSourceMapping.MaximumRecordAgeInSeconds=
Lambda.EventSourceMapping.MaximumRetryAttempts=
Lambda.EventSourceMapping.ParallelizationFactor=
Lambda.EventSourceMapping.Queues=
Lambda.EventSourceMapping.ScalingConfig.MaximumConcurrency=
Lambda.EventSourceMapping.SourceAccessConfigurations[].Type=
Lambda.EventSourceMapping.SourceAccessConfigurations[].URI=
Lambda.EventSourceMapping.StartingPosition=
Lambda.EventSourceMapping.StartingPositionTimestamp=
Lambda.EventSourceMapping.Tags[].Key=
Lambda.EventSourceMapping.Tags[].Value=
Lambda.EventSourceMapping.Topics=
Lambda.EventSourceMapping.TumblingWindowInSeconds=
