Lambda.Permission.Action=
Lambda.Permission.EventSourceToken=
Lambda.Permission.FunctionName=
Lambda.Permission.FunctionUrlAuthType=
Lambda.Permission.InvokedViaFunctionUrl=
Lambda.Permission.Principal=
Lambda.Permission.PrincipalOrgID=
Lambda.Permission.SourceAccount=
Lambda.Permission.SourceArn=
