Logs.MetricFilter.FilterName=
Logs.MetricFilter.FilterPattern=
Logs.MetricFilter.LogGroupName=
Logs.MetricFilter.MetricTransformations[].DefaultValue=
Logs.MetricFilter.MetricTransformations[].Dimensions[].Key=
Logs.MetricFilter.MetricTransformations[].Dimensions[].Value=
Logs.MetricFilter.MetricTransformations[].MetricName=
Logs.MetricFilter.MetricTransformations[].MetricNamespace=
Logs.MetricFilter.MetricTransformations[].MetricValue=
Logs.MetricFilter.MetricTransformations[].Unit=
