NetworkFirewall.RuleGroup.Capacity=
NetworkFirewall.RuleGroup.Description=
NetworkFirewall.RuleGroup.RuleGroup.ReferenceSets.IPSetReferences=
NetworkFirewall.RuleGroup.RuleGroup.RuleVariables.IPSets=
NetworkFirewall.RuleGroup.RuleGroup.RuleVariables.PortSets=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.RulesSourceList.GeneratedRulesType=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.RulesSourceList.TargetTypes=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.RulesSourceList.Targets=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.RulesString=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatefulRules[].Action=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatefulRules[].Header.Destination=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatefulRules[].Header.DestinationPort=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatefulRules[].Header.Direction=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatefulRules[].Header.Protocol=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatefulRules[].Header.Source=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatefulRules[].Header.SourcePort=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatefulRules[].RuleOptions[].Keyword=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatefulRules[].RuleOptions[].Settings=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatelessRulesAndCustomActions.CustomActions[].ActionDefinition.PublishMetricAction.Dimensions[].Value=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatelessRulesAndCustomActions.CustomActions[].ActionName=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules[].Priority=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules[].RuleDefinition.Actions=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules[].RuleDefinition.MatchAttributes.DestinationPorts[].FromPort=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules[].RuleDefinition.MatchAttributes.DestinationPorts[].ToPort=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules[].RuleDefinition.MatchAttributes.Destinations[].AddressDefinition=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules[].RuleDefinition.MatchAttributes.Protocols=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules[].RuleDefinition.MatchAttributes.SourcePorts[].FromPort=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules[].RuleDefinition.MatchAttributes.SourcePorts[].ToPort=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules[].RuleDefinition.MatchAttributes.Sources[].AddressDefinition=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules[].RuleDefinition.MatchAttributes.TCPFlags[].Flags=
NetworkFirewall.RuleGroup.RuleGroup.RulesSource.StatelessRulesAndCustomActions.StatelessRules[].RuleDefinition.MatchAttributes.TCPFlags[].Masks=
NetworkFirewall.RuleGroup.RuleGroup.StatefulRuleOptions.RuleOrder=
NetworkFirewall.RuleGroup.RuleGroupName=
NetworkFirewall.RuleGroup.SummaryConfiguration.RuleOptions=
NetworkFirewall.RuleGroup.Tags[].Key=
NetworkFirewall.RuleGroup.Tags[].Value=
NetworkFirewall.RuleGroup.Type=
