NetworkFirewall.LoggingConfiguration.EnableMonitoringDashboard=
NetworkFirewall.LoggingConfiguration.FirewallArn=
NetworkFirewall.LoggingConfiguration.FirewallName=
NetworkFirewall.LoggingConfiguration.LoggingConfiguration.LogDestinationConfigs[].LogDestination=
NetworkFirewall.LoggingConfiguration.LoggingConfiguration.LogDestinationConfigs[].LogDestinationType=
NetworkFirewall.LoggingConfiguration.LoggingConfiguration.LogDestinationConfigs[].LogType=
