NetworkFirewall.FirewallPolicy.Description=
NetworkFirewall.FirewallPolicy.FirewallPolicy.EnableTLSSessionHolding=
NetworkFirewall.FirewallPolicy.FirewallPolicy.PolicyVariables.RuleVariables=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatefulDefaultActions=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatefulEngineOptions.FlowTimeouts.TcpIdleTimeoutSeconds=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatefulEngineOptions.RuleOrder=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatefulEngineOptions.StreamExceptionPolicy=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatefulRuleGroupReferences[].DeepThreatInspection=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatefulRuleGroupReferences[].Override.Action=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatefulRuleGroupReferences[].Priority=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatefulRuleGroupReferences[].ResourceArn=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatelessCustomActions[].ActionDefinition.PublishMetricAction.Dimensions[].Value=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatelessCustomActions[].ActionName=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatelessDefaultActions=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatelessFragmentDefaultActions=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatelessRuleGroupReferences[].Priority=
NetworkFirewall.FirewallPolicy.FirewallPolicy.StatelessRuleGroupReferences[].ResourceArn=
NetworkFirewall.FirewallPolicy.FirewallPolicy.TLSInspectionConfigurationArn=
NetworkFirewall.FirewallPolicy.FirewallPolicyName=
NetworkFirewall.FirewallPolicy.Tags[].Key=
NetworkFirewall.FirewallPolicy.Tags[].Value=
