NetworkFirewall.Firewall.AvailabilityZoneChangeProtection=
NetworkFirewall.Firewall.AvailabilityZoneMappings[].AvailabilityZone=
NetworkFirewall.Firewall.DeleteProtection=
NetworkFirewall.Firewall.Description=
NetworkFirewall.Firewall.EnabledAnalysisTypes=
NetworkFirewall.Firewall.FirewallName=
NetworkFirewall.Firewall.FirewallPolicyArn=
NetworkFirewall.Firewall.FirewallPolicyChangeProtection=
NetworkFirewall.Firewall.SubnetChangeProtection=
NetworkFirewall.Firewall.SubnetMappings[].IPAddressType=
NetworkFirewall.Firewall.SubnetMappings[].SubnetId=
NetworkFirewall.Firewall.Tags[].Key=
NetworkFirewall.Firewall.Tags[].Value=
NetworkFirewall.Firewall.TransitGatewayId=
NetworkFirewall.Firewall.VpcId=
