Organizations.Policy.Id=IDENTIFIER_OUTPUT
Organizations.Policy.Name=
Organizations.Policy.Type=
Organizations.Policy.Content=
Organizations.Policy.Description=
Organizations.Policy.TargetIds=
Organizations.Policy.Tags[].Key=
Organizations.Policy.Tags[].Value=
