RDS.DBInstance.AdditionalStorageVolumes[].AllocatedStorage=
RDS.DBInstance.AdditionalStorageVolumes[].Iops=
RDS.DBInstance.AdditionalStorageVolumes[].MaxAllocatedStorage=
RDS.DBInstance.AdditionalStorageVolumes[].StorageThroughput=
RDS.DBInstance.AdditionalStorageVolumes[].StorageType=
RDS.DBInstance.AdditionalStorageVolumes[].VolumeName=
RDS.DBInstance.AllocatedStorage=
RDS.DBInstance.AllowMajorVersionUpgrade=
RDS.DBInstance.ApplyImmediately=
RDS.DBInstance.AssociatedRoles[].FeatureName=
RDS.DBInstance.AssociatedRoles[].RoleArn=
RDS.DBInstance.AutoMinorVersionUpgrade=
RDS.DBInstance.AutomaticBackupReplicationKmsKeyId=
RDS.DBInstance.AutomaticBackupReplicationRegion=
RDS.DBInstance.AutomaticBackupReplicationRetentionPeriod=
RDS.DBInstance.AvailabilityZone=
RDS.DBInstance.BackupRetentionPeriod=
RDS.DBInstance.BackupTarget=
RDS.DBInstance.CACertificateIdentifier=
RDS.DBInstance.CertificateRotationRestart=
RDS.DBInstance.CharacterSetName=
RDS.DBInstance.CopyTagsToSnapshot=
RDS.DBInstance.CustomIAMInstanceProfile=
RDS.DBInstance.DBClusterIdentifier=
RDS.DBInstance.DBClusterSnapshotIdentifier=
RDS.DBInstance.DBInstanceClass=
RDS.DBInstance.DBInstanceIdentifier=
RDS.DBInstance.DBName=
RDS.DBInstance.DBParameterGroupName=
RDS.DBInstance.DBSecurityGroups[]=
RDS.DBInstance.DBSnapshotIdentifier=
RDS.DBInstance.DBSubnetGroupName=
RDS.DBInstance.DBSystemId=
RDS.DBInstance.DatabaseInsightsMode=
RDS.DBInstance.DedicatedLogVolume=
RDS.DBInstance.DeleteAutomatedBackups=
RDS.DBInstance.DeletionProtection=
RDS.DBInstance.Domain=
RDS.DBInstance.DomainAuthSecretArn=
RDS.DBInstance.DomainDnsIps[]=
RDS.DBInstance.DomainFqdn=
RDS.DBInstance.DomainIAMRoleName=
RDS.DBInstance.DomainOu=
RDS.DBInstance.EnableCloudwatchLogsExports[]=
RDS.DBInstance.EnableIAMDatabaseAuthentication=
RDS.DBInstance.EnablePerformanceInsights=
RDS.DBInstance.Engine=
RDS.DBInstance.EngineLifecycleSupport=
RDS.DBInstance.EngineVersion=
RDS.DBInstance.Iops=
RDS.DBInstance.KmsKeyId=
RDS.DBInstance.LicenseModel=
RDS.DBInstance.ManageMasterUserPassword=
RDS.DBInstance.MasterUserAuthenticationType=
RDS.DBInstance.MasterUserPassword=
RDS.DBInstance.MasterUserSecret.KmsKeyId=
RDS.DBInstance.MasterUsername=
RDS.DBInstance.MaxAllocatedStorage=
RDS.DBInstance.MonitoringInterval=
RDS.DBInstance.MonitoringRoleArn=
RDS.DBInstance.MultiAZ=
RDS.DBInstance.NcharCharacterSetName=
RDS.DBInstance.NetworkType=
RDS.DBInstance.OptionGroupName=
RDS.DBInstance.PerformanceInsightsKMSKeyId=
RDS.DBInstance.PerformanceInsightsRetentionPeriod=
RDS.DBInstance.Port=
RDS.DBInstance.PreferredBackupWindow=
RDS.DBInstance.PreferredMaintenanceWindow=
RDS.DBInstance.ProcessorFeatures[].Name=
RDS.DBInstance.ProcessorFeatures[].Value=
RDS.DBInstance.PromotionTier=
RDS.DBInstance.PubliclyAccessible=
RDS.DBInstance.ReplicaMode=
RDS.DBInstance.RestoreTime=
RDS.DBInstance.SourceDBClusterIdentifier=
RDS.DBInstance.SourceDBInstanceAutomatedBackupsArn=
RDS.DBInstance.SourceDBInstanceIdentifier=
RDS.DBInstance.SourceDbiResourceId=
RDS.DBInstance.SourceRegion=
RDS.DBInstance.StorageEncrypted=
RDS.DBInstance.StorageThroughput=
RDS.DBInstance.StorageType=
RDS.DBInstance.Tags[].Key=
RDS.DBInstance.Tags[].Value=
RDS.DBInstance.Timezone=
RDS.DBInstance.UseDefaultProcessorFeatures=
RDS.DBInstance.UseLatestRestorableTime=
RDS.DBInstance.VPCSecurityGroups[]=
