RDS.DBProxy.Auth[].AuthScheme=
RDS.DBProxy.Auth[].ClientPasswordAuthType=
RDS.DBProxy.Auth[].Description=
RDS.DBProxy.Auth[].IAMAuth=
RDS.DBProxy.Auth[].SecretArn=
RDS.DBProxy.DBProxyName=
RDS.DBProxy.DebugLogging=
RDS.DBProxy.DefaultAuthScheme=
RDS.DBProxy.EndpointNetworkType=
RDS.DBProxy.EngineFamily=
RDS.DBProxy.IdleClientTimeout=
RDS.DBProxy.RequireTLS=
RDS.DBProxy.RoleArn=
RDS.DBProxy.Tags[].Key=
RDS.DBProxy.Tags[].Value=
RDS.DBProxy.TargetConnectionNetworkType=
RDS.DBProxy.VpcSecurityGroupIds[]=
RDS.DBProxy.VpcSubnetIds[]=
