Route53.RecordSet.AliasTarget.DNSName=
Route53.RecordSet.AliasTarget.EvaluateTargetHealth=
Route53.RecordSet.AliasTarget.HostedZoneId=
Route53.RecordSet.Comment=
Route53.RecordSet.Failover=
Route53.RecordSet.GeoLocation.ContinentCode=
Route53.RecordSet.GeoLocation.CountryCode=
Route53.RecordSet.GeoLocation.SubdivisionCode=
Route53.RecordSet.HealthCheckId=
Route53.RecordSet.HostedZoneId=
Route53.RecordSet.HostedZoneName=
Route53.RecordSet.Id=IDENTIFIER_OUTPUT
Route53.RecordSet.MultiValueAnswer=
Route53.RecordSet.Name=
Route53.RecordSet.Region=
Route53.RecordSet.ResourceRecords=
Route53.RecordSet.SetIdentifier=
Route53.RecordSet.TTL=
Route53.RecordSet.Type=
Route53.RecordSet.Weight=
