Route53Resolver.ResolverRule.DomainName=
Route53Resolver.ResolverRule.Name=
Route53Resolver.ResolverRule.ResolverEndpointId=
Route53Resolver.ResolverRule.RuleType=
Route53Resolver.ResolverRule.Tags[].Key=
Route53Resolver.ResolverRule.Tags[].Value=
Route53Resolver.ResolverRule.TargetIps[].Ip=
Route53Resolver.ResolverRule.TargetIps[].Port=
Route53Resolver.ResolverRule.TargetIps[].Protocol=
Route53Resolver.ResolverRule.TargetIps[].ServerNameIndication=
