Route53Resolver.ResolverEndpoint.Direction=
Route53Resolver.ResolverEndpoint.IpAddresses[].Ip=
Route53Resolver.ResolverEndpoint.IpAddresses[].SubnetId=
Route53Resolver.ResolverEndpoint.Name=
Route53Resolver.ResolverEndpoint.Protocols=
Route53Resolver.ResolverEndpoint.ResolverEndpointId=IDENTIFIER_OUTPUT
Route53Resolver.ResolverEndpoint.ResolverEndpointType=
Route53Resolver.ResolverEndpoint.SecurityGroupIds=
Route53Resolver.ResolverEndpoint.Tags[].Key=
Route53Resolver.ResolverEndpoint.Tags[].Value=
