Route53.HostedZone.HostedZoneConfig.Comment=
Route53.HostedZone.HostedZoneTags[].Key=
Route53.HostedZone.HostedZoneTags[].Value=
Route53.HostedZone.Name=
Route53.HostedZone.QueryLoggingConfig.CloudWatchLogsLogGroupArn=
Route53.HostedZone.VPCs[].VPCId=
Route53.HostedZone.VPCs[].VPCRegion=
