Route53Resolver.ResolverRuleAssociation.Name=
Route53Resolver.ResolverRuleAssociation.ResolverRuleAssociationId=IDENTIFIER_OUTPUT
Route53Resolver.ResolverRuleAssociation.ResolverRuleId=
Route53Resolver.ResolverRuleAssociation.VPCId=
