SageMaker.Space.DomainId=
SageMaker.Space.OwnershipSettings.OwnerUserProfileName=
SageMaker.Space.SpaceDisplayName=
SageMaker.Space.SpaceName=
SageMaker.Space.SpaceSettings.AppType=
SageMaker.Space.SpaceSettings.CodeEditorAppSettings.AppLifecycleManagement.IdleSettings.IdleTimeoutInMinutes=
SageMaker.Space.SpaceSettings.CodeEditorAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.Space.SpaceSettings.CodeEditorAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.Space.SpaceSettings.CodeEditorAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.Space.SpaceSettings.CodeEditorAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.Space.SpaceSettings.CustomFileSystems[].EFSFileSystem.FileSystemId=
SageMaker.Space.SpaceSettings.CustomFileSystems[].FSxLustreFileSystem.FileSystemId=
SageMaker.Space.SpaceSettings.CustomFileSystems[].S3FileSystem.S3Uri=
SageMaker.Space.SpaceSettings.JupyterLabAppSettings.AppLifecycleManagement.IdleSettings.IdleTimeoutInMinutes=
SageMaker.Space.SpaceSettings.JupyterLabAppSettings.CodeRepositories[].RepositoryUrl=
SageMaker.Space.SpaceSettings.JupyterLabAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.Space.SpaceSettings.JupyterLabAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.Space.SpaceSettings.JupyterLabAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.Space.SpaceSettings.JupyterLabAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.Space.SpaceSettings.JupyterServerAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.Space.SpaceSettings.JupyterServerAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.Space.SpaceSettings.JupyterServerAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.Space.SpaceSettings.JupyterServerAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.Space.SpaceSettings.JupyterServerAppSettings.LifecycleConfigArns[]=
SageMaker.Space.SpaceSettings.KernelGatewayAppSettings.CustomImages[].AppImageConfigName=
SageMaker.Space.SpaceSettings.KernelGatewayAppSettings.CustomImages[].ImageName=
SageMaker.Space.SpaceSettings.KernelGatewayAppSettings.CustomImages[].ImageVersionNumber=
SageMaker.Space.SpaceSettings.KernelGatewayAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.Space.SpaceSettings.KernelGatewayAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.Space.SpaceSettings.KernelGatewayAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.Space.SpaceSettings.KernelGatewayAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.Space.SpaceSettings.KernelGatewayAppSettings.LifecycleConfigArns[]=
SageMaker.Space.SpaceSettings.RemoteAccess=
SageMaker.Space.SpaceSettings.SpaceManagedResources=
SageMaker.Space.SpaceSettings.SpaceStorageSettings.EbsStorageSettings.EbsVolumeSizeInGb=
SageMaker.Space.SpaceSharingSettings.SharingType=
SageMaker.Space.Tags[].Key=
SageMaker.Space.Tags[].Value=
