SageMaker.UserProfile.DomainId=
SageMaker.UserProfile.SingleSignOnUserIdentifier=
SageMaker.UserProfile.SingleSignOnUserValue=
SageMaker.UserProfile.Tags[].Key=
SageMaker.UserProfile.Tags[].Value=
SageMaker.UserProfile.UserProfileName=
SageMaker.UserProfile.UserSettings.AutoMountHomeEFS=
SageMaker.UserProfile.UserSettings.CodeEditorAppSettings.AppLifecycleManagement.IdleSettings.IdleTimeoutInMinutes=
SageMaker.UserProfile.UserSettings.CodeEditorAppSettings.AppLifecycleManagement.IdleSettings.LifecycleManagement=
SageMaker.UserProfile.UserSettings.CodeEditorAppSettings.AppLifecycleManagement.IdleSettings.MaxIdleTimeoutInMinutes=
SageMaker.UserProfile.UserSettings.CodeEditorAppSettings.AppLifecycleManagement.IdleSettings.MinIdleTimeoutInMinutes=
SageMaker.UserProfile.UserSettings.CodeEditorAppSettings.BuiltInLifecycleConfigArn=
SageMaker.UserProfile.UserSettings.CodeEditorAppSettings.CustomImages[].AppImageConfigName=
SageMaker.UserProfile.UserSettings.CodeEditorAppSettings.CustomImages[].ImageName=
SageMaker.UserProfile.UserSettings.CodeEditorAppSettings.CustomImages[].ImageVersionNumber=
SageMaker.UserProfile.UserSettings.CodeEditorAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.UserProfile.UserSettings.CodeEditorAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.UserProfile.UserSettings.CodeEditorAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.UserProfile.UserSettings.CodeEditorAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.UserProfile.UserSettings.CodeEditorAppSettings.LifecycleConfigArns[]=
SageMaker.UserProfile.UserSettings.CustomFileSystemConfigs[].EFSFileSystemConfig.FileSystemId=
SageMaker.UserProfile.UserSettings.CustomFileSystemConfigs[].EFSFileSystemConfig.FileSystemPath=
SageMaker.UserProfile.UserSettings.CustomFileSystemConfigs[].FSxLustreFileSystemConfig.FileSystemId=
SageMaker.UserProfile.UserSettings.CustomFileSystemConfigs[].FSxLustreFileSystemConfig.FileSystemPath=
SageMaker.UserProfile.UserSettings.CustomFileSystemConfigs[].S3FileSystemConfig.MountPath=
SageMaker.UserProfile.UserSettings.CustomFileSystemConfigs[].S3FileSystemConfig.S3Uri=
SageMaker.UserProfile.UserSettings.CustomPosixUserConfig.Gid=
SageMaker.UserProfile.UserSettings.CustomPosixUserConfig.Uid=
SageMaker.UserProfile.UserSettings.DefaultLandingUri=
SageMaker.UserProfile.UserSettings.ExecutionRole=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.AppLifecycleManagement.IdleSettings.IdleTimeoutInMinutes=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.AppLifecycleManagement.IdleSettings.LifecycleManagement=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.AppLifecycleManagement.IdleSettings.MaxIdleTimeoutInMinutes=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.AppLifecycleManagement.IdleSettings.MinIdleTimeoutInMinutes=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.BuiltInLifecycleConfigArn=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.CodeRepositories[].RepositoryUrl=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.CustomImages[].AppImageConfigName=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.CustomImages[].ImageName=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.CustomImages[].ImageVersionNumber=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.EmrSettings.AssumableRoleArns[]=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.EmrSettings.ExecutionRoleArns[]=
SageMaker.UserProfile.UserSettings.JupyterLabAppSettings.LifecycleConfigArns[]=
SageMaker.UserProfile.UserSettings.JupyterServerAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.UserProfile.UserSettings.JupyterServerAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.UserProfile.UserSettings.JupyterServerAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.UserProfile.UserSettings.JupyterServerAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.UserProfile.UserSettings.JupyterServerAppSettings.LifecycleConfigArns[]=
SageMaker.UserProfile.UserSettings.KernelGatewayAppSettings.CustomImages[].AppImageConfigName=
SageMaker.UserProfile.UserSettings.KernelGatewayAppSettings.CustomImages[].ImageName=
SageMaker.UserProfile.UserSettings.KernelGatewayAppSettings.CustomImages[].ImageVersionNumber=
SageMaker.UserProfile.UserSettings.KernelGatewayAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.UserProfile.UserSettings.KernelGatewayAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.UserProfile.UserSettings.KernelGatewayAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.UserProfile.UserSettings.KernelGatewayAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.UserProfile.UserSettings.KernelGatewayAppSettings.LifecycleConfigArns[]=
SageMaker.UserProfile.UserSettings.RStudioServerProAppSettings.AccessStatus=
SageMaker.UserProfile.UserSettings.RStudioServerProAppSettings.UserGroup=
SageMaker.UserProfile.UserSettings.SecurityGroups[]=
SageMaker.UserProfile.UserSettings.SharingSettings.NotebookOutputOption=
SageMaker.UserProfile.UserSettings.SharingSettings.S3KmsKeyId=
SageMaker.UserProfile.UserSettings.SharingSettings.S3OutputPath=
SageMaker.UserProfile.UserSettings.SpaceStorageSettings.DefaultEbsStorageSettings.DefaultEbsVolumeSizeInGb=
SageMaker.UserProfile.UserSettings.SpaceStorageSettings.DefaultEbsStorageSettings.MaximumEbsVolumeSizeInGb=
SageMaker.UserProfile.UserSettings.StudioWebPortal=
SageMaker.UserProfile.UserSettings.StudioWebPortalSettings.HiddenAppTypes[]=
SageMaker.UserProfile.UserSettings.StudioWebPortalSettings.HiddenInstanceTypes[]=
SageMaker.UserProfile.UserSettings.StudioWebPortalSettings.HiddenMlTools[]=
SageMaker.UserProfile.UserSettings.StudioWebPortalSettings.HiddenSageMakerImageVersionAliases[].SageMakerImageName=
SageMaker.UserProfile.UserSettings.StudioWebPortalSettings.HiddenSageMakerImageVersionAliases[].VersionAliases[]=
