SageMaker.Domain.DomainId=IDENTIFIER_OUTPUT
SageMaker.Domain.AppNetworkAccessType=
SageMaker.Domain.AppSecurityGroupManagement=
SageMaker.Domain.AuthMode=
SageMaker.Domain.DefaultSpaceSettings.CustomFileSystemConfigs[].EFSFileSystemConfig.FileSystemId=
SageMaker.Domain.DefaultSpaceSettings.CustomFileSystemConfigs[].EFSFileSystemConfig.FileSystemPath=
SageMaker.Domain.DefaultSpaceSettings.CustomFileSystemConfigs[].FSxLustreFileSystemConfig.FileSystemId=
SageMaker.Domain.DefaultSpaceSettings.CustomFileSystemConfigs[].FSxLustreFileSystemConfig.FileSystemPath=
SageMaker.Domain.DefaultSpaceSettings.CustomFileSystemConfigs[].S3FileSystemConfig.MountPath=
SageMaker.Domain.DefaultSpaceSettings.CustomFileSystemConfigs[].S3FileSystemConfig.S3Uri=
SageMaker.Domain.DefaultSpaceSettings.CustomPosixUserConfig.Gid=
SageMaker.Domain.DefaultSpaceSettings.CustomPosixUserConfig.Uid=
SageMaker.Domain.DefaultSpaceSettings.ExecutionRole=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.AppLifecycleManagement.IdleSettings.IdleTimeoutInMinutes=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.AppLifecycleManagement.IdleSettings.LifecycleManagement=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.AppLifecycleManagement.IdleSettings.MaxIdleTimeoutInMinutes=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.AppLifecycleManagement.IdleSettings.MinIdleTimeoutInMinutes=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.BuiltInLifecycleConfigArn=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.CodeRepositories[].RepositoryUrl=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.CustomImages[].AppImageConfigName=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.CustomImages[].ImageName=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.CustomImages[].ImageVersionNumber=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.Domain.DefaultSpaceSettings.JupyterLabAppSettings.LifecycleConfigArns[]=
SageMaker.Domain.DefaultSpaceSettings.JupyterServerAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.Domain.DefaultSpaceSettings.JupyterServerAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.Domain.DefaultSpaceSettings.JupyterServerAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.Domain.DefaultSpaceSettings.JupyterServerAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.Domain.DefaultSpaceSettings.JupyterServerAppSettings.LifecycleConfigArns[]=
SageMaker.Domain.DefaultSpaceSettings.KernelGatewayAppSettings.CustomImages[].AppImageConfigName=
SageMaker.Domain.DefaultSpaceSettings.KernelGatewayAppSettings.CustomImages[].ImageName=
SageMaker.Domain.DefaultSpaceSettings.KernelGatewayAppSettings.CustomImages[].ImageVersionNumber=
SageMaker.Domain.DefaultSpaceSettings.KernelGatewayAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.Domain.DefaultSpaceSettings.KernelGatewayAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.Domain.DefaultSpaceSettings.KernelGatewayAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.Domain.DefaultSpaceSettings.KernelGatewayAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.Domain.DefaultSpaceSettings.KernelGatewayAppSettings.LifecycleConfigArns[]=
SageMaker.Domain.DefaultSpaceSettings.SecurityGroups[]=
SageMaker.Domain.DefaultSpaceSettings.SpaceStorageSettings.DefaultEbsStorageSettings.DefaultEbsVolumeSizeInGb=
SageMaker.Domain.DefaultSpaceSettings.SpaceStorageSettings.DefaultEbsStorageSettings.MaximumEbsVolumeSizeInGb=
SageMaker.Domain.DefaultUserSettings.AutoMountHomeEFS=
SageMaker.Domain.DefaultUserSettings.CodeEditorAppSettings.AppLifecycleManagement.IdleSettings.IdleTimeoutInMinutes=
SageMaker.Domain.DefaultUserSettings.CodeEditorAppSettings.AppLifecycleManagement.IdleSettings.LifecycleManagement=
SageMaker.Domain.DefaultUserSettings.CodeEditorAppSettings.AppLifecycleManagement.IdleSettings.MaxIdleTimeoutInMinutes=
SageMaker.Domain.DefaultUserSettings.CodeEditorAppSettings.AppLifecycleManagement.IdleSettings.MinIdleTimeoutInMinutes=
SageMaker.Domain.DefaultUserSettings.CodeEditorAppSettings.BuiltInLifecycleConfigArn=
SageMaker.Domain.DefaultUserSettings.CodeEditorAppSettings.CustomImages[].AppImageConfigName=
SageMaker.Domain.DefaultUserSettings.CodeEditorAppSettings.CustomImages[].ImageName=
SageMaker.Domain.DefaultUserSettings.CodeEditorAppSettings.CustomImages[].ImageVersionNumber=
SageMaker.Domain.DefaultUserSettings.CodeEditorAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.Domain.DefaultUserSettings.CodeEditorAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.Domain.DefaultUserSettings.CodeEditorAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.Domain.DefaultUserSettings.CodeEditorAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.Domain.DefaultUserSettings.CodeEditorAppSettings.LifecycleConfigArns[]=
SageMaker.Domain.DefaultUserSettings.CustomFileSystemConfigs[].EFSFileSystemConfig.FileSystemId=
SageMaker.Domain.DefaultUserSettings.CustomFileSystemConfigs[].EFSFileSystemConfig.FileSystemPath=
SageMaker.Domain.DefaultUserSettings.CustomFileSystemConfigs[].FSxLustreFileSystemConfig.FileSystemId=
SageMaker.Domain.DefaultUserSettings.CustomFileSystemConfigs[].FSxLustreFileSystemConfig.FileSystemPath=
SageMaker.Domain.DefaultUserSettings.CustomFileSystemConfigs[].S3FileSystemConfig.MountPath=
SageMaker.Domain.DefaultUserSettings.CustomFileSystemConfigs[].S3FileSystemConfig.S3Uri=
SageMaker.Domain.DefaultUserSettings.CustomPosixUserConfig.Gid=
SageMaker.Domain.DefaultUserSettings.CustomPosixUserConfig.Uid=
SageMaker.Domain.DefaultUserSettings.DefaultLandingUri=
SageMaker.Domain.DefaultUserSettings.ExecutionRole=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.AppLifecycleManagement.IdleSettings.IdleTimeoutInMinutes=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.AppLifecycleManagement.IdleSettings.LifecycleManagement=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.AppLifecycleManagement.IdleSettings.MaxIdleTimeoutInMinutes=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.AppLifecycleManagement.IdleSettings.MinIdleTimeoutInMinutes=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.BuiltInLifecycleConfigArn=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.CodeRepositories[].RepositoryUrl=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.CustomImages[].AppImageConfigName=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.CustomImages[].ImageName=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.CustomImages[].ImageVersionNumber=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.Domain.DefaultUserSettings.JupyterLabAppSettings.LifecycleConfigArns[]=
SageMaker.Domain.DefaultUserSettings.JupyterServerAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.Domain.DefaultUserSettings.JupyterServerAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.Domain.DefaultUserSettings.JupyterServerAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.Domain.DefaultUserSettings.JupyterServerAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.Domain.DefaultUserSettings.JupyterServerAppSettings.LifecycleConfigArns[]=
SageMaker.Domain.DefaultUserSettings.KernelGatewayAppSettings.CustomImages[].AppImageConfigName=
SageMaker.Domain.DefaultUserSettings.KernelGatewayAppSettings.CustomImages[].ImageName=
SageMaker.Domain.DefaultUserSettings.KernelGatewayAppSettings.CustomImages[].ImageVersionNumber=
SageMaker.Domain.DefaultUserSettings.KernelGatewayAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.Domain.DefaultUserSettings.KernelGatewayAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.Domain.DefaultUserSettings.KernelGatewayAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.Domain.DefaultUserSettings.KernelGatewayAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.Domain.DefaultUserSettings.KernelGatewayAppSettings.LifecycleConfigArns[]=
SageMaker.Domain.DefaultUserSettings.RSessionAppSettings.CustomImages[].AppImageConfigName=
SageMaker.Domain.DefaultUserSettings.RSessionAppSettings.CustomImages[].ImageName=
SageMaker.Domain.DefaultUserSettings.RSessionAppSettings.CustomImages[].ImageVersionNumber=
SageMaker.Domain.DefaultUserSettings.RSessionAppSettings.DefaultResourceSpec.InstanceType=
SageMaker.Domain.DefaultUserSettings.RSessionAppSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.Domain.DefaultUserSettings.RSessionAppSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.Domain.DefaultUserSettings.RSessionAppSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.Domain.DefaultUserSettings.RStudioServerProAppSettings.AccessStatus=
SageMaker.Domain.DefaultUserSettings.RStudioServerProAppSettings.UserGroup=
SageMaker.Domain.DefaultUserSettings.SecurityGroups[]=
SageMaker.Domain.DefaultUserSettings.SharingSettings.NotebookOutputOption=
SageMaker.Domain.DefaultUserSettings.SharingSettings.S3KmsKeyId=
SageMaker.Domain.DefaultUserSettings.SharingSettings.S3OutputPath=
SageMaker.Domain.DefaultUserSettings.SpaceStorageSettings.DefaultEbsStorageSettings.DefaultEbsVolumeSizeInGb=
SageMaker.Domain.DefaultUserSettings.SpaceStorageSettings.DefaultEbsStorageSettings.MaximumEbsVolumeSizeInGb=
SageMaker.Domain.DefaultUserSettings.StudioWebPortal=
SageMaker.Domain.DefaultUserSettings.StudioWebPortalSettings.HiddenAppTypes[]=
SageMaker.Domain.DefaultUserSettings.StudioWebPortalSettings.HiddenInstanceTypes[]=
SageMaker.Domain.DefaultUserSettings.StudioWebPortalSettings.HiddenMlTools[]=
SageMaker.Domain.DefaultUserSettings.StudioWebPortalSettings.HiddenSageMakerImageVersionAliases[].SageMakerImageName=
SageMaker.Domain.DefaultUserSettings.StudioWebPortalSettings.HiddenSageMakerImageVersionAliases[].VersionAliases[]=
SageMaker.Domain.DomainName=
SageMaker.Domain.DomainSettings.DockerSettings.EnableDockerAccess=
SageMaker.Domain.DomainSettings.DockerSettings.VpcOnlyTrustedAccounts[]=
SageMaker.Domain.DomainSettings.ExecutionRoleIdentityConfig=
SageMaker.Domain.DomainSettings.IpAddressType=
SageMaker.Domain.DomainSettings.RStudioServerProDomainSettings.DefaultResourceSpec.InstanceType=
SageMaker.Domain.DomainSettings.RStudioServerProDomainSettings.DefaultResourceSpec.LifecycleConfigArn=
SageMaker.Domain.DomainSettings.RStudioServerProDomainSettings.DefaultResourceSpec.SageMakerImageArn=
SageMaker.Domain.DomainSettings.RStudioServerProDomainSettings.DefaultResourceSpec.SageMakerImageVersionArn=
SageMaker.Domain.DomainSettings.RStudioServerProDomainSettings.DomainExecutionRoleArn=
SageMaker.Domain.DomainSettings.RStudioServerProDomainSettings.RStudioConnectUrl=
SageMaker.Domain.DomainSettings.RStudioServerProDomainSettings.RStudioPackageManagerUrl=
SageMaker.Domain.DomainSettings.SecurityGroupIds[]=
SageMaker.Domain.DomainSettings.UnifiedStudioSettings.DomainAccountId=
SageMaker.Domain.DomainSettings.UnifiedStudioSettings.DomainId=
SageMaker.Domain.DomainSettings.UnifiedStudioSettings.DomainRegion=
SageMaker.Domain.DomainSettings.UnifiedStudioSettings.EnvironmentId=
SageMaker.Domain.DomainSettings.UnifiedStudioSettings.ProjectId=
SageMaker.Domain.DomainSettings.UnifiedStudioSettings.ProjectS3Path=
SageMaker.Domain.DomainSettings.UnifiedStudioSettings.StudioWebPortalAccess=
SageMaker.Domain.KmsKeyId=
SageMaker.Domain.SubnetIds[]=
SageMaker.Domain.TagPropagation=
SageMaker.Domain.Tags[].Key=
SageMaker.Domain.Tags[].Value=
SageMaker.Domain.VpcId=
