SecretsManager.RotationSchedule.HostedRotationLambda.ExcludeCharacters=
SecretsManager.RotationSchedule.HostedRotationLambda.KmsKeyArn=
SecretsManager.RotationSchedule.HostedRotationLambda.MasterSecretArn=
SecretsManager.RotationSchedule.HostedRotationLambda.MasterSecretKmsKeyArn=
SecretsManager.RotationSchedule.HostedRotationLambda.RotationLambdaName=
SecretsManager.RotationSchedule.HostedRotationLambda.RotationType=
SecretsManager.RotationSchedule.HostedRotationLambda.Runtime=
SecretsManager.RotationSchedule.HostedRotationLambda.SuperuserSecretArn=
SecretsManager.RotationSchedule.HostedRotationLambda.SuperuserSecretKmsKeyArn=
SecretsManager.RotationSchedule.HostedRotationLambda.VpcSecurityGroupIds=
SecretsManager.RotationSchedule.HostedRotationLambda.VpcSubnetIds=
SecretsManager.RotationSchedule.RotateImmediatelyOnUpdate=
SecretsManager.RotationSchedule.RotationLambdaARN=
SecretsManager.RotationSchedule.RotationRules.AutomaticallyAfterDays=
SecretsManager.RotationSchedule.RotationRules.Duration=
SecretsManager.RotationSchedule.RotationRules.ScheduleExpression=
SecretsManager.RotationSchedule.SecretId=
