SNS.Topic.ArchivePolicy=
SNS.Topic.ContentBasedDeduplication=
SNS.Topic.DataProtectionPolicy=
SNS.Topic.DeliveryStatusLogging[].FailureFeedbackRoleArn=
SNS.Topic.DeliveryStatusLogging[].Protocol=
SNS.Topic.DeliveryStatusLogging[].SuccessFeedbackRoleArn=
SNS.Topic.DeliveryStatusLogging[].SuccessFeedbackSampleRate=
SNS.Topic.DisplayName=
SNS.Topic.FifoThroughputScope=
SNS.Topic.FifoTopic=
SNS.Topic.KmsMasterKeyId=
SNS.Topic.SignatureVersion=
SNS.Topic.Tags[].Key=
SNS.Topic.Tags[].Value=
SNS.Topic.TopicName=
SNS.Topic.TracingConfig=
