SQS.Queue.ContentBasedDeduplication=
SQS.Queue.DeduplicationScope=
SQS.Queue.DelaySeconds=
SQS.Queue.FifoQueue=
SQS.Queue.FifoThroughputLimit=
SQS.Queue.KmsDataKeyReusePeriodSeconds=
SQS.Queue.KmsMasterKeyId=
SQS.Queue.MaximumMessageSize=
SQS.Queue.MessageRetentionPeriod=
SQS.Queue.QueueName=
SQS.Queue.QueueUrl=IDENTIFIER_OUTPUT
SQS.Queue.ReceiveMessageWaitTimeSeconds=
SQS.Queue.RedriveAllowPolicy=
SQS.Queue.RedrivePolicy=
SQS.Queue.SqsManagedSseEnabled=
SQS.Queue.Tags[].Key=
SQS.Queue.Tags[].Value=
SQS.Queue.VisibilityTimeout=
