SSM.PatchBaseline.Id=IDENTIFIER_OUTPUT
SSM.PatchBaseline.Name=
SSM.PatchBaseline.DefaultBaseline=
SSM.PatchBaseline.OperatingSystem=
SSM.PatchBaseline.Description=
SSM.PatchBaseline.ApprovalRules.PatchRules[].ApproveUntilDate=
SSM.PatchBaseline.ApprovalRules.PatchRules[].EnableNonSecurity=
SSM.PatchBaseline.ApprovalRules.PatchRules[].PatchFilterGroup.PatchFilters[].Values=
SSM.PatchBaseline.ApprovalRules.PatchRules[].PatchFilterGroup.PatchFilters[].Key=
SSM.PatchBaseline.ApprovalRules.PatchRules[].ApproveAfterDays=
SSM.PatchBaseline.ApprovalRules.PatchRules[].ComplianceLevel=
SSM.PatchBaseline.Sources[].Products=
SSM.PatchBaseline.Sources[].Configuration=
SSM.PatchBaseline.Sources[].Name=
SSM.PatchBaseline.RejectedPatches=
SSM.PatchBaseline.ApprovedPatches=
SSM.PatchBaseline.RejectedPatchesAction=
SSM.PatchBaseline.PatchGroups=
SSM.PatchBaseline.ApprovedPatchesComplianceLevel=
SSM.PatchBaseline.ApprovedPatchesEnableNonSecurity=
SSM.PatchBaseline.GlobalFilters.PatchFilters[].Values=
SSM.PatchBaseline.GlobalFilters.PatchFilters[].Key=
SSM.PatchBaseline.AvailableSecurityUpdatesComplianceStatus=
SSM.PatchBaseline.Tags[].Key=
SSM.PatchBaseline.Tags[].Value=
