SSM.MaintenanceWindow.WindowId=IDENTIFIER_OUTPUT
SSM.MaintenanceWindow.Name=
SSM.MaintenanceWindow.StartDate=
SSM.MaintenanceWindow.Description=
SSM.MaintenanceWindow.AllowUnassociatedTargets=
SSM.MaintenanceWindow.Cutoff=
SSM.MaintenanceWindow.Schedule=
SSM.MaintenanceWindow.Duration=
SSM.MaintenanceWindow.ScheduleOffset=
SSM.MaintenanceWindow.EndDate=
SSM.MaintenanceWindow.Tags[].Value=
SSM.MaintenanceWindow.Tags[].Key=
SSM.MaintenanceWindow.ScheduleTimezone=
