SSM.MaintenanceWindowTarget.WindowTargetId=IDENTIFIER_OUTPUT
SSM.MaintenanceWindowTarget.Name=
SSM.MaintenanceWindowTarget.OwnerInformation=
SSM.MaintenanceWindowTarget.Description=
SSM.MaintenanceWindowTarget.WindowId=
SSM.MaintenanceWindowTarget.ResourceType=
SSM.MaintenanceWindowTarget.Targets[].Values=
SSM.MaintenanceWindowTarget.Targets[].Key=
