SSM.MaintenanceWindowTask.WindowTaskId=IDENTIFIER_OUTPUT
SSM.MaintenanceWindowTask.Name=
SSM.MaintenanceWindowTask.MaxErrors=
SSM.MaintenanceWindowTask.Description=
SSM.MaintenanceWindowTask.ServiceRoleArn=
SSM.MaintenanceWindowTask.Priority=
SSM.MaintenanceWindowTask.MaxConcurrency=
SSM.MaintenanceWindowTask.Targets[].Values=
SSM.MaintenanceWindowTask.Targets[].Key=
SSM.MaintenanceWindowTask.TaskArn=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowStepFunctionsParameters.Input=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowStepFunctionsParameters.Name=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.TimeoutSeconds=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.Comment=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.OutputS3KeyPrefix=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.Parameters=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.CloudWatchOutputConfig.CloudWatchOutputEnabled=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.CloudWatchOutputConfig.CloudWatchLogGroupName=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.DocumentHashType=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.ServiceRoleArn=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.NotificationConfig.NotificationEvents=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.NotificationConfig.NotificationArn=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.NotificationConfig.NotificationType=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.DocumentVersion=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.OutputS3BucketName=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowRunCommandParameters.DocumentHash=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowLambdaParameters.Qualifier=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowLambdaParameters.Payload=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowLambdaParameters.ClientContext=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowAutomationParameters.Parameters=
SSM.MaintenanceWindowTask.TaskInvocationParameters.MaintenanceWindowAutomationParameters.DocumentVersion=
SSM.MaintenanceWindowTask.WindowId=
SSM.MaintenanceWindowTask.TaskParameters=
SSM.MaintenanceWindowTask.TaskType=
SSM.MaintenanceWindowTask.CutoffBehavior=
SSM.MaintenanceWindowTask.LoggingInfo.Region=
SSM.MaintenanceWindowTask.LoggingInfo.S3Prefix=
SSM.MaintenanceWindowTask.LoggingInfo.S3Bucket=
