SSM.Association.AssociationId=IDENTIFIER_OUTPUT
SSM.Association.AssociationName=
SSM.Association.CalendarNames=
SSM.Association.ScheduleExpression=
SSM.Association.MaxErrors=
SSM.Association.Parameters=
SSM.Association.InstanceId=
SSM.Association.AssociationDispatchAssumeRole=
SSM.Association.WaitForSuccessTimeoutSeconds=
SSM.Association.MaxConcurrency=
SSM.Association.ComplianceSeverity=
SSM.Association.Targets[].Values=
SSM.Association.Targets[].Key=
SSM.Association.SyncCompliance=
SSM.Association.OutputLocation.S3Location.OutputS3KeyPrefix=
SSM.Association.OutputLocation.S3Location.OutputS3Region=
SSM.Association.OutputLocation.S3Location.OutputS3BucketName=
SSM.Association.ScheduleOffset=
SSM.Association.Name=
SSM.Association.ApplyOnlyAtCronInterval=
SSM.Association.DocumentVersion=
SSM.Association.AutomationTargetParameterName=
SSM.Association.Tags[].Key=
SSM.Association.Tags[].Value=
