WAFv2.WebACL.ApplicationConfig=
WAFv2.WebACL.AssociationConfig=
WAFv2.WebACL.CaptchaConfig.ImmunityTimeProperty.ImmunityTime=
WAFv2.WebACL.ChallengeConfig.ImmunityTimeProperty.ImmunityTime=
WAFv2.WebACL.CustomResponseBodies=
WAFv2.WebACL.DataProtectionConfig=
WAFv2.WebACL.DefaultAction=
WAFv2.WebACL.Description=
WAFv2.WebACL.Id=IDENTIFIER_OUTPUT
WAFv2.WebACL.MonetizationConfig=
WAFv2.WebACL.Name=
WAFv2.WebACL.OnSourceDDoSProtectionConfig=
WAFv2.WebACL.Rules=
WAFv2.WebACL.Scope=
WAFv2.WebACL.Tags[].Key=
WAFv2.WebACL.Tags[].Value=
WAFv2.WebACL.TokenDomains[]=
WAFv2.WebACL.VisibilityConfig.CloudWatchMetricsEnabled=
WAFv2.WebACL.VisibilityConfig.MetricName=
WAFv2.WebACL.VisibilityConfig.SampledRequestsEnabled=
