WAFv2.RuleGroup.Capacity=
WAFv2.RuleGroup.CustomResponseBodies=
WAFv2.RuleGroup.Description=
WAFv2.RuleGroup.MonetizationConfig=
WAFv2.RuleGroup.Name=
WAFv2.RuleGroup.Rules=
WAFv2.RuleGroup.Scope=
WAFv2.RuleGroup.Tags[].Key=
WAFv2.RuleGroup.Tags[].Value=
WAFv2.RuleGroup.VisibilityConfig.CloudWatchMetricsEnabled=
WAFv2.RuleGroup.VisibilityConfig.MetricName=
WAFv2.RuleGroup.VisibilityConfig.SampledRequestsEnabled=
