elasticIp.NATA01EIP.nameTag=eip-web-nginx-dev-nat-a-01
elasticIp.NATA01EIP.domain=vpc
elasticIp.NATA01EIP.allocationStrategy=create-in-stack
elasticIp.NATC02EIP.nameTag=eip-web-nginx-dev-nat-c-02
elasticIp.NATC02EIP.domain=vpc
elasticIp.NATC02EIP.allocationStrategy=create-in-stack
