iamRole.WEBNGINXEC2ROLE01.roleName=webNginxEc2Role
iamRole.WEBNGINXEC2ROLE01.assumeRolePrincipal=ec2.amazonaws.com
iamRole.WEBNGINXEC2ROLE01.assumeRoleAction=sts:AssumeRole
iamRole.WEBNGINXEC2ROLE01.managedPolicyArns=arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
iamRole.WEBNGINXEC2ROLE01.purpose=EC2-bootstrap-and-Session-Manager
