loadBalancer.ALB01.name=alb-dev-web01
loadBalancer.ALB01.scheme=internet-facing
loadBalancer.ALB01.type=application
loadBalancer.ALB01.ipAddressType=ipv4
loadBalancer.ALB01.subnetRefs=subnet.PUBLICAZ1,subnet.PUBLICAZ2
loadBalancer.ALB01.securityGroupRef=securityGroup.ALBSG01
loadBalancer.ALB01.accessLogsEnabled=false
loadBalancer.TG01.name=tgp-dev-web01
loadBalancer.TG01.targetType=instance
loadBalancer.TG01.protocol=HTTP
loadBalancer.TG01.port=80
loadBalancer.TG01.healthCheckProtocol=HTTP
loadBalancer.TG01.healthCheckPath=/
loadBalancer.TG01.healthCheckMatcher=200-399
loadBalancer.TG01.deregistrationDelaySeconds=60
loadBalancer.TG01.vpcRef=vpc.WEBNGINXVPC
loadBalancer.TG01.targetRefs=ec2.EC2AZ1,ec2.EC2AZ2
loadBalancer.HTTP80.loadBalancerRef=loadBalancer.ALB01
loadBalancer.HTTP80.protocol=HTTP
loadBalancer.HTTP80.port=80
loadBalancer.HTTP80.defaultActionTargetRef=loadBalancer.TG01
