natGateway.NATA01.nameTag=natgw-web-nginx-dev-a
natGateway.NATA01.subnetRef=subnet.PUBLICAZ1
natGateway.NATA01.elasticIpRef=elasticIp.NATA01EIP
natGateway.NATA01.connectivityType=public
natGateway.NATC01.nameTag=natgw-web-nginx-dev-c
natGateway.NATC01.subnetRef=subnet.PUBLICAZ2
natGateway.NATC01.elasticIpRef=elasticIp.NATC02EIP
natGateway.NATC01.connectivityType=public
