routeTable.PUBLICRT01.vpcRef=vpc.WEBNGINXVPC
routeTable.PUBLICRT01.nameTag=rtb-web-nginx-dev-public-public-01
routeTable.PUBLICDEFAULT.routeTableRef=routeTable.PUBLICRT01
routeTable.PUBLICDEFAULT.destinationCidrBlock=0.0.0.0/0
routeTable.PUBLICDEFAULT.defaultRouteTargetRef=internetGateway.WEBNGINXIGW
routeTable.PUBLICAZ1ASSOC.routeTableRef=routeTable.PUBLICRT01
routeTable.PUBLICAZ1ASSOC.subnetRef=subnet.PUBLICAZ1
routeTable.PUBLICAZ2ASSOC.routeTableRef=routeTable.PUBLICRT01
routeTable.PUBLICAZ2ASSOC.subnetRef=subnet.PUBLICAZ2
routeTable.PRIVATEAPPARTA01.vpcRef=vpc.WEBNGINXVPC
routeTable.PRIVATEAPPARTA01.nameTag=rtb-web-nginx-dev-app-private-a-01
routeTable.PRIVATEAZ1DEFAULT.routeTableRef=routeTable.PRIVATEAPPARTA01
routeTable.PRIVATEAZ1DEFAULT.destinationCidrBlock=0.0.0.0/0
routeTable.PRIVATEAZ1DEFAULT.defaultRouteTargetRef=natGateway.NATA01
routeTable.PRIVATEAPPAZ1ASSOC.routeTableRef=routeTable.PRIVATEAPPARTA01
routeTable.PRIVATEAPPAZ1ASSOC.subnetRef=subnet.PRIVATEAPPAZ1
routeTable.PRIVATEAPPCRT02.vpcRef=vpc.WEBNGINXVPC
routeTable.PRIVATEAPPCRT02.nameTag=rtb-web-nginx-dev-app-private-c-02
routeTable.PRIVATEAZ2DEFAULT.routeTableRef=routeTable.PRIVATEAPPCRT02
routeTable.PRIVATEAZ2DEFAULT.destinationCidrBlock=0.0.0.0/0
routeTable.PRIVATEAZ2DEFAULT.defaultRouteTargetRef=natGateway.NATC01
routeTable.PRIVATEAPPAZ2ASSOC.routeTableRef=routeTable.PRIVATEAPPCRT02
routeTable.PRIVATEAPPAZ2ASSOC.subnetRef=subnet.PRIVATEAPPAZ2
