securityGroup.ALBSG01.groupDescription=Allow inbound HTTP from the internet to the public ALB.
securityGroup.ALBSG01.groupName=dev-alb-web01-sg
securityGroup.ALBSG01.vpcRef=vpc.WEBNGINXVPC
securityGroup.ALBSG01.attachedResourceRef=loadBalancer.ALB01
securityGroup.ALBSG01.ingressHttp=protocol:tcp,fromPort:80,toPort:80,cidr:0.0.0.0/0
securityGroup.ALBSG01.egressHttp=protocol:tcp,fromPort:80,toPort:80,destinationRef:securityGroup.EC2SG01
securityGroup.EC2SG01.groupDescription=Allow inbound HTTP from the ALB and outbound HTTP/HTTPS for patching and SSM.
securityGroup.EC2SG01.groupName=dev-ec2-app01-sg
securityGroup.EC2SG01.vpcRef=vpc.WEBNGINXVPC
securityGroup.EC2SG01.attachedResourceRefs=ec2.EC2AZ1,ec2.EC2AZ2
securityGroup.EC2SG01.ingressHttp=protocol:tcp,fromPort:80,toPort:80,sourceRef:securityGroup.ALBSG01
securityGroup.EC2SG01.egressHttp=protocol:tcp,fromPort:80,toPort:80,cidr:0.0.0.0/0
securityGroup.EC2SG01.egressHttps=protocol:tcp,fromPort:443,toPort:443,cidr:0.0.0.0/0
securityGroup.EC2SG01.ingressSsh=none
