subnet.PUBLICAZ1.vpcRef=vpc.WEBNGINXVPC
subnet.PUBLICAZ1.nameTag=sbnt-web-nginx-dev-public-public-a-01
subnet.PUBLICAZ1.availabilityZone=ap-northeast-1a
subnet.PUBLICAZ1.cidrBlock=10.0.0.0/24
subnet.PUBLICAZ1.mapPublicIpOnLaunch=true
subnet.PUBLICAZ2.vpcRef=vpc.WEBNGINXVPC
subnet.PUBLICAZ2.nameTag=sbnt-web-nginx-dev-public-public-c-02
subnet.PUBLICAZ2.availabilityZone=ap-northeast-1c
subnet.PUBLICAZ2.cidrBlock=10.0.1.0/24
subnet.PUBLICAZ2.mapPublicIpOnLaunch=true
subnet.PRIVATEAPPAZ1.vpcRef=vpc.WEBNGINXVPC
subnet.PRIVATEAPPAZ1.nameTag=sbnt-web-nginx-dev-app-private-a-01
subnet.PRIVATEAPPAZ1.availabilityZone=ap-northeast-1a
subnet.PRIVATEAPPAZ1.cidrBlock=10.0.10.0/24
subnet.PRIVATEAPPAZ1.mapPublicIpOnLaunch=false
subnet.PRIVATEAPPAZ2.vpcRef=vpc.WEBNGINXVPC
subnet.PRIVATEAPPAZ2.nameTag=sbnt-web-nginx-dev-app-private-c-02
subnet.PRIVATEAPPAZ2.availabilityZone=ap-northeast-1c
subnet.PRIVATEAPPAZ2.cidrBlock=10.0.11.0/24
subnet.PRIVATEAPPAZ2.mapPublicIpOnLaunch=false
