Macie.ClassificationJob.allowListIds=
Macie.ClassificationJob.customDataIdentifierIds=
Macie.ClassificationJob.description=
Macie.ClassificationJob.initialRun=
Macie.ClassificationJob.jobId=IDENTIFIER_OUTPUT
Macie.ClassificationJob.jobType=
Macie.ClassificationJob.managedDataIdentifierIds=
Macie.ClassificationJob.managedDataIdentifierSelector=
Macie.ClassificationJob.name=
Macie.ClassificationJob.s3JobDefinition=
Macie.ClassificationJob.samplingPercentage=
Macie.ClassificationJob.scheduleFrequency=
Macie.ClassificationJob.tags=
